// Word meanings for the study card: part of speech, a plain-English definition and a few
// related words, for every built-in word. Richer than the one-line `hint` in WORD_LIST,
// which is still what the recall-stage hints and custom/AI words use.
//
// Row format:  "part of speech | definition | related, words (optional)"
//  - Definitions use simple words and never contain the word itself.
//  - They must not contain a US-only or UK-only spelling (color/colour, center/centre...):
//    the app shows both styles, and only the headword is switched.
//  - Keyed by the US spelling; British variants resolve through WORD_LIST.variants.
(() => {
  "use strict";

  const ROWS = {
    // ---------- beginner ----------
    cat: "noun | A small furry animal that people keep as a pet. It purrs and meows. | kitten",
    dog: "noun | A common pet animal that barks and is often kept as a companion. | puppy, hound",
    sun: "noun | The star that gives the Earth its light and heat. | sunshine, daylight",
    run: "verb | To move quickly on foot; also to manage or operate something. | sprint, jog",
    jump: "verb | To push yourself off the ground into the air. | leap, hop",
    frog: "noun | A small animal with long back legs that lives near water and hops. | toad",
    milk: "noun | A white liquid from cows that people drink and use in food. | dairy",
    book: "noun | Pages joined together inside a cover, for reading or writing in. | novel, volume",
    happy: "adjective | Feeling joy or pleasure. | glad, cheerful, joyful",
    apple: "noun | A round, crisp fruit with red, green or yellow skin. | fruit",
    house: "noun | A building where a family lives. | home, residence",
    water: "noun | The clear liquid in rivers and rain that people drink. As a verb, to give it to plants. | liquid",
    green: "adjective | Having the shade of fresh grass and leaves. | emerald, leafy",
    smile: "verb | To turn up the corners of your mouth to show you are happy or friendly. | grin, beam",
    chair: "noun | A seat for one person, with a back. | seat, stool",

    // ---------- everyday ----------
    because: "conjunction | Used to give the reason for something. | since, as",
    friend: "noun | A person you know well and like. | pal, companion",
    believe: "verb | To accept that something is true, or that someone is telling the truth. | trust, accept",
    separate: "verb / adjective | To divide or keep apart; or not joined to anything else. | divide, apart",
    definitely: "adverb | Without any doubt; for sure. | certainly, surely",
    necessary: "adjective | Needed; something you must have or do. | essential, required",
    receive: "verb | To get something that is given or sent to you. | get, accept",
    though: "conjunction | In spite of the fact that. | although, even if",
    beautiful: "adjective | Very pleasing to look at, hear or experience. | lovely, gorgeous",
    science: "noun | The study of nature and the physical world through observation and experiments. | biology, physics",
    people: "noun | Men, women and children; human beings. | persons, public",
    different: "adjective | Not the same as something else. | unlike, distinct",
    favorite: "adjective / noun | Liked more than all the others. | preferred, best-loved",
    weird: "adjective | Strange or unusual in a way that is hard to explain. | odd, strange",
    environment: "noun | The natural world, or the conditions in which people, animals and plants live. | nature, surroundings",
    government: "noun | The group of people who rule a country and make its big decisions. | administration, state",
    restaurant: "noun | A place where you pay to sit down and eat a meal. | cafe, diner",
    calendar: "noun | A chart showing the days, weeks and months of the year. | diary, planner",
    vacuum: "noun / verb | A space with no air in it; also a machine that cleans by sucking up dust. | cleaner",
    rhythm: "noun | A regular, repeated pattern of sounds or beats. | beat, tempo",
    language: "noun | The system of words people use to speak and write. | speech, tongue",
    surprise: "noun / verb | Something unexpected; or to make someone feel astonished. | shock, astonish",
    immediately: "adverb | Right now, without any delay. | at once, instantly",
    occasion: "noun | A particular time, or a special event. | event, celebration",
    embarrass: "verb | To make someone feel shy, awkward or ashamed. | shame, humiliate",
    knowledge: "noun | The facts and skills you have learned. | learning, understanding",
    guarantee: "noun / verb | A promise that something will be done or will happen. | promise, assure",
    mischievous: "adjective | Playful in a way that causes small amounts of trouble. | naughty, playful",
    neighbor: "noun | A person who lives next door or very near to you. | resident",
    achieve: "verb | To succeed in reaching a goal through effort. | accomplish, attain",
    although: "conjunction | In spite of the fact that. | though, even though",
    business: "noun | Work done to earn money, or a company that does it. | company, trade",
    column: "noun | A tall upright pillar; or a vertical line of numbers or text. | pillar, post",
    foreign: "adjective | From or belonging to another country. | overseas, alien",
    grateful: "adjective | Feeling thankful for something someone has done. | thankful, appreciative",
    height: "noun | How tall a person or thing is. | tallness, altitude",
    island: "noun | A piece of land completely surrounded by water. | isle",
    jewelry: "noun | Decorations such as rings and necklaces that people wear. | gems, ornaments",
    library: "noun | A place where books are kept for people to read or borrow. | archive",
    medicine: "noun | A drug you take to treat an illness; also the science of treating illness. | drug, remedy",
    opposite: "adjective / preposition | Completely different; or facing something from across. | reverse, contrary",
    possible: "adjective | Able to happen or to be done. | achievable, feasible",
    question: "noun / verb | A sentence you ask to get information; or to doubt something. | query, inquiry",
    rhyme: "noun / verb | Words that end with the same sound, such as “cat” and “hat”. | verse, poem",
    schedule: "noun / verb | A plan that lists when things will happen. | timetable, plan",
    tomorrow: "adverb / noun | The day after today. | next day",
    umbrella: "noun | A folding cover you hold over your head to keep off the rain. | parasol",
    vegetable: "noun | A plant, or part of one, that is eaten as food, such as a carrot. | produce",
    weather: "noun | The daily conditions outside, such as sun, rain and wind. | climate",

    // ---------- expert ----------
    conscientious: "adjective | Careful and thorough, taking your duties seriously. | diligent, careful",
    onomatopoeia: "noun | A word that sounds like the thing it names, such as “buzz”. | sound word",
    bureaucracy: "noun | A system with many rules and officials that can make things slow. | red tape, administration",
    questionnaire: "noun | A set of written questions used to gather information. | survey, form",
    entrepreneur: "noun | A person who starts a business and takes financial risks. | businessperson, founder",
    chrysanthemum: "noun | A garden flower with many layered petals. | flower, bloom",
    idiosyncrasy: "noun | A strange or personal habit that makes someone different from others. | quirk, oddity",
    connoisseur: "noun | A person with expert knowledge and taste in a subject such as food or art. | expert, judge",
    camouflage: "noun / verb | Patterns or shades that help something blend into its surroundings. | disguise",
    silhouette: "noun | A dark shape seen against a lighter background. | outline, shadow",
    rhinoceros: "noun | A large, heavy animal with thick skin and one or two horns on its nose. | rhino",
    acquaintance: "noun | A person you know a little but not well. | contact",
    millennium: "noun | A period of one thousand years. | thousand years",
    hierarchy: "noun | A system that ranks people or things from highest to lowest. | ranking, order",
    phenomenon: "noun | An event or fact that can be observed and is remarkable or hard to explain. | event, occurrence",
    pneumonia: "noun | A serious lung illness caused by infection. | lung infection",
    cappuccino: "noun | An Italian coffee with hot, frothy milk on top. | latte",
    kaleidoscope: "noun | A tube with mirrors and bits of glass that makes changing patterns when turned. | pattern",

    // ---------- more beginner ----------
    bird: "noun | An animal with feathers and wings that can usually fly. | creature",
    fish: "noun | An animal that lives in water and breathes through gills. | seafood",
    tree: "noun | A tall plant with a thick trunk, branches and leaves. | plant",
    star: "noun | A bright point of light in the night sky; also a famous performer. | celebrity",
    moon: "noun | The large round object that moves around the Earth and shines at night. | satellite",
    ball: "noun | A round object used in games; also a formal dance party. | sphere",
    cake: "noun | A sweet baked food made from flour, eggs and sugar. | pastry, dessert",
    bike: "noun | A vehicle with two wheels that you ride by pushing pedals. | bicycle, cycle",
    rain: "noun / verb | Water that falls from clouds in drops. | shower, drizzle",
    snow: "noun | Soft white flakes of frozen water that fall from the sky. | frost, sleet",
    shoe: "noun | A strong covering for the foot. | boot, sandal",
    hand: "noun | The part at the end of your arm, with fingers and a thumb. | palm",
    door: "noun | A panel that opens and closes an entrance. | entrance, gate",
    desk: "noun | A table, often with drawers, used for reading and writing. | table, workstation",
    lamp: "noun | A device that gives light. | light",
    picture: "noun | A drawing, painting or photograph. | image, photo",
    another: "determiner | One more; a different one. | additional, other",
    thought: "noun / verb | An idea in your mind; also the past tense of “think”. | idea, notion",
    through: "preposition | From one end or side of something to the other. | across, via",
    careful: "adjective | Paying attention so as to avoid mistakes or danger. | cautious, watchful",
    kitchen: "noun | A room where food is cooked. | galley",
    morning: "noun | The early part of the day, until about noon. | dawn, daybreak",
    evening: "noun | The part of the day between afternoon and night. | dusk, sunset",
    holiday: "noun | A day or period of rest from work or school. | break, time off",
    cousin: "noun | A child of your aunt or uncle. | relative",
    sister: "noun | A girl or woman with the same parents as you. | sibling",
    brother: "noun | A boy or man with the same parents as you. | sibling",
    teacher: "noun | A person whose job is to help others learn. | tutor, instructor",
    student: "noun | A person who is studying at a school or college. | pupil, learner",
    journey: "noun | The act of going from one place to another, usually over a long distance. | trip, voyage",
    hungry: "adjective | Wanting or needing food. | starving, famished",
    thirsty: "adjective | Wanting or needing something to drink. | parched",
    thankful: "adjective | Pleased and grateful for something. | grateful",
    birthday: "noun | The day each year when you celebrate the day you were born. | anniversary",
    remember: "verb | To keep something in your mind or bring it back to mind. | recall, recollect",
    alphabet: "noun | The set of letters used to write a language. | letters",
    computer: "noun | An electronic machine that stores and processes information. | laptop",
    continue: "verb | To keep going, or to start again after a pause. | carry on, proceed",
    decision: "noun | A choice you make after thinking about it. | choice, verdict",
    exercise: "noun / verb | Physical activity that keeps the body healthy; or a task for practice. | workout, training",
    furniture: "noun | Movable things in a room, such as chairs, tables and beds. | furnishings",
    direction: "noun | The way something is moving or facing; or instructions on what to do. | route, course",
    character: "noun | A person in a story; or the qualities that make someone who they are. | personality, role",
    adventure: "noun | An exciting or unusual experience. | quest, journey",
    chocolate: "noun | A sweet food made from roasted cocoa beans. | cocoa, sweet",
    dangerous: "adjective | Likely to cause harm. | risky, unsafe",
    difficult: "adjective | Hard to do or to understand. | hard, tough",
    vacation: "noun | A period of time spent away from home or work for rest or travel. | holiday, break",
    mountain: "noun | A very high hill with steep sides. | peak, summit",
    thousand: "number | The number 1,000. | ",
    hospital: "noun | A place where sick or injured people are treated. | clinic",
    dictionary: "noun | A book or website that explains the meanings of words. | glossary",
    temperature: "noun | How hot or cold something is. | heat",
    disappear: "verb | To go out of sight or stop existing. | vanish, fade",
    disappoint: "verb | To make someone sad by not being as good as they hoped. | let down, upset",
    appreciate: "verb | To value something or be thankful for it. | value, cherish",
    communicate: "verb | To share information, ideas or feelings with others. | talk, convey",
    experience: "noun / verb | Knowledge gained from doing something; or something that happens to you. | skill, event",
    imagination: "noun | The ability to form pictures and ideas in your mind. | creativity, fantasy",
    information: "noun | Facts or details about something. | data, facts",
    personality: "noun | The qualities that make a person who they are. | character, nature",
    professional: "adjective / noun | Done by a person who is trained and paid for the work. | expert, skilled",
    unfortunately: "adverb | Used to say that something is a pity or bad luck. | sadly, regrettably",
    responsibility: "noun | A duty to take care of something or someone. | duty, obligation",
    extraordinary: "adjective | Very unusual or remarkable. | remarkable, amazing",
    conscience: "noun | The inner sense of what is right and wrong. | morals",
    pronunciation: "noun | The way a word is said. | speech, accent",
    miscellaneous: "adjective | Of various kinds that do not belong together. | assorted, mixed",
    unprecedented: "adjective | Never done or known before. | unheard-of, new",
    indispensable: "adjective | So important that you cannot do without it. | essential, vital",
    subconscious: "adjective / noun | Happening in your mind without you being aware of it. | instinctive, hidden",
    exaggerate: "verb | To make something seem bigger or better than it really is. | overstate, inflate",
    maintenance: "noun | The work of keeping something in good condition. | upkeep, repair",
    questionable: "adjective | Doubtful; not clearly honest or good. | doubtful, dubious",
    perseverance: "noun | Continuing to try hard even when things are difficult. | persistence, determination",
    vulnerable: "adjective | Easily hurt or harmed. | exposed, weak",

    // ---------- US / UK spelling pairs ----------
    color: "noun | The look of something such as red, blue or yellow, caused by how it reflects light. | shade, hue",
    honor: "noun / verb | Great respect; or to show respect to someone. | respect, glory",
    flavor: "noun | The taste of a food or drink. | taste, tang",
    humor: "noun | The quality of being funny; the ability to enjoy fun. | comedy, wit",
    labor: "noun | Hard physical work. | toil, work",
    rumor: "noun | A story that people pass on and that may not be true. | gossip, hearsay",
    harbor: "noun | A sheltered area of water where ships stay safe. | port, dock",
    vapor: "noun | A mist or gas made when a liquid is heated. | steam, mist",
    center: "noun | The middle point or part of something. | middle, core",
    theater: "noun | A building where plays are performed. | playhouse, stage",
    meter: "noun | A unit of length in the metric system, equal to 100 cm. | unit",
    liter: "noun | A unit of volume for liquids in the metric system. | unit",
    fiber: "noun | A thin thread of material; also the part of food that helps digestion. | thread, strand",
    organize: "verb | To arrange things in a clear, ordered way. | arrange, sort",
    realize: "verb | To understand or notice something, often suddenly. | notice, understand",
    recognize: "verb | To know someone or something because you have seen it before. | identify, know",
    apologize: "verb | To say you are sorry. | say sorry",
    memorize: "verb | To learn something so you can remember it exactly. | learn by heart",
    catalog: "noun / verb | A list of items, often with descriptions and pictures. | list, directory",
    dialog: "noun | A conversation between two or more people. | conversation, discussion",
    defense: "noun | Action taken to protect against attack. | protection, guard",
    license: "noun | Official permission to do or own something. | permit, certificate",
    traveling: "verb | Going from one place to another. | journeying, touring",
    canceled: "verb | Decided that a planned event will not take place. | called off",
    gray: "adjective | The shade between black and white, like rain clouds. | silver, ash",
    pajamas: "noun | Loose clothes that you wear in bed. | nightclothes",
    mustache: "noun | Hair growing on the upper lip. | whiskers",
    fulfill: "verb | To do or complete what is needed or promised. | achieve, satisfy",

    // ---------- hard ----------
    achievement: "noun | Something good that you have done successfully through effort. | accomplishment, success",
    committee: "noun | A group of people chosen to make decisions or plans for a larger group. | board, panel",
    conscious: "adjective | Awake and aware of what is around you. | aware, awake",
    existence: "noun | The state of being real or alive. | being, life",
    independent: "adjective | Not controlled by others; able to manage on your own. | free, self-reliant",
    occurrence: "noun | Something that happens. | event, incident",
    parallel: "adjective | Running side by side with the same distance between, and never meeting. | alongside, equidistant",
    possession: "noun | Something that you own. | belonging, property",
    privilege: "noun | A special right or benefit that only some people have. | advantage, right",
    recommend: "verb | To suggest that something is good or should be done. | suggest, advise",
    sincerely: "adverb | In a way that is honest and genuine. | truly, honestly",
    cemetery: "noun | A place where dead people are buried. | graveyard",
    handkerchief: "noun | A small piece of cloth used to wipe your nose or face. | tissue",
    sacrilege: "noun | Treating something holy, or greatly respected, without respect. | blasphemy",
    yacht: "noun | A boat with sails or an engine used for pleasure or racing. | sailboat",
    colonel: "noun | A high-ranking officer in the army. | officer",
    accommodate: "verb | To provide space for; or to fit what someone needs. | house, suit",
    acquiesce: "verb | To agree or accept without arguing. | consent, comply",
    liaison: "noun | A link that helps people or groups work together. | contact, connection",
    reminiscence: "noun | The act of remembering past events. | memory, recollection",
    renaissance: "noun | A new growth of interest in art or ideas; also the period in Europe from about the 14th to the 17th century. | revival, rebirth",
    sovereignty: "noun | The power of a country to rule itself. | independence, authority",
    surreptitious: "adjective | Done secretly so that others do not notice. | secret, stealthy",
    unanimous: "adjective | Agreed by everyone, with no one against. | united, undivided",
    vengeance: "noun | Punishment given to someone in return for harm they caused. | revenge",
    whimsical: "adjective | Playful and unusual in a charming way. | playful, fanciful",

    // ---------- more expert ----------
    camaraderie: "noun | Friendship and trust among people who spend time together. | fellowship, friendship",
    gauge: "noun / verb | A tool that measures something; or to judge something. | dial, measure",
    inoculate: "verb | To protect someone from a disease by giving them a vaccine. | vaccinate",
    juxtapose: "verb | To put two things next to each other to show how they differ. | compare, contrast",
    labyrinth: "noun | A complicated network of paths that is hard to find your way through. | maze",
    mnemonic: "noun | A trick or short rhyme that helps you remember something. | memory aid",
    paraphernalia: "noun | Many small items needed for a particular activity. | equipment, gear",
    pharaoh: "noun | A king of ancient Egypt. | ruler",
    supersede: "verb | To take the place of something older or less suitable. | replace, succeed",
    cinnamon: "noun | A sweet brown spice made from tree bark. | spice",
    physician: "noun | A doctor, especially one trained in medicine. | doctor",
    resemblance: "noun | The way two things look alike. | similarity, likeness",
    trustworthy: "adjective | Able to be relied on; honest. | reliable, dependable",
    prestigious: "adjective | Respected and admired because of high status. | respected, esteemed",
  // ---------- wave 2: beginner ----------
    hat: "noun | A piece of clothing that you wear on your head. | cap, helmet",
    pen: "noun | A tool for writing or drawing with ink. | ballpoint, marker",
    pig: "noun | A farm animal with a curly tail and a flat nose that makes an oinking sound. | hog, piglet",
    cup: "noun | A small round container with a handle, used for drinking. | mug, glass",
    bed: "noun | A piece of furniture that you lie on to sleep. | bunk, cot",
    bus: "noun | A large vehicle that carries many passengers along a road. | coach, transport",
    egg: "noun | An oval object laid by a hen or another bird; people also eat it. | yolk, shell",
    red: "adjective / noun | The shade of a ripe strawberry or a stop sign. | scarlet, crimson",
    sit: "verb | To rest with your weight on your bottom instead of on your feet. | perch, settle",
    ship: "noun | A large vessel that carries people or goods across the sea. | vessel, liner",
    duck: "noun | A water bird with a flat bill that quacks and swims. | drake, mallard",
    nest: "noun | A home that a bird makes for its eggs and chicks. | roost, shelter",
    farm: "noun | Land and buildings used for growing crops or keeping animals. | ranch, field",
    corn: "noun | A tall plant that grows yellow seeds on a cob, or the seeds themselves. | maize, kernel",
    boat: "noun | A small vessel that floats and moves across water. | canoe, dinghy",
    road: "noun | A hard path for cars, buses and bikes to travel on. | street, lane",
    kite: "noun | A light toy that flies in the wind on a long string. | string, toy",
    home: "noun | The house or place where a person or family lives. | house, dwelling",
    soup: "noun | A hot liquid food made by boiling vegetables, meat or noodles in water. | broth, stew",
    leaf: "noun | A flat, usually green part that grows from the stem of a plant. | frond, foliage",
    baby: "noun | A very young child who cannot yet walk or talk. | infant, newborn",
    sofa: "noun | A long, soft seat with arms and a back for several people. | couch, settee",
    play: "verb / noun | To take part in a game or do something for fun. | frolic, perform",
    plane: "noun | A vehicle with wings and engines that flies through the air. | aircraft, jet",
    train: "noun | A line of linked carriages pulled along railway tracks. | locomotive, railway",
    bread: "noun | A baked food made from flour, often cut into slices. | loaf, toast",
    plate: "noun | A flat dish that food is served on. | dish, platter",
    spoon: "noun | A tool with a small bowl on a handle, used for eating or stirring. | ladle, utensil",
    horse: "noun | A large, strong animal with hooves that people ride. | pony, stallion",
    clock: "noun | A device that shows the time. | timer, watch",
    sheep: "noun | A farm animal with a thick woolly coat. | lamb, ram",
    cloud: "noun | A mass of tiny water drops floating in the sky. | mist, fog",
    stone: "noun | A small piece of rock. | pebble, rock",
    grass: "noun | A low green plant that covers fields and lawns. | lawn, turf",
    pizza: "noun | A flat round bread baked with tomato sauce, cheese and other toppings. | slice, crust",

  // ---------- wave 2: easy ----------
    they: "pronoun | Used to talk about two or more people or things that have already been mentioned. | them, their",
    said: "verb | Spoke words out loud; the past form of the verb meaning to speak. | spoke, told",
    were: "verb | The past form of “are”, used with we, you and they. | was, are",
    would: "verb | A helper word used to ask politely or to talk about something that might happen. | could, should",
    could: "verb | A helper word that shows ability in the past or that something is possible. | can, might",
    should: "verb | A helper word used to say what is right or sensible to do. | ought, must",
    enough: "adjective / adverb | As much as is needed; no more is required. | sufficient, plenty",
    laugh: "verb / noun | To make happy sounds with your voice when something is funny. | giggle, chuckle",
    write: "verb | To put letters or words on paper or a screen. | scribble, type",
    wrong: "adjective | Not correct or not true. | incorrect, mistaken",
    knee: "noun | The joint in the middle of your leg where it bends. | joint, kneecap",
    knife: "noun | A tool with a sharp blade for cutting. | blade, cutter",
    knock: "verb / noun | To hit something firmly, especially a door, to make a noise. | tap, rap",
    climb: "verb | To go up something using your hands and feet. | scale, ascend",
    listen: "verb | To pay attention so that you can hear something. | hear, attend",
    answer: "noun / verb | A reply to a question; or to give such a reply. | reply, response",
    whistle: "verb / noun | To make a high, clear sound by blowing air through your lips; or a small tool that does this. | toot, signal",
    honest: "adjective | Truthful and fair; not lying or cheating. | truthful, sincere",
    hour: "noun | A period of time lasting sixty minutes. | period, time",
    ghost: "noun | The spirit of a dead person that some people say they can see. | spirit, phantom",
    castle: "noun | A large strong building with thick walls, built long ago to keep people safe. | fortress, palace",
    walk: "verb / noun | To move along on foot at a steady pace. | stroll, stride",
    again: "adverb | One time more; once more. | once more, anew",
    heart: "noun | The organ in your chest that pumps blood around your body. | organ, pulse",
    early: "adjective / adverb | Happening before the usual or expected time. | soon, ahead",
    guess: "verb / noun | To give an answer when you are not sure it is right. | estimate, suppose",
    guide: "noun / verb | A person who shows others the way; or to lead someone along a route. | lead, escort",
    busy: "adjective | Having a lot to do; not free. | occupied, active",
    once: "adverb | One time only; at a time in the past. | formerly, previously",
    country: "noun | A land with its own government and borders, or the countryside away from towns. | nation, land",
    young: "adjective | In an early stage of life; not old. | youthful, little",
    group: "noun | A number of people or things that are together or belong together. | set, team",
    minute: "noun | A period of time lasting sixty seconds. | moment, second",
    sugar: "noun | A sweet substance used to make food and drinks taste sweet. | sweetener, syrup",
    orange: "noun / adjective | A round juicy fruit with a thick peel; also the bright shade between red and yellow. | citrus, tangerine",
    breakfast: "noun | The first meal you eat in the morning. | morning meal, brunch",
    ocean: "noun | A very large area of salt water that covers much of the Earth. | sea, deep",
    thunder: "noun | The loud rumbling noise heard in the sky during a storm. | rumble, storm",
    feather: "noun | One of the light, soft parts that cover a bird’s body. | plume, down",
    forest: "noun | A large area of land thickly covered with trees. | woods, jungle",
    garden: "noun | A piece of ground where people grow flowers, fruit or vegetables. | yard, lawn",
    window: "noun | An opening in a wall, filled with glass, that lets in light and air. | pane, glass",
    pencil: "noun | A thin wooden tool with a soft black core, used for writing or drawing. | crayon, lead",
    family: "noun | A group of people who are related, such as parents and their children. | relatives, household",
    giant: "noun / adjective | A very large imaginary person; or something extremely big. | titan, enormous",

  // ---------- wave 2: medium ----------
    address: "noun / verb | The details of where a person lives or where a building is; or to speak to someone formally. | location, residence",
    argument: "noun | A disagreement in which people state different views; or a set of reasons given to support an idea. | debate, quarrel",
    beginning: "noun | The point at which something starts. | start, opening",
    bargain: "noun / verb | Something bought for less than its usual price; or an agreement between people. | deal, discount",
    behavior: "noun | The way a person or animal acts. | conduct, manners",
    cozy: "adjective | Warm, comfortable and safe. | snug, comfy",
    analyze: "verb | To study something carefully to understand how it works or what it means. | examine, study",
    courage: "noun | The ability to do something brave even when you feel afraid. | bravery, nerve",
    curious: "adjective | Eager to learn or find out about something; also strange. | inquisitive, interested",
    delicious: "adjective | Having a very pleasant taste or smell. | tasty, yummy",
    describe: "verb | To say what someone or something is like, using words. | explain, portray",
    fierce: "adjective | Angry, aggressive and frightening; or very strong. | wild, savage",
    guard: "verb / noun | To protect someone or something from danger; or a person who does this. | protect, defend",
    guitar: "noun | A musical instrument with strings that you pluck or strum. | string, instrument",
    interrupt: "verb | To stop someone while they are speaking or doing something. | disturb, cut in",
    lightning: "noun | A bright flash of light in the sky during a storm. | flash, bolt",
    muscle: "noun | A part of the body that tightens and relaxes to make you move. | tissue, strength",
    ordinary: "adjective | Normal and usual, not special or different. | normal, typical",
    peculiar: "adjective | Strange or odd in a way that is hard to explain. | odd, unusual",
    permanent: "adjective | Lasting for a very long time or for ever. | lasting, fixed",
    pollution: "noun | Harmful substances that make air, water or land dirty. | smog, waste",
    recipe: "noun | A set of instructions for making a particular food. | method, formula",
    sandwich: "noun | Two slices of bread with a filling between them. | snack, roll",
    secretary: "noun | A person who handles letters, calls and appointments for an office or a boss. | assistant, clerk",
    stomach: "noun | The part of the body where food goes after you swallow it. | belly, tummy",
    strength: "noun | The quality of being strong. | power, force",
    success: "noun | The good result of trying to do something; reaching a goal. | triumph, achievement",
    suddenly: "adverb | Quickly and without any warning. | abruptly, swiftly",
    tongue: "noun | The soft part inside your mouth that you use for tasting and speaking. | taste, language",
    usually: "adverb | In most cases; on most days. | normally, generally",
    weight: "noun | A measure of how heavy someone or something is. | mass, heaviness",
    interesting: "adjective | Holding your attention or making you want to know more. | fascinating, absorbing",
    comfortable: "adjective | Pleasantly relaxing, with no pain or worry. | snug, relaxed",
    excellent: "adjective | Extremely good; of very high quality. | superb, outstanding",
    accident: "noun | An unexpected event that causes harm or damage, usually not on purpose. | mishap, crash",
    accept: "verb | To take something that is offered, or to agree that it is true. | receive, agree",
    celebrate: "verb | To do something enjoyable to mark a special day or event. | party, commemorate",
    climate: "noun | The usual weather of a place over a long time. | weather, conditions",
    conversation: "noun | A talk between two or more people. | chat, discussion",
    enormous: "adjective | Extremely large in size or amount. | huge, gigantic",
    exciting: "adjective | Making you feel happy, interested and full of energy. | thrilling, lively",
    forehead: "noun | The part of the face above the eyebrows and below the hair. | brow, temple",
    frighten: "verb | To make someone feel afraid. | scare, alarm",
    gorgeous: "adjective | Very beautiful or very pleasing to look at. | stunning, lovely",
    grammar: "noun | The rules for how words are put together in a language. | syntax, usage",
    mystery: "noun | Something strange or secret that people cannot explain. | puzzle, riddle",
    quiet: "adjective | Making little or no noise. | silent, calm",
    receipt: "noun | A piece of paper that shows you have paid for something. | ticket, proof",
    scissors: "noun | A tool with two blades that cut when you squeeze the handles. | shears, blades",
    straight: "adjective / adverb | Going in one direction without a bend or curve. | direct, level",

  // ---------- wave 2: hard ----------
    accessible: "adjective | Able to be reached, entered or used by people. | reachable, available",
    accidentally: "adverb | By chance or by mistake, not on purpose. | unintentionally, by mistake",
    acknowledge: "verb | To accept or admit that something is true or exists; or to show thanks. | admit, accept",
    ambiguous: "adjective | Having more than one possible meaning, so not clear. | unclear, vague",
    apparently: "adverb | As far as one can tell from what is seen or heard. | seemingly, evidently",
    atmosphere: "noun | The layer of gases around a planet; or the feeling of a place. | air, mood",
    auxiliary: "adjective | Providing extra help or support. | extra, backup",
    beneficial: "adjective | Helpful or good for someone or something. | helpful, useful",
    bizarre: "adjective | Very strange or unusual. | odd, peculiar",
    boundary: "noun | A line that marks the edge of an area. | border, limit",
    bruise: "noun / verb | A dark mark on the skin where the body has been hit. | mark, injury",
    catastrophe: "noun | A sudden event that causes great damage or suffering. | disaster, calamity",
    chauffeur: "noun | A person whose job is to drive someone else’s car. | driver, escort",
    circumstance: "noun | A fact or condition connected with an event or situation. | situation, condition",
    compliment: "noun / verb | A kind or admiring remark; or to say something nice to someone. | praise, flattery",
    consensus: "noun | General agreement among a group of people. | agreement, accord",
    criticize: "verb | To say what you think is wrong or bad about someone or something. | judge, fault",
    curriculum: "noun | The set of subjects and lessons taught at a school. | syllabus, course",
    desperate: "adjective | Feeling that a situation is so bad that you will try anything. | frantic, hopeless",
    discipline: "noun | Training that teaches people to follow rules and control themselves. | control, training",
    dilemma: "noun | A difficult choice between two or more options. | predicament, quandary",
    eccentric: "adjective | Behaving in an unusual way that is different from most people. | quirky, odd",
    efficient: "adjective | Working well without wasting time, effort or money. | capable, productive",
    emphasize: "verb | To show that something is especially important. | stress, highlight",
    enthusiasm: "noun | Strong excitement and interest in something. | eagerness, passion",
    equipment: "noun | The tools and items needed for a particular job or activity. | gear, apparatus",
    especially: "adverb | More than usual; in particular. | particularly, mainly",
    familiar: "adjective | Well known to you because you have seen or met it often. | known, common",
    fluorescent: "adjective | Giving off bright light, as in some lamps and bright clothing. | glowing, luminous",
    fundamental: "adjective | Forming the basic or most important part of something. | basic, essential",
    harassment: "noun | Repeated unkind actions that upset or bother someone. | bullying, pestering",
    hypocrite: "noun | A person who says one thing but does another. | pretender, fraud",
    incidentally: "adverb | Used to add a related remark or to change the subject. | by the way, besides",
    irrelevant: "adjective | Not connected to the matter being discussed. | unrelated, beside the point",
    jealous: "adjective | Unhappy because you want what someone else has. | envious, resentful",
    judgment: "noun | A decision or opinion formed after careful thought. | decision, verdict",
    leisure: "noun | Free time when you can relax and enjoy yourself. | rest, spare time",
    lieutenant: "noun | An officer of middle rank in the army, navy or police. | officer, commander",
    maneuver: "noun / verb | A careful, skilled movement; or to move something into position with skill. | move, steer",
    mathematics: "noun | The study of numbers, shapes and how they relate. | arithmetic, algebra",
    miniature: "adjective / noun | A very small version of something; or very small. | tiny, model",
    noticeable: "adjective | Easy to see or spot; clear enough to attract attention. | obvious, visible",
    occasionally: "adverb | Now and then; not often. | sometimes, periodically",
    pastime: "noun | An activity you do for fun in your free time. | hobby, activity",
    pursue: "verb | To follow or chase someone or something; or to work toward a goal. | chase, seek",
    sergeant: "noun | An officer of middle rank in the army or police. | officer, soldier",
    skeptical: "adjective | Doubtful and not easily convinced that something is true. | doubtful, unconvinced",
    solemn: "adjective | Serious and dignified, not cheerful. | serious, grave",
    subtle: "adjective | Slight and delicate; not obvious or easy to notice. | slight, delicate",
    thorough: "adjective | Complete and careful; leaving nothing out. | complete, detailed",

  // ---------- wave 2: expert ----------
    aficionado: "noun | A person who knows a lot about a subject and loves it, such as a sport or an art. | enthusiast, fan",
    ambidextrous: "adjective | Able to use the left and right hand equally well. | skilled, versatile",
    anachronism: "noun | Something that belongs to a different time from the one it appears in. | mismatch, relic",
    anesthesia: "noun | Medicine or a treatment that stops a person feeling pain, often during surgery. | numbing, sedation",
    antediluvian: "adjective | Extremely old-fashioned; belonging to the time before the flood in the Bible. | ancient, outdated",
    apocryphal: "adjective | Widely told as true but probably not real. | doubtful, unverified",
    archipelago: "noun | A group of many islands close together. | islands, chain",
    bourgeois: "adjective / noun | Belonging to the middle class, often with a focus on money and comfort. | middle-class, conventional",
    cacophony: "noun | A harsh, unpleasant mixture of loud sounds. | racket, din",
    chiaroscuro: "noun | The use of strong contrasts of light and dark in a painting or photograph. | contrast, shading",
    clandestine: "adjective | Kept secret, often because it is not allowed. | secret, hidden",
    curmudgeon: "noun | A bad-tempered, grumpy person. | grouch, crank",
    demagogue: "noun | A political leader who wins support by playing on people’s fears and feelings. | agitator, rabble-rouser",
    dilettante: "noun | A person who takes an interest in a subject without deep knowledge or serious effort. | amateur, dabbler",
    ebullient: "adjective | Full of cheerful energy and enthusiasm. | cheerful, exuberant",
    eclectic: "adjective | Choosing ideas or styles from many different sources. | varied, diverse",
    ephemeral: "adjective | Lasting for only a very short time. | brief, fleeting",
    epitome: "noun | A perfect example of a quality or type. | model, embodiment",
    esoteric: "adjective | Known or understood by only a small group of people. | obscure, specialized",
    euphemism: "noun | A mild word used in place of one that sounds harsh or rude. | substitute, softener",
    facetious: "adjective | Treating serious things with silly or joking remarks. | flippant, joking",
    fastidious: "adjective | Very careful about details and hard to please. | particular, picky",
    flamboyant: "adjective | Bold, showy and full of style. | showy, dramatic",
    gregarious: "adjective | Enjoying the company of other people; sociable. | sociable, outgoing",
    haphazard: "adjective | Done in a careless way, without any plan. | random, careless",
    hegemony: "noun | Leadership or control by one country or group over others. | dominance, control",
    idyllic: "adjective | Extremely peaceful, happy and beautiful. | perfect, peaceful",
    ineffable: "adjective | Too great or beautiful to be put into words. | indescribable, inexpressible",
    insouciant: "adjective | Showing a casual lack of worry or concern. | carefree, nonchalant",
    irascible: "adjective | Easily made angry; bad-tempered. | irritable, short-tempered",
    lackadaisical: "adjective | Lacking energy, interest or care. | lazy, listless",
    malfeasance: "noun | Wrongdoing, especially by a person in a position of power. | misconduct, corruption",
    meticulous: "adjective | Showing great care and attention to detail. | careful, precise",
    nonchalant: "adjective | Calm and relaxed, showing no worry or interest. | casual, unconcerned",
    obsequious: "adjective | Too eager to please or obey someone important. | fawning, servile",
    ostentatious: "adjective | Designed to impress people or show off wealth. | showy, flashy",
    perfunctory: "adjective | Done quickly and without real interest or care. | careless, hasty",
    pusillanimous: "adjective | Lacking courage; timid and easily frightened. | cowardly, timid",
    quintessential: "adjective | Being the most perfect or typical example of something. | ultimate, classic",
    rendezvous: "noun / verb | A planned meeting at an agreed time and place; or to meet there. | meeting, appointment",
    schism: "noun | A split between people who once agreed or belonged together. | division, rift",
    serendipity: "noun | The luck of finding good things by chance. | luck, fortune",
    soliloquy: "noun | A speech in a play in which a character speaks their thoughts aloud, alone. | monologue, speech",
    sycophant: "noun | A person who flatters powerful people to gain an advantage. | flatterer, toady",
    ubiquitous: "adjective | Seeming to be present everywhere at the same time. | everywhere, universal",
  };

  function parse(row) {
    const [pos, definition, related] = row.split("|").map((p) => p.trim());
    return { pos, definition, related: related ? related.split(",").map((r) => r.trim()).filter(Boolean) : [] };
  }

  // Rows that did not come from this file (AI-generated words) are untrusted, so they are checked.
  function fromRow(word, row) {
    if (typeof row !== "string" || row.length > 600) return null;
    const parts = row.split("|").map((p) => p.trim());
    if (parts.length < 2 || parts.length > 3) return null;
    const [pos, definition, related = ""] = parts;
    if (!/^[a-z][a-z /]{1,38}$/i.test(pos)) return null;
    if (definition.length < 12 || definition.length > 300 || /[{}]/.test(definition)) return null;
    if (new RegExp(`\\b${String(word).toLowerCase()}\\b`, "i").test(definition)) return null; // would give the answer away
    const list = related.split(",").map((r) => r.trim()).filter(Boolean);
    if (list.length > 4 || list.some((r) => !/^[a-z][a-z' -]{0,38}$/i.test(r))) return null;
    return { pos, definition, related: list };
  }

  const cache = new Map();

  // Look up by the spelling on screen, which may be the British variant of the base word.
  function get(spelled) {
    if (!spelled) return null;
    const key = String(spelled).toLowerCase();
    if (cache.has(key)) return cache.get(key);
    const list = typeof WORD_LIST !== "undefined" ? WORD_LIST : [];
    const base = list.find((w) => w.word === key || (w.variants && Object.values(w.variants).includes(key)));
    const row = ROWS[base ? base.word : key];
    const meaning = row ? parse(row) : null;
    cache.set(key, meaning);
    return meaning;
  }

  // The built-in, hand-checked meaning wins; a word's own AI-written row is the fallback.
  function forEntry(entry) {
    if (!entry) return null;
    return get(entry.word) || fromRow(entry.word, entry.meaning);
  }

  window.SpellMeanings = { get, fromRow, forEntry, rows: ROWS };
})();
