// World words — hand-written rows, one list per theme (at most 100 words each).
// Loaded on demand by packs.js; see the notes at the top of packs.js for the row format.
SpellPacks.register("world", {
  "german": [
      { w: "schadenfreude", o: "German · Schadenfreude", lang: "de", pos: "noun", def: "Pleasure felt at someone else's bad luck.", rel: "malice, gloating",
        say: "scha-den-freu-de | SHAH-den-froy-duh | /ˈʃɑːdənˌfrɔɪdə/ | sch says “sh”; eu says “oy”.",
        ex: ["He felt a flash of {word} when his rival missed the bus.", "{word} is the guilty pleasure of watching someone else fail.", "German is the only language with such a tidy word for {word}."] },
      { w: "wanderlust", o: "German · Wanderlust", pos: "noun", def: "A strong urge to travel and see the world.", rel: "travel, adventure",
        say: "wan-der-lust | WON-der-lust | /ˈwɑːndɚˌlʌst/ | Said the English way, not the German “VAHN-der-loost”.",
        ex: ["Her {word} took her to forty countries.", "A map on the wall fed his {word}.", "Spring always brings out my {word}."] },
      { w: "zeitgeist", o: "German · Zeitgeist", pos: "noun", def: "The mood and ideas that define a particular time in history.", rel: "spirit, climate",
        say: "zeit-geist | ZYTE-gyste | /ˈzaɪtɡaɪst/ | Both ei letters say “eye”.",
        ex: ["The film captured the {word} of the 1960s.", "Social media has changed the {word} of our age.", "Great writers often sense the {word} before anyone else."] },
      { w: "doppelganger", o: "German · Doppelgänger", pos: "noun", def: "A person who looks exactly like someone else.", rel: "double, lookalike",
        say: "dop-pel-gang-er | DOP-ul-gang-ur | /ˈdɑːpəlˌɡæŋɚ/ | In German the ä has two dots; here it is a plain a.",
        ex: ["People kept mistaking me for my {word}.", "She met her {word} in a cafe in Lisbon.", "The story is about a man who finds his {word}."] },
      { w: "kindergarten", o: "German · Kindergarten", pos: "noun", def: "A school or class for young children before they start formal lessons.", rel: "nursery, preschool",
        say: "kin-der-gar-ten | KIN-dur-gar-tun | /ˈkɪndɚˌɡɑːrtn/ | In German it means “children's garden”.",
        ex: ["My little brother starts {word} in September.", "The {word} teacher read us a story.", "We painted pictures in {word}."] },
      { w: "angst", o: "German · Angst", pos: "noun", def: "A deep, restless worry about life or the future.", rel: "anxiety, dread",
        say: "angst | ANGKST | /ɑːŋkst/ | The ng is one sound, as in “sing”.",
        ex: ["Teenage {word} fills the pages of her diary.", "He felt a wave of {word} before the exam.", "The song is full of {word} and longing."] },
  ],
  "japanese": [
      { w: "ikigai", o: "Japanese · 生きがい", pos: "noun", def: "A reason to get up in the morning; what makes life feel worth living.", rel: "purpose, passion",
        say: "i-ki-gai | ee-kee-GUY | /ˌiːkiˈɡaɪ/ | ai says “eye”.",
        ex: ["Gardening is her {word}.", "He searched for his {word} for years.", "Your {word} sits where what you love meets what you do well."] },
      { w: "kintsugi", o: "Japanese · 金継ぎ", pos: "noun", def: "The art of mending broken pottery with gold, so the cracks become part of its beauty.", rel: "repair, mending",
        say: "kin-tsu-gi | kin-TSOO-gee | /kɪnˈtsuːɡi/ | The ts is one quick sound.",
        ex: ["The cracked bowl was repaired with {word}.", "{word} treats a break as part of an object's story.", "She uses {word} as a way to think about mistakes."] },
      { w: "wabisabi", o: "Japanese · 侘寂 (wabi-sabi)", pos: "noun", def: "Finding beauty in things that are imperfect, simple and passing.", rel: "imperfection, simplicity",
        say: "wa-bi-sa-bi | wah-bee-SAH-bee | /ˌwɑːbiˈsɑːbi/ | Usually written with a hyphen: wabi-sabi.",
        ex: ["The chipped teacup was full of {word}.", "A weathered wooden gate shows {word}.", "{word} teaches us to enjoy what is plain and worn."] },
      { w: "tsunami", o: "Japanese · 津波, “harbour wave”", pos: "noun", def: "A huge sea wave caused by an earthquake or volcano under the water.", rel: "wave, flood",
        say: "tsu-na-mi | tsoo-NAH-mee | /tsuːˈnɑːmi/ | Japanese says the t; English often leaves it silent.",
        ex: ["A {word} warning sent everyone to higher ground.", "The {word} reached the coast within an hour.", "Scientists study how a {word} travels across an ocean."] },
      { w: "origami", o: "Japanese · 折り紙, “folded paper”", pos: "noun", def: "The art of folding paper into shapes such as birds and flowers.", rel: "paper folding, craft",
        say: "o-ri-ga-mi | or-ih-GAH-mee | /ˌɔːrɪˈɡɑːmi/ | The g is hard, as in “game”.",
        ex: ["She folded a paper crane for her {word} class.", "{word} needs patience and neat creases.", "He made a tiny frog using {word}."] },
  ],
  "indian": [
      { w: "karma", o: "Sanskrit · karma", pos: "noun", def: "The belief that what you do comes back to you, for good or bad.", rel: "fate, destiny",
        say: "kar-ma | KAR-muh | /ˈkɑːrmə/ | The final a is a soft “uh”.",
        ex: ["Helping others is good {word}.", "He believed his bad luck was {word}.", "The word {word} comes from the Sanskrit for “action”."] },
      { w: "dharma", o: "Sanskrit · dharma", pos: "noun", def: "In Indian traditions, a person's duty and the right way to live.", rel: "duty, righteousness",
        say: "dhar-ma | DAR-muh | /ˈdɑːrmə/ | The h after d is not heard separately.",
        ex: ["She saw teaching as her {word}.", "Following your {word} means doing what is right.", "The story asks what a prince's {word} should be."] },
      { w: "namaste", o: "Sanskrit and Hindi · नमस्ते", pos: "noun", def: "A respectful greeting made with the palms pressed together.", rel: "greeting, salutation",
        say: "na-mas-te | NUH-muh-stay | /ˈnʌməsteɪ/ | The final e says “ay”.",
        ex: ["She bowed slightly and said {word}.", "The teacher greeted the class with a warm {word}.", "{word} is both hello and goodbye in Hindi."] },
      { w: "jugaad", o: "Hindi · जुगाड़", pos: "noun", def: "A clever, low-cost fix made with whatever is at hand.", rel: "improvisation, makeshift",
        say: "ju-gaad | joo-GAHD | /dʒʊˈɡɑːd/ | The double a makes one long vowel.",
        ex: ["Fixing the cart with a bicycle chain was pure {word}.", "Indian engineers are famous for their {word}.", "Her {word} kept the old radio working for years."] },
      { w: "bungalow", o: "Hindi · बंगला (bangla), “of Bengal”", pos: "noun", def: "A house that has only one floor.", rel: "cottage, house",
        say: "bun-ga-low | BUNG-guh-loh | /ˈbʌŋɡəloʊ/ | The ng is followed by a hard g.",
        ex: ["They retired to a small {word} by the sea.", "A {word} has no stairs to climb.", "The word {word} began in Bengal."] },
      { w: "jungle", o: "Hindi · जंगल (jangal), “wild, uncultivated land”", pos: "noun", def: "A thick, hot forest where many plants and animals live.", rel: "rainforest, wilderness",
        say: "jun-gle | JUNG-gul | /ˈdʒʌŋɡəl/ | The g in the middle is hard.",
        ex: ["We hiked through the {word} for three days.", "The {word} was loud with birds at dawn.", "Rain fell steadily on the green {word}."] },
  ],
  "nordic": [
      { w: "hygge", o: "Danish · hygge", lang: "da", pos: "noun", def: "A warm, cosy feeling of comfort and togetherness.", rel: "cosiness, contentment",
        say: "hyg-ge | HOO-guh | /ˈhʊɡə/ | The y sounds like “oo”, and gg is a hard g.",
        ex: ["Candles and blankets are the heart of {word}.", "We spent a snowy evening in pure {word}.", "Denmark gave the world the idea of {word}."] },
      { w: "fika", o: "Swedish · fika", lang: "sv", pos: "noun", def: "A break to enjoy coffee and a sweet treat with other people.", rel: "coffee break, pause",
        say: "fi-ka | FEE-kuh | /ˈfiːka/ | The i says “ee”.",
        ex: ["Every afternoon the team stops for {word}.", "Let's meet for {word} at three.", "A cinnamon bun is the classic partner for {word}."] },
      { w: "sisu", o: "Finnish · sisu", lang: "fi", pos: "noun", def: "Stubborn courage that keeps you going when things are very hard.", rel: "grit, resolve, determination",
        say: "si-su | SEE-soo | /ˈsisu/ | Both s letters are a plain “s”.",
        ex: ["It took real {word} to finish the marathon.", "Finns describe their toughness as {word}.", "She showed great {word} after the injury."] },
  ],
  "romance": [
      { w: "saudade", o: "Portuguese · Saudade", lang: "pt", pos: "noun", def: "A deep, wistful longing for someone or something you love that is far away.", rel: "longing, nostalgia",
        say: "sau-da-de | sow-DAH-duh | /saʊˈdɑːdə/ | au says “ow”, as in “cow”.",
        ex: ["The old fado song is full of {word}.", "She felt {word} for the village she grew up in.", "Portuguese speakers say {word} has no exact English match."] },
      { w: "sobremesa", o: "Spanish · sobremesa, “over the table”", lang: "es", pos: "noun", def: "The relaxed time spent chatting at the table after a meal is finished.", rel: "chat, lingering",
        say: "so-bre-me-sa | soh-bray-MAY-sah | /soβɾeˈmesa/ | Each vowel is pure and short.",
        ex: ["The long {word} lasted until the sun went down.", "In Spain, {word} is as important as the meal itself.", "We stayed for {word} and talked for hours."] },
      { w: "ennui", o: "French · ennui", pos: "noun", def: "A feeling of being tired, bored and unsatisfied.", rel: "boredom, weariness",
        say: "en-nui | ahn-WEE | /ɑːnˈwiː/ | The en is a nasal sound, and ui says “wee”.",
        ex: ["A long, grey winter filled him with {word}.", "The novel's hero is lost in {word}.", "She tried to shake off her {word} with a long walk."] },
      { w: "quarantine", o: "Italian · quaranta giorni, “forty days”", pos: "noun", def: "A period of staying apart to stop an illness from spreading.", rel: "isolation, separation",
        say: "quar-an-tine | KWOR-un-teen | /ˈkwɔːrəntiːn/ | The qu says “kw”.",
        ex: ["Ships once waited forty days in {word}.", "The traveller spent a week in {word}.", "The word {word} comes from the Italian for forty."] },
  ],
  "world": [
      { w: "ubuntu", o: "Zulu and Xhosa · ubuntu", pos: "noun", def: "The idea that a person is a person through other people: “I am because we are”.", rel: "humanity, community",
        say: "u-bun-tu | oo-BOON-too | /ʊˈbʊntuː/ | The u at the start says “oo”.",
        ex: ["The village lives by the spirit of {word}.", "{word} reminds us that we belong to one another.", "She spoke about {word} in her speech on kindness."] },
      { w: "safari", o: "Swahili · safari, from Arabic for “journey”", pos: "noun", def: "A trip to watch wild animals, especially in Africa.", rel: "expedition, trek",
        say: "sa-fa-ri | suh-FAR-ee | /səˈfɑːri/ | The first a is a soft “uh”.",
        ex: ["We saw lions on our {word}.", "The {word} began before sunrise.", "A jeep is the usual way to go on {word}."] },
      { w: "algorithm", o: "From the name of the Persian scholar al-Khwarizmi", pos: "noun", def: "A set of step-by-step rules for solving a problem.", rel: "procedure, formula",
        say: "al-go-rithm | AL-guh-rithum | /ˈælɡəˌrɪðəm/ | The ending is spelled -rithm but said “rith-um”.",
        ex: ["The app uses an {word} to suggest songs.", "She wrote an {word} for sorting the names.", "Every recipe is a kind of {word}."] },
      { w: "meraki", o: "Greek · μεράκι", pos: "noun", def: "Doing something with complete care, creativity and love.", rel: "passion, devotion",
        say: "me-ra-ki | meh-rah-KEE | /mɛˈrɑːki/ | Stress the last syllable.",
        ex: ["The chef cooked every dish with {word}.", "You could see her {word} in each stitch.", "Work done with {word} carries a little of the maker."] },
      { w: "mamihlapinatapai", o: "Yaghan (Tierra del Fuego) · often cited as one of the hardest words to translate", pos: "noun", def: "A shared look between two people, each hoping the other will begin something neither wants to start.", syl: "ma-mih-la-pi-na-ta-pai",
        say: "",
        ex: ["The word {word} describes a silent, hopeful look.", "Linguists love to quote {word} as a word with no short translation.", "Spelling {word} is a good test of patience."] },
      { w: "barbecue", o: "Taíno (Caribbean) · barbacoa, through Spanish", pos: "noun", def: "A meal cooked over an open fire, or the grill used to cook it.", rel: "grill, cookout",
        say: "bar-be-cue | BAR-buh-kyoo | /ˈbɑːrbɪkjuː/ | The ending -cue says “kyoo”.",
        ex: ["We held a {word} in the garden.", "Dad lit the {word} before the guests arrived.", "The smell of a {word} drifted across the street."] },
  ],
});
