// Names & places — hand-written rows, one list per theme (at most 100 words each).
// Loaded on demand by packs.js; see the notes at the top of packs.js for the row format.
SpellPacks.register("names", {
  "british-places": [
      { w: "worcester", o: "Place in England", pos: "place name", def: "A city in western England whose name has only two syllables when spoken.",
        say: "wor-cester | WUS-ter | /ˈwʊstər/ | Spelled with three parts but said with two.",
        ex: ["We took the train to {word} for the cricket.", "The sauce takes its name from {word}.", "Nobody says {word} the way it is spelled."] },
      { w: "gloucester", o: "Place in England", pos: "place name", def: "A cathedral city in western England, said as if it were spelled with fewer letters.",
        say: "glou-cester | GLOS-ter | /ˈɡlɒstər/ | The ou and ce are not sounded separately.",
        ex: ["The cathedral in {word} is hundreds of years old.", "They moved to {word} last spring.", "Tourists often get {word} wrong when they say it aloud."] },
      { w: "leicester", o: "Place in England", pos: "place name", def: "A city in the middle of England, said with a short first syllable.",
        say: "lei-cester | LES-ter | /ˈlɛstər/ | The ei says “e” and the c is silent.",
        ex: ["The football club from {word} won the league.", "We drove through {word} on the way north.", "A visitor might spell {word} with an extra letter."] },
      { w: "edinburgh", o: "City in Scotland", pos: "place name", def: "The capital city of Scotland.",
        say: "ed-in-burgh | ED-in-bruh | /ˈɛdɪnbərə/ | The ending -burgh is said “bruh”.",
        ex: ["Every August {word} fills with festival crowds.", "The castle in {word} stands on an old volcano.", "She studied history in {word}."] },
      { w: "greenwich", o: "Place in London", pos: "place name", def: "A district of London that gives its name to the world's time standard.",
        say: "green-wich | GREN-itch | /ˈɡrɛnɪtʃ/ | The w is silent.",
        ex: ["Time around the world is measured from {word}.", "We took a boat down the river to {word}.", "The ending of {word} is not said “wich”."] },
      { w: "marylebone", o: "District of London", pos: "place name", def: "A district in central London with a famous railway station.",
        say: "mar-y-le-bone | MAR-ee-luh-bun | /ˈmærɪləbən/ | The last part is “bun”, not “bone”.",
        ex: ["Our train leaves from {word} station.", "The cricket club named after {word} is world famous.", "Say {word} slowly and it starts to make sense."] },
      { w: "bicester", o: "Town in England", pos: "place name", def: "A market town near Oxford, said with a short, quick ending.",
        say: "bi-cester | BIS-ter | /ˈbɪstər/ | The middle ce is not sounded as its own part.",
        ex: ["Shoppers travel to {word} for the village outlet.", "Our bus stops in {word} before Oxford.", "He grew up near {word}."] },
      { w: "leominster", o: "Town in England", pos: "place name", def: "A market town in Herefordshire that is said as “Lemster”.",
        say: "leo-minster | LEM-ster | /ˈlɛmstər/ | The leo says “lem”.",
        ex: ["The priory in {word} is very old.", "Her aunt lives in {word}.", "Visitors often say {word} with three syllables."] },
      { w: "magdalen", o: "Oxford college", pos: "place name", def: "A college of Oxford University whose name is said “Maudlin”.",
        say: "mag-dalen | MAWD-lin | /ˈmɔːdlɪn/ | The g and a are not sounded as in the spelling.",
        ex: ["He studied physics at {word}.", "Deer graze in the park beside {word}.", "Say {word} aloud and it sounds like a different word."] },
  ],
  "british-surnames": [
      { w: "cholmondeley", o: "English surname and place", pos: "surname", def: "An English family name that is said like “Chumley”.",
        say: "cholmon-deley | CHUM-lee | /ˈtʃʌmli/ | Twelve letters but only two syllables.",
        ex: ["Lord {word} welcomed the guests to the hall.", "The teacher asked how to say {word}.", "Spelling {word} is harder than saying it."] },
      { w: "featherstonehaugh", o: "English surname", pos: "surname", def: "A very long English family name, usually said like “Fanshaw”.",
        say: "feather-stonehaugh | FAN-shaw | /ˈfænʃɔː/ | Also said FEATH-er-stun-haw by some families.",
        ex: ["Mr {word} spelled his name out twice.", "The name {word} is famous for how it sounds.", "She wrote {word} carefully on the form."] },
      { w: "beauchamp", o: "English surname", pos: "surname", def: "An English family name that is said like “Beecham”.",
        say: "beau-champ | BEE-chum | /ˈbiːtʃəm/ | The beau says “bee” and the p is silent.",
        ex: ["Lady {word} opened the garden to visitors.", "The family name {word} came over from France.", "He corrected everyone who said {word} the French way."] },
      { w: "menzies", o: "Scottish surname", pos: "surname", def: "A Scottish family name that is said as “Mingis”.",
        say: "men-zies | MING-iss | /ˈmɪŋɪs/ | The nz is said as “ng”.",
        ex: ["The clan {word} has a castle in Perthshire.", "Mr {word} spelled it for us twice.", "Few people say {word} correctly the first time."] },
  ],
  "irish": [
      { w: "siobhan", o: "Irish first name · Siobhán", pos: "first name", def: "A traditional Irish girl's name, said with a “sh” sound at the start.",
        say: "sio-bhan | shi-VAWN | /ʃɪˈvɔːn/ | In Irish, sio says “shi” and bh says “v”.",
        ex: ["{word} is a popular girl's name in Ireland.", "My friend {word} always spells it out for new teachers.", "Nobody guesses how to say {word} on the first try."] },
      { w: "saoirse", o: "Irish first name", pos: "first name", def: "An Irish name that means “freedom”.",
        say: "saoir-se | SUR-shuh | /ˈsɜːrʃə/ | Some say it SEER-shuh; both are used.",
        ex: ["{word} means freedom in Irish.", "The actress {word} has spelled her name for many interviewers.", "She named her daughter {word}."] },
      { w: "niamh", o: "Irish first name", pos: "first name", def: "An Irish name from a legend of a golden-haired princess.",
        say: "niamh | NEEV | /niːv/ | The mh at the end says “v”.",
        ex: ["{word} looked up from her book.", "Her name, {word}, surprises people who see it written.", "In the old tale, {word} rode a white horse over the sea."] },
      { w: "aoife", o: "Irish first name", pos: "first name", def: "An Irish name made of five letters that is said with just two sounds.",
        say: "ao-ife | EE-fuh | /ˈiːfə/ | The ao says “ee”.",
        ex: ["{word} won the school spelling prize.", "Most teachers have to ask how to say {word}.", "The name {word} appears in Irish legends."] },
  ],
  "indian-names": [
      { w: "aishwarya", o: "Indian first name (Sanskrit) · ऐश्वर्या", pos: "first name", def: "An Indian name that means wealth, prosperity or divine power.",
        say: "aish-war-ya | eye-SHWAR-yuh | /aɪʃˈwɑːrjə/ | The ai says “eye” and the ya is a quick “yuh”.",
        ex: ["{word} carefully wrote her name on the form.", "The name {word} is often spelled in more than one way.", "Our new classmate {word} comes from Chennai."] },
      { w: "lakshmi", o: "Indian first name (Sanskrit) · लक्ष्मी", pos: "first name", def: "An Indian name; also the name of the goddess of wealth and good fortune.",
        say: "laksh-mi | LUK-shmee | /ˈlʌkʃmi/ | The ksh is said “ksh” in one breath.",
        ex: ["{word} lit a lamp for Diwali.", "Many families name a daughter {word}.", "The letters ksh in {word} can be tricky to remember."] },
      { w: "siddhartha", o: "Indian name (Sanskrit) · सिद्धार्थ", pos: "first name", def: "An Indian name, also that of the prince who became the Buddha.",
        say: "sid-dhar-tha | sid-DAR-tuh | /sɪˈdɑːrtə/ | The dh and th are softer than they look.",
        ex: ["{word} left the palace to search for truth.", "A famous novel is named after {word}.", "My cousin {word} is learning to code."] },
      { w: "ananya", o: "Indian first name (Sanskrit) · अनन्या", pos: "first name", def: "An Indian name that means unique, with no equal.",
        say: "a-nan-ya | uh-NUN-yuh | /əˈnʌnjə/ | Stress the middle part.",
        ex: ["{word} gave the best talk in the class.", "Her parents chose {word} because it means “one of a kind”.", "I always double-check how to spell {word}."] },
      { w: "priyanka", o: "Indian first name (Sanskrit) · प्रियंका", pos: "first name", def: "A popular Indian name that means dear or beloved.",
        say: "pri-yan-ka | pree-YUNG-kuh | /priˈjɑːŋkə/ | The yan is said “yung”.",
        ex: ["{word} waved from across the courtyard.", "The name {word} is common across India.", "She taught us how to say {word} properly."] },
  ],
  "indian-places": [
      { w: "bengaluru", o: "City in India · ಬೆಂಗಳೂರು", pos: "place name", def: "A large city in southern India, once spelled Bangalore.",
        say: "ben-ga-lu-ru | ben-guh-LOO-roo | /ˈbɛŋɡəluːru/ | The ng is followed by a hard g.",
        ex: ["Many software companies have offices in {word}.", "{word} is known for its mild weather.", "The city's name was changed to {word} in 2014."] },
      { w: "mumbai", o: "City in India", pos: "place name", def: "A large port city on the west coast of India, once called Bombay.",
        say: "mum-bai | mum-BYE | /mʌmˈbaɪ/ | The ai says “eye”.",
        ex: ["Films from {word} are watched around the world.", "The train to {word} leaves at noon.", "She grew up beside the sea in {word}."] },
      { w: "chennai", o: "City in India · சென்னை", pos: "place name", def: "A large city on the south-east coast of India, once called Madras.",
        say: "chen-nai | CHEN-eye | /ˈtʃɛnaɪ/ | The double n and ai make “nye”.",
        ex: ["The beach in {word} is long and wide.", "He flew from Delhi to {word}.", "Filter coffee is a favourite drink in {word}."] },
      { w: "kolkata", o: "City in India · কলকাতা", pos: "place name", def: "A large city in eastern India, once spelled Calcutta.",
        say: "kol-ka-ta | kol-KAH-tuh | /kɒlˈkɑːtə/ | Stress the middle part.",
        ex: ["The trams of {word} are over a century old.", "Writers and artists have long lived in {word}.", "We visited a bookshop street in {word}."] },
      { w: "varanasi", o: "City in India · वाराणसी", pos: "place name", def: "An ancient holy city on the banks of the river Ganges.",
        say: "va-ra-na-si | vuh-RAH-nuh-see | /vəˈrɑːnəsi/ | Four syllables, with the stress on the second.",
        ex: ["Pilgrims bathe in the river at {word}.", "{word} is one of the oldest cities in the world.", "Sunrise over the water in {word} is unforgettable."] },
      { w: "rajasthan", o: "State in India · राजस्थान", pos: "place name", def: "A large state in north-western India, known for forts and the Thar desert.",
        say: "ra-jas-than | RAH-juh-stahn | /ˈrɑːdʒəstɑːn/ | The j says “j” as in “jam”.",
        ex: ["We rode camels in the desert of {word}.", "The palaces of {word} glow at sunset.", "Colourful turbans are a sight across {word}."] },
      { w: "thiruvananthapuram", o: "City in India · തിരുവനന്തപുരം", pos: "place name", def: "The capital city of the state of Kerala in southern India.",
        say: "thi-ru-va-nan-tha-pu-ram | tih-ru-vuh-NUN-tuh-puh-rum | /ˌtɪruvəˈnʌnθəˌpʊrəm/ | Seven short syllables; take it one at a time.",
        ex: ["The capital of Kerala is {word}.", "It took her a week to learn to spell {word}.", "A long name like {word} is easier in small parts."] },
      { w: "vijayawada", o: "City in India · విజయవాడ", pos: "place name", def: "A busy city in the south-east of India beside the river Krishna.",
        say: "vi-ja-ya-wa-da | vih-juh-yuh-WAH-duh | /ˌvɪdʒəjəˈwɑːdə/ | Five syllables, with the stress on the fourth.",
        ex: ["The bridge at {word} crosses a wide river.", "Trains from {word} run to every part of the south.", "We stopped for lunch in {word}."] },
  ],
});
