// Handwritten sentence prompts. {word} is replaced with one spelling mistake.
window.PROOFREAD_WORDS = [
  ["because", "I stayed indoors {word} it was raining.", "be-cause"],
  ["friend", "My best {word} lives next door.", "friend"],
  ["believe", "I {word} we can solve this puzzle.", "be-lieve"],
  ["separate", "Please {word} the red blocks from the blue ones.", "sep-a-rate"],
  ["definitely", "I will {word} bring my book tomorrow.", "def-i-nite-ly"],
  ["necessary", "A warm coat is {word} in cold weather.", "nec-es-sar-y"],
  ["receive", "You will {word} a letter in the post.", "re-ceive"],
  ["beautiful", "We saw a {word} rainbow after the storm.", "beau-ti-ful"],
  ["science", "In {word} class, we learned about magnets.", "sci-ence"],
  ["different", "Each butterfly has a {word} pattern.", "dif-fer-ent"],
  ["favorite", "Strawberry is my {word} ice cream flavour.", "fa-vor-ite"],
  ["environment", "Planting trees helps protect the {word}.", "en-vi-ron-ment"],
  ["restaurant", "We ate lunch at a small {word} near the park.", "res-tau-rant"],
  ["calendar", "I marked my birthday on the {word}.", "cal-en-dar"],
  ["vacuum", "We used a {word} to clean the carpet.", "vac-u-um"],
  ["rhythm", "The drummer kept a steady {word}.", ""],
  ["language", "She is learning a new {word} at school.", "lan-guage"],
  ["surprise", "The party was a wonderful {word}.", "sur-prise"],
  ["immediately", "Please wash your hands {word} after painting.", "im-me-di-ate-ly"],
  ["occasion", "We baked a cake for the special {word}.", "oc-ca-sion"],
  ["knowledge", "Reading books can increase your {word}.", "knowl-edge"],
  ["neighbor", "Our {word} kindly watered the plants.", "neigh-bor"],
  ["achieve", "With practice, you can {word} your goal.", "a-chieve"],
  ["business", "Her family runs a small {word} in town.", "busi-ness"],
  ["column", "Write your answer in the first {word}.", "col-umn"],
  ["grateful", "I am {word} for your help.", "grate-ful"],
  ["height", "We measured the {word} of the sunflower.", "height"],
  ["island", "The boat took us to a tiny {word}.", "is-land"],
  ["library", "I borrowed three books from the {word}.", "li-brar-y"],
  ["opposite", "The shop is on the {word} side of the road.", "op-po-site"],
  ["possible", "Is it {word} to finish before lunch?", "pos-si-ble"],
  ["question", "Raise your hand if you have a {word}.", "ques-tion"],
  ["tomorrow", "We are going to the beach {word}.", "to-mor-row"],
  ["umbrella", "Take an {word} in case it rains.", "um-brel-la"],
  ["cat", "The {word} curled up beside the warm fire.", "cat"],
  ["dog", "Our {word} loves to fetch a ball.", "dog"],
  ["apple", "I packed an {word} in my lunch box.", "ap-ple"],
  ["happy", "Winning the game made her feel {word}.", "hap-py"],
  ["water", "Remember to drink plenty of {word}.", "wa-ter"],
  ["chair", "Please pull up a {word} and join us.", "chair"],
].map(([word, sentence, syllables]) => ({ ...WORD_LIST.find(w => w.word === word), word, sentence, syllables }));

// Curated errors avoid accidentally offering another correctly spelt word,
// such as "cut" for "cat", in a task about finding misspellings.
window.PROOFREAD_MISTAKES = {
  because: "becuase", friend: "freind", believe: "beleive", separate: "seperate",
  definitely: "definately", necessary: "neccessary", receive: "recieve", beautiful: "beautifull",
  science: "scince", different: "diffrent", favorite: "favroite", favourite: "favrouite",
  environment: "enviroment", restaurant: "restarant", calendar: "calender", vacuum: "vaccuum",
  rhythm: "rythm", language: "langauge", surprise: "suprise", immediately: "immediatly",
  occasion: "ocassion", knowledge: "knowlege", neighbor: "nieghbor", neighbour: "nieghbour",
  achieve: "acheive", business: "buisness", column: "colum", grateful: "greatful",
  height: "hieght", island: "islnad", library: "libary", opposite: "oposite",
  possible: "possable", question: "qustion", tomorrow: "tommorow", umbrella: "umbrellla",
  cat: "catt", dog: "dogg", apple: "appple", happy: "hapy", water: "watter", chair: "chiar",
};
