// Sound guide for the pronounce coach: real syllables, a plain-English respelling,
// IPA and (where the spelling hides the sound) a short note, for every built-in word.
//
// Row format:  "written-syl-la-bles | RES-pel-ling | /ipa/ | optional note"
//  - The respelling has one part per written syllable; the STRESSED part is UPPERCASE
//    (single-syllable words are all caps). Parts are spoken aloud by the coach, so they
//    use ordinary English letters (ay, ee, eye, oh, oo, ow, aw, uh, ur, air) that a
//    text-to-speech voice reads correctly, unlike a chunk of the real spelling like "ly".
//  - Pronunciation is General American. Keyed by the US spelling; British variants
//    (colour, favourite...) are resolved through WORD_LIST.variants.
(() => {
  "use strict";

  const ROWS = {
    // ---------- beginner ----------
    cat: "cat | KAT | /kæt/",
    dog: "dog | DAWG | /dɔɡ/",
    sun: "sun | SUN | /sʌn/",
    run: "run | RUN | /rʌn/",
    jump: "jump | JUMP | /dʒʌmp/",
    frog: "frog | FRAWG | /frɔɡ/",
    milk: "milk | MILK | /mɪlk/",
    book: "book | BOOK | /bʊk/ | The double o is short here, like in “look”.",
    happy: "hap-py | HAP-ee | /ˈhæp.i/ | The final y says /ee/.",
    apple: "ap-ple | AP-ul | /ˈæp.əl/ | The ending -le sounds like “ul”.",
    house: "house | HOWS | /haʊs/ | “ou” says /ow/; the final e is silent.",
    water: "wa-ter | WAW-tur | /ˈwɔ.tɚ/ | “a” says /aw/ after w.",
    green: "green | GREEN | /ɡrin/",
    smile: "smile | SMYLE | /smaɪl/ | The final e is silent and makes the i say its name.",
    chair: "chair | CHAIR | /tʃɛr/ | “air” says /air/.",

    // ---------- everyday ----------
    because: "be-cause | bih-KAWZ | /bɪˈkɔz/ | “au” says /aw/ and the ending -se sounds like Z.",
    friend: "friend | FREND | /frɛnd/ | “ie” says a short /e/ here; you don't hear the i.",
    believe: "be-lieve | bih-LEEV | /bɪˈliv/ | “ie” says /ee/; the final e is silent.",
    separate: "sep-a-rate | SEP-uh-rit | /ˈsɛp.ə.rɪt/ | The middle a is a weak “uh”, which is why it is easy to write “seperate”.",
    definitely: "def-i-nite-ly | DEF-uh-nit-lee | /ˈdɛf.ə.nɪt.li/ | The ending sounds like “it”, so the final “ite” is easy to misspell.",
    necessary: "nec-es-sar-y | NES-uh-ser-ee | /ˈnɛs.ə.sɛr.i/ | The /s/ sounds are spelled c, ss: one c, two s.",
    receive: "re-ceive | rih-SEEV | /rɪˈsiv/ | “ei” says /ee/ after c.",
    though: "though | THOH | /ðoʊ/ | “ough” says /oh/; the gh is silent.",
    beautiful: "beau-ti-ful | BYOO-tuh-ful | /ˈbju.tə.fəl/ | “eau” says /yoo/.",
    science: "sci-ence | SY-uns | /ˈsaɪ.əns/ | “sc” sounds like /s/.",
    people: "peo-ple | PEE-pul | /ˈpi.pəl/ | “eo” says /ee/.",
    different: "dif-fer-ent | DIF-ur-unt | /ˈdɪf.ɚ.ənt/ | Double f, then “er” and “ent” are weak.",
    favorite: "fa-vor-ite | FAY-vur-it | /ˈfeɪ.vɚ.ɪt/ | The ending -ite says “it”.",
    weird: "weird | WEERD | /wɪrd/ | “ei” says /ee/: an exception to “i before e”.",
    environment: "en-vi-ron-ment | en-VY-run-munt | /ɪnˈvaɪ.rən.mənt/ | Say the n before the m: envi-RON-ment.",
    government: "gov-ern-ment | GUV-urn-munt | /ˈɡʌv.ɚn.mənt/ | “o” says /u/; the n in “govern” is pronounced.",
    restaurant: "res-tau-rant | RES-tuh-ront | /ˈrɛs.tə.rɑnt/ | The middle “au” is weak: it sounds like “tuh”.",
    calendar: "cal-en-dar | KAL-un-dur | /ˈkæl.ən.dɚ/ | The ending -ar sounds like “er”.",
    vacuum: "vac-u-um | VAK-yoo-um | /ˈvæk.ju.əm/ | Two u's in a row, both pronounced.",
    rhythm: "rhy-thm | RITH-um | /ˈrɪð.əm/ | “rh” is just /r/, and the second syllable has no vowel letter.",
    language: "lan-guage | LANG-gwij | /ˈlæŋ.ɡwɪdʒ/ | “gu” says /gw/ and “age” says /ij/.",
    surprise: "sur-prise | sur-PRYZ | /sɚˈpraɪz/ | Two r's: sur-prise. The first r is easy to drop.",
    immediately: "im-me-di-ate-ly | ih-MEE-dee-it-lee | /ɪˈmi.di.ɪt.li/ | Double m; “ate” sounds like “it”.",
    occasion: "oc-ca-sion | uh-KAY-zhun | /əˈkeɪ.ʒən/ | “sion” says /zhun/. Double c, single s.",
    embarrass: "em-bar-rass | im-BAIR-us | /ɪmˈbɛr.əs/ | Two r's and two s's.",
    knowledge: "knowl-edge | NOL-ij | /ˈnɑl.ɪdʒ/ | The k is silent; “dge” says /j/.",
    guarantee: "guar-an-tee | gair-un-TEE | /ˌɡɛr.ənˈti/ | “gu” says /g/: the u is silent.",
    mischievous: "mis-chie-vous | MIS-chuh-vus | /ˈmɪs.tʃə.vəs/ | Three syllables, not four: there is no “i” sound before -ous.",
    neighbor: "neigh-bor | NAY-bur | /ˈneɪ.bɚ/ | “eigh” says /ay/; the gh is silent.",
    achieve: "a-chieve | uh-CHEEV | /əˈtʃiv/ | “ie” says /ee/.",
    although: "al-though | awl-THOH | /ɔlˈðoʊ/ | “ough” says /oh/.",
    business: "busi-ness | BIZ-nis | /ˈbɪz.nɪs/ | The u and the i are not both heard: it sounds like “biz-nis”.",
    column: "col-umn | KOL-um | /ˈkɑl.əm/ | The n at the end is silent.",
    foreign: "for-eign | FOR-in | /ˈfɔr.ɪn/ | “eign” says /in/; the g is silent.",
    grateful: "grate-ful | GRAYT-ful | /ˈɡreɪt.fəl/ | The ending is -ful with one l.",
    height: "height | HYTE | /haɪt/ | “eigh” says /eye/ and the word ends in t, not th.",
    island: "is-land | EYE-lund | /ˈaɪ.lənd/ | The s is silent.",
    jewelry: "jew-el-ry | JOO-ul-ree | /ˈdʒu.əl.ri/ | Three syllables: jew-el-ry.",
    library: "li-brar-y | LY-brair-ee | /ˈlaɪ.brɛr.i/ | Say the first r: li-BRAR-y, not “lie-berry”.",
    medicine: "med-i-cine | MED-uh-sin | /ˈmɛd.ə.sɪn/ | “c” says /s/.",
    opposite: "op-po-site | OP-uh-zit | /ˈɑp.ə.zɪt/ | “site” says /zit/. Double p.",
    possible: "pos-si-ble | POS-uh-bul | /ˈpɑs.ə.bəl/ | Double s; the ending -ble sounds like “bul”.",
    question: "ques-tion | KWES-chun | /ˈkwɛs.tʃən/ | “qu” says /kw/; “tion” says /chun/ after s.",
    rhyme: "rhyme | RYME | /raɪm/ | “rh” is just /r/.",
    schedule: "sched-ule | SKEJ-ool | /ˈskɛdʒ.ul/ | “sch” says /sk/ in American English and the d sounds like /j/.",
    tomorrow: "to-mor-row | tuh-MOR-oh | /təˈmɔr.oʊ/ | One m, two r's.",
    umbrella: "um-brel-la | um-BREL-uh | /ʌmˈbrɛl.ə/ | Two l's at the end; the last syllable is a weak “uh”.",
    vegetable: "veg-e-ta-ble | VEJ-uh-tuh-bul | /ˈvɛdʒ.ə.tə.bəl/ | Often said in three syllables: VEJ-tuh-bul.",
    weather: "weath-er | WETH-ur | /ˈwɛð.ɚ/ | “ea” says a short /e/.",

    // ---------- expert ----------
    conscientious: "con-sci-en-tious | kon-shee-EN-shus | /ˌkɑn.ʃiˈɛn.ʃəs/ | “sc” says /sh/ and “tious” says /shus/.",
    onomatopoeia: "on-o-mat-o-poe-ia | on-uh-mat-uh-PEE-uh | /ˌɑn.əˌmæt.əˈpi.ə/ | “oeia” says /ee-uh/, and that is where the stress falls.",
    bureaucracy: "bu-reau-cra-cy | byoo-ROK-ruh-see | /bjʊˈrɑk.rə.si/ | “eau” says /o/ here.",
    questionnaire: "ques-tion-naire | kwes-chuh-NAIR | /ˌkwɛs.tʃəˈnɛr/ | Two n's: question + naire.",
    entrepreneur: "en-tre-pre-neur | on-truh-pruh-NUR | /ˌɑn.trə.prəˈnɝ/ | It starts with “on”, not “en”; “eur” says /ur/.",
    chrysanthemum: "chry-san-the-mum | krih-SAN-thuh-mum | /krɪˈsæn.θə.məm/ | “ch” says /k/ and the “th” is a real /th/.",
    idiosyncrasy: "id-i-o-syn-cra-sy | id-ee-oh-SING-kruh-see | /ˌɪd.i.oʊˈsɪŋ.krə.si/ | “syn” sounds like “sing”.",
    connoisseur: "con-nois-seur | kon-uh-SUR | /ˌkɑn.əˈsɝ/ | “oi” is weak and “eur” says /ur/.",
    camouflage: "cam-ou-flage | KAM-uh-flahzh | /ˈkæm.ə.flɑʒ/ | “age” says /ahzh/: it is a French word.",
    silhouette: "sil-hou-ette | sil-oo-ET | /ˌsɪl.uˈɛt/ | The h is silent.",
    rhinoceros: "rhi-noc-er-os | ry-NOS-ur-us | /raɪˈnɑs.ɚ.əs/ | “rh” is just /r/.",
    acquaintance: "ac-quaint-ance | uh-KWAYN-tuns | /əˈkweɪn.təns/ | “cq” sounds like /kw/.",
    millennium: "mil-len-ni-um | mih-LEN-ee-um | /mɪˈlɛn.i.əm/ | Two l's and two n's.",
    hierarchy: "hi-er-ar-chy | HY-uh-rar-kee | /ˈhaɪ.ɚˌɑr.ki/ | “ch” says /k/.",
    phenomenon: "phe-nom-e-non | fuh-NOM-uh-non | /fəˈnɑm.ə.nɑn/ | “ph” says /f/.",
    pneumonia: "pneu-mo-nia | noo-MOH-nyuh | /nuˈmoʊ.njə/ | The p is silent.",
    cappuccino: "cap-puc-ci-no | kap-uh-CHEE-noh | /ˌkæp.əˈtʃi.noʊ/ | “cc” before i says /ch/. Two p's, two c's.",
    kaleidoscope: "ka-lei-do-scope | kuh-LY-duh-skohp | /kəˈlaɪ.də.skoʊp/ | “ei” says /eye/ here.",

    // ---------- more beginner ----------
    bird: "bird | BURD | /bɝd/ | “ir” says /ur/.",
    fish: "fish | FISH | /fɪʃ/",
    tree: "tree | TREE | /tri/",
    star: "star | STAR | /stɑr/",
    moon: "moon | MOON | /mun/",
    ball: "ball | BAWL | /bɔl/ | “a” says /aw/ before ll.",
    cake: "cake | KAYK | /keɪk/ | The final e is silent and makes the a say its name.",
    bike: "bike | BYKE | /baɪk/ | The final e is silent and makes the i say its name.",
    rain: "rain | RAYN | /reɪn/ | “ai” says /ay/.",
    snow: "snow | SNOH | /snoʊ/ | “ow” says /oh/ here.",
    shoe: "shoe | SHOO | /ʃu/ | “oe” says /oo/ here.",
    hand: "hand | HAND | /hænd/",
    door: "door | DOR | /dɔr/ | “oo” says /o/ here.",
    desk: "desk | DESK | /dɛsk/",
    lamp: "lamp | LAMP | /læmp/",
    picture: "pic-ture | PIK-chur | /ˈpɪk.tʃɚ/ | “ture” says /chur/.",
    another: "an-oth-er | uh-NUTH-ur | /əˈnʌð.ɚ/ | The “o” says /u/.",
    thought: "thought | THAWT | /θɔt/ | “ough” says /aw/; the gh is silent.",
    through: "through | THROO | /θru/ | “ough” says /oo/; the gh is silent.",
    careful: "care-ful | KAIR-ful | /ˈkɛr.fəl/ | The ending is -ful with one l.",
    kitchen: "kitch-en | KICH-un | /ˈkɪtʃ.ən/ | “tch” says /ch/.",
    morning: "morn-ing | MOR-ning | /ˈmɔr.nɪŋ/",
    evening: "eve-ning | EEV-ning | /ˈiv.nɪŋ/",
    holiday: "hol-i-day | HOL-uh-day | /ˈhɑl.ə.deɪ/",
    cousin: "cous-in | KUZ-in | /ˈkʌz.ɪn/ | “ou” says /u/, like in “cut”.",
    sister: "sis-ter | SIS-tur | /ˈsɪs.tɚ/",
    brother: "broth-er | BRUTH-ur | /ˈbrʌð.ɚ/ | “o” says /u/.",
    teacher: "teach-er | TEE-chur | /ˈti.tʃɚ/",
    student: "stu-dent | STOO-dunt | /ˈstu.dənt/",
    journey: "jour-ney | JUR-nee | /ˈdʒɝ.ni/ | “ou” says /ur/.",
    hungry: "hun-gry | HUNG-gree | /ˈhʌŋ.ɡri/",
    thirsty: "thirst-y | THUR-stee | /ˈθɝ.sti/ | “ir” says /ur/.",
    thankful: "thank-ful | THANGK-ful | /ˈθæŋk.fəl/ | The ending is -ful with one l.",
    birthday: "birth-day | BURTH-day | /ˈbɝθ.deɪ/",
    remember: "re-mem-ber | rih-MEM-bur | /rɪˈmɛm.bɚ/",
    alphabet: "al-pha-bet | AL-fuh-bet | /ˈæl.fə.bɛt/ | “ph” says /f/.",
    computer: "com-put-er | kum-PYOO-tur | /kəmˈpju.tɚ/ | “u” says /yoo/.",
    continue: "con-tin-ue | kun-TIN-yoo | /kənˈtɪn.ju/ | The ending -ue says /yoo/.",
    decision: "de-ci-sion | dih-SIZH-un | /dɪˈsɪʒ.ən/ | “sion” says /zhun/.",
    exercise: "ex-er-cise | EK-sur-syze | /ˈɛk.sɚ.saɪz/ | “cise” says /syze/.",
    furniture: "fur-ni-ture | FUR-nuh-chur | /ˈfɝ.nɪ.tʃɚ/ | “ture” says /chur/.",
    direction: "di-rec-tion | duh-REK-shun | /dəˈrɛk.ʃən/ | “tion” says /shun/.",
    character: "char-ac-ter | KAIR-ik-tur | /ˈkɛr.ɪk.tɚ/ | “ch” says /k/.",
    adventure: "ad-ven-ture | ud-VEN-chur | /ədˈvɛn.tʃɚ/ | “ture” says /chur/.",
    chocolate: "choc-o-late | CHOK-uh-lit | /ˈtʃɑk.ə.lɪt/ | Often said in two syllables: CHOK-lit.",
    dangerous: "dan-ger-ous | DAYN-jur-us | /ˈdeɪn.dʒɚ.əs/ | “a” says its name and “ge” says /j/.",
    difficult: "dif-fi-cult | DIF-ih-kult | /ˈdɪf.ɪ.kəlt/ | Double f.",
    vacation: "va-ca-tion | vay-KAY-shun | /veɪˈkeɪ.ʃən/ | “tion” says /shun/.",
    mountain: "moun-tain | MOWN-tun | /ˈmaʊn.tən/ | “ain” sounds like “un”.",
    thousand: "thou-sand | THOW-zund | /ˈθaʊ.zənd/ | “s” says /z/ here.",
    hospital: "hos-pi-tal | HOS-pih-tul | /ˈhɑs.pɪ.təl/",
    dictionary: "dic-tion-ar-y | DIK-shuh-ner-ee | /ˈdɪk.ʃə.nɛr.i/ | “tion” says /shun/.",
    temperature: "tem-per-a-ture | TEM-pur-uh-chur | /ˈtɛm.pɚ.ə.tʃɚ/ | Four syllables, and “ture” says /chur/.",
    disappear: "dis-ap-pear | dis-uh-PEER | /ˌdɪs.əˈpɪr/ | One s, then two p's.",
    disappoint: "dis-ap-point | dis-uh-POINT | /ˌdɪs.əˈpɔɪnt/ | One s, then two p's.",
    appreciate: "ap-pre-ci-ate | uh-PREE-shee-ayt | /əˈpri.ʃi.eɪt/ | “ci” says /sh/.",
    communicate: "com-mu-ni-cate | kuh-MYOO-nuh-kayt | /kəˈmju.nə.keɪt/ | Double m.",
    experience: "ex-pe-ri-ence | ik-SPEER-ee-uns | /ɪkˈspɪr.i.əns/ | Ends in -ence.",
    imagination: "i-mag-i-na-tion | ih-maj-uh-NAY-shun | /ɪˌmædʒ.əˈneɪ.ʃən/ | “g” says /j/ and “tion” says /shun/.",
    information: "in-for-ma-tion | in-fur-MAY-shun | /ˌɪn.fɚˈmeɪ.ʃən/ | “tion” says /shun/.",
    personality: "per-son-al-i-ty | pur-suh-NAL-ih-tee | /ˌpɝ.səˈnæl.ɪ.ti/ | The stress moves to “nal”.",
    professional: "pro-fes-sion-al | pruh-FESH-uh-nul | /prəˈfɛʃ.ə.nəl/ | Double s; “ssion” says /shun/.",
    unfortunately: "un-for-tu-nate-ly | un-FOR-chuh-nit-lee | /ʌnˈfɔr.tʃə.nɪt.li/ | “tu” says /chuh/.",
    responsibility: "re-spon-si-bil-i-ty | rih-spon-suh-BIL-ih-tee | /rɪˌspɑn.sə.ˈbɪl.ɪ.ti/ | Six syllables; the stress is on “bil”.",
    extraordinary: "ex-traor-di-nar-y | ik-STROR-duh-ner-ee | /ɪkˈstrɔr.də.nɛr.i/ | Not “extra-ordinary”: say ik-STROR-duh-ner-ee.",
    conscience: "con-science | KON-shuns | /ˈkɑn.ʃəns/ | “sc” says /sh/.",
    pronunciation: "pro-nun-ci-a-tion | pruh-nun-see-AY-shun | /prəˌnʌn.siˈeɪ.ʃən/ | Say “nun”, not “noun”: there is no “ou”.",
    miscellaneous: "mis-cel-la-ne-ous | mis-uh-LAY-nee-us | /ˌmɪs.əˈleɪ.ni.əs/ | “sc” says /s/; ends in -eous.",
    unprecedented: "un-prec-e-dent-ed | un-PRES-uh-den-tid | /ʌnˈprɛs.ɪˌdɛn.tɪd/ | Starts with un-; the stress is on “pres”.",
    indispensable: "in-dis-pens-a-ble | in-dis-PEN-suh-bul | /ˌɪn.dɪˈspɛn.sə.bəl/ | Ends in -able, not -ible.",
    subconscious: "sub-con-scious | sub-KON-shus | /ˌsʌbˈkɑn.ʃəs/ | “sc” says /sh/.",
    exaggerate: "ex-ag-ger-ate | ig-ZAJ-uh-rayt | /ɪɡˈzædʒ.ə.reɪt/ | “x” says /gz/ and “gg” says /j/ here.",
    maintenance: "main-te-nance | MAYN-tuh-nuns | /ˈmeɪn.tə.nəns/ | Not “maintain” + ance: the middle is “te”.",
    questionable: "ques-tion-a-ble | KWES-chun-uh-bul | /ˈkwɛs.tʃə.nə.bəl/ | Ends in -able.",
    perseverance: "per-se-ver-ance | pur-suh-VEER-uns | /ˌpɝ.səˈvɪr.əns/ | Ends in -ance.",
    vulnerable: "vul-ner-a-ble | VUL-nur-uh-bul | /ˈvʌl.nɚ.ə.bəl/ | Say the first l: it is “vul”, not “vun”.",

    // ---------- US / UK spelling pairs (same sound in both spellings) ----------
    color: "col-or | KUL-ur | /ˈkʌl.ɚ/ | “o” says /u/.",
    honor: "hon-or | ON-ur | /ˈɑn.ɚ/ | The h is silent.",
    flavor: "fla-vor | FLAY-vur | /ˈfleɪ.vɚ/",
    humor: "hu-mor | HYOO-mur | /ˈhju.mɚ/ | Say the h, then /yoo/.",
    labor: "la-bor | LAY-bur | /ˈleɪ.bɚ/",
    rumor: "ru-mor | ROO-mur | /ˈru.mɚ/",
    harbor: "har-bor | HAR-bur | /ˈhɑr.bɚ/",
    vapor: "va-por | VAY-pur | /ˈveɪ.pɚ/",
    center: "cen-ter | SEN-tur | /ˈsɛn.tɚ/ | The first c says /s/.",
    theater: "the-a-ter | THEE-uh-tur | /ˈθi.ə.tɚ/ | Three syllables.",
    meter: "me-ter | MEE-tur | /ˈmi.tɚ/",
    liter: "li-ter | LEE-tur | /ˈli.tɚ/ | “i” says /ee/ here.",
    fiber: "fi-ber | FY-bur | /ˈfaɪ.bɚ/",
    organize: "or-gan-ize | OR-guh-nyze | /ˈɔr.ɡə.naɪz/ | “ize” says /eyez/.",
    realize: "re-al-ize | REE-uh-lyze | /ˈri.ə.laɪz/ | “ize” says /eyez/.",
    recognize: "rec-og-nize | REK-ug-nyze | /ˈrɛk.əɡ.naɪz/ | The g is pronounced: rec-og-nize.",
    apologize: "a-pol-o-gize | uh-POL-uh-jyze | /əˈpɑl.ə.dʒaɪz/ | “g” says /j/.",
    memorize: "mem-o-rize | MEM-uh-ryze | /ˈmɛm.ə.raɪz/ | “ize” says /eyez/.",
    catalog: "cat-a-log | KAT-uh-lawg | /ˈkæt.ə.lɔɡ/",
    dialog: "di-a-log | DY-uh-lawg | /ˈdaɪ.ə.lɔɡ/",
    defense: "de-fense | dih-FENS | /dɪˈfɛns/ | In sports, the noun is often said DEE-fens.",
    license: "li-cense | LY-suns | /ˈlaɪ.səns/ | “c” says /s/.",
    traveling: "trav-el-ing | TRAV-uh-ling | /ˈtræv.ə.lɪŋ/",
    canceled: "can-celed | KAN-suld | /ˈkæn.səld/ | “c” says /s/ and “ed” sounds like “d”.",
    gray: "gray | GRAY | /ɡreɪ/",
    pajamas: "pa-ja-mas | puh-JAH-muz | /pəˈdʒɑ.məz/ | “j” says /j/ and “a” says /ah/.",
    mustache: "mus-tache | MUS-tash | /ˈmʌs.tæʃ/ | “ache” says /ash/.",
    fulfill: "ful-fill | ful-FIL | /fʊlˈfɪl/ | Double l in “fill”, but a single l in “ful”.",

    // ---------- hard ----------
    achievement: "a-chieve-ment | uh-CHEEV-munt | /əˈtʃiv.mənt/ | “ie” says /ee/.",
    committee: "com-mit-tee | kuh-MIT-ee | /kəˈmɪt.i/ | Double m, double t, double e.",
    conscious: "con-scious | KON-shus | /ˈkɑn.ʃəs/ | “sc” says /sh/.",
    existence: "ex-is-tence | ig-ZIS-tuns | /ɪɡˈzɪs.təns/ | Ends in -ence.",
    independent: "in-de-pen-dent | in-dih-PEN-dunt | /ˌɪn.dɪˈpɛn.dənt/ | Ends in -ent.",
    occurrence: "oc-cur-rence | uh-KUR-uns | /əˈkɝ.əns/ | Double c, double r.",
    parallel: "par-al-lel | PAIR-uh-lel | /ˈpɛr.ə.lɛl/ | A double l in the middle, then a single l at the end.",
    possession: "pos-ses-sion | puh-ZESH-un | /pəˈzɛʃ.ən/ | Two double s's; the first “ss” sounds like /z/.",
    privilege: "priv-i-lege | PRIV-uh-lij | /ˈprɪv.ə.lɪdʒ/ | “ege” says /ij/.",
    recommend: "rec-om-mend | rek-uh-MEND | /ˌrɛk.əˈmɛnd/ | One c, two m's.",
    sincerely: "sin-cere-ly | sin-SEER-lee | /sɪnˈsɪr.li/ | “c” says /s/.",
    cemetery: "cem-e-ter-y | SEM-uh-ter-ee | /ˈsɛm.ə.tɛr.i/ | Ends in -ery, not -ary.",
    handkerchief: "hand-ker-chief | HANG-kur-chif | /ˈhæŋ.kɚ.tʃɪf/ | The d is silent; “chief” says /chif/.",
    sacrilege: "sac-ri-lege | SAK-ruh-lij | /ˈsæk.rə.lɪdʒ/ | “ege” says /ij/.",
    yacht: "yacht | YAHT | /jɑt/ | “acht” says /ot/; the ch is silent.",
    colonel: "colo-nel | KUR-nul | /ˈkɝ.nəl/ | Said like “kernel”: the first l sounds like r.",
    accommodate: "ac-com-mo-date | uh-KOM-uh-dayt | /əˈkɑm.ə.deɪt/ | Double c, double m.",
    acquiesce: "ac-qui-esce | ak-wee-ES | /ˌæk.wiˈɛs/ | “qu” says /kw/ and “sce” says /s/.",
    liaison: "li-ai-son | lee-AY-zon | /liˈeɪ.zɑn/ | “s” says /z/.",
    reminiscence: "rem-i-nis-cence | rem-uh-NIS-uns | /ˌrɛm.ɪˈnɪs.əns/ | “sc” says /s/.",
    renaissance: "ren-ais-sance | REN-uh-sahns | /ˈrɛn.ə.sɑns/ | “ai” is weak: it sounds like “uh”.",
    sovereignty: "sov-er-eign-ty | SOV-ur-in-tee | /ˈsɑv.ɚ.ɪn.ti/ | “eign” says /in/.",
    surreptitious: "sur-rep-ti-tious | sur-up-TISH-us | /ˌsɝ.əpˈtɪʃ.əs/ | “tious” says /shus/.",
    unanimous: "u-nan-i-mous | yoo-NAN-uh-mus | /juˈnæn.ə.məs/ | The first u says /yoo/.",
    vengeance: "ven-geance | VEN-juns | /ˈvɛn.dʒəns/ | “ge” says /j/.",
    whimsical: "whim-si-cal | WIM-zih-kul | /ˈwɪm.zɪ.kəl/ | “s” says /z/.",

    // ---------- more expert ----------
    camaraderie: "ca-ma-ra-de-rie | kah-muh-RAH-duh-ree | /ˌkɑ.məˈrɑ.də.ri/ | A French word: “ie” says /ee/.",
    gauge: "gauge | GAYJ | /ɡeɪdʒ/ | “au” says /ay/ and “ge” says /j/.",
    inoculate: "in-oc-u-late | ih-NOK-yuh-layt | /ɪˈnɑk.jə.leɪt/ | One n, one c.",
    juxtapose: "jux-ta-pose | JUK-stuh-pohz | /ˈdʒʌk.stə.poʊz/ | “x” says /ks/.",
    labyrinth: "lab-y-rinth | LAB-uh-rinth | /ˈlæb.ə.rɪnθ/ | “y” says /uh/ in the middle.",
    mnemonic: "mne-mon-ic | nih-MON-ik | /nɪˈmɑn.ɪk/ | “mn” says /n/: the m is silent.",
    paraphernalia: "par-a-pher-na-lia | pair-uh-fur-NAYL-yuh | /ˌpɛr.ə.fɚˈneɪl.jə/ | “ph” says /f/.",
    pharaoh: "pha-raoh | FAIR-oh | /ˈfɛr.oʊ/ | “ph” says /f/ and “aoh” says /oh/.",
    supersede: "su-per-sede | soo-pur-SEED | /ˌsu.pɚˈsid/ | One of the only words ending in -sede.",
    cinnamon: "cin-na-mon | SIN-uh-mun | /ˈsɪn.ə.mən/ | “c” says /s/; double n.",
    physician: "phy-si-cian | fih-ZISH-un | /fɪˈzɪʃ.ən/ | “ph” says /f/ and “cian” says /shun/.",
    resemblance: "re-sem-blance | rih-ZEM-bluns | /rɪˈzɛm.bləns/ | “s” says /z/.",
    trustworthy: "trust-wor-thy | TRUST-wur-thee | /ˈtrʌst.wɝ.ði/ | “wor” says /wur/.",
    prestigious: "pres-ti-gious | pres-TEE-jus | /prɛˈsti.dʒəs/ | “gious” says /jus/.",
  // ---------- wave 2: beginner ----------
    hat: "hat | HAT | /hæt/",
    pen: "pen | PEN | /pɛn/",
    pig: "pig | PIG | /pɪɡ/",
    cup: "cup | CUP | /kʌp/",
    bed: "bed | BED | /bɛd/",
    bus: "bus | BUS | /bʌs/",
    egg: "egg | EG | /ɛɡ/",
    red: "red | RED | /rɛd/",
    sit: "sit | SIT | /sɪt/",
    ship: "ship | SHIP | /ʃɪp/ | “sh” makes one sound, /sh/, from two letters.",
    duck: "duck | DUK | /dʌk/ | “ck” says /k/.",
    nest: "nest | NEST | /nɛst/",
    farm: "farm | FARM | /fɑrm/ | “ar” says /ar/.",
    corn: "corn | KORN | /kɔrn/ | “or” says /or/.",
    boat: "boat | BOHT | /boʊt/ | “oa” says /oh/.",
    road: "road | ROHD | /roʊd/ | “oa” says /oh/.",
    kite: "kite | KYTE | /kaɪt/ | The final e is silent and makes the i say its name.",
    home: "home | HOHM | /hoʊm/ | The final e is silent and makes the o say its name.",
    soup: "soup | SOOP | /sup/ | “ou” says /oo/ here.",
    leaf: "leaf | LEEF | /lif/ | “ea” says /ee/.",
    baby: "ba-by | BAY-bee | /ˈbeɪ.bi/ | The final y says /ee/.",
    sofa: "so-fa | SOH-fuh | /ˈsoʊ.fə/ | The final a says a weak “uh”.",
    play: "play | PLAY | /pleɪ/ | “ay” says /ay/.",
    plane: "plane | PLAYN | /pleɪn/ | The final e is silent and makes the a say its name.",
    train: "train | TRAYN | /treɪn/ | “ai” says /ay/.",
    bread: "bread | BRED | /brɛd/ | “ea” says a short /e/, like in “head”.",
    plate: "plate | PLAYT | /pleɪt/ | The final e is silent and makes the a say its name.",
    spoon: "spoon | SPOON | /spun/ | “oo” says /oo/.",
    horse: "horse | HORSS | /hɔrs/ | “or” says /or/ and the final e is silent.",
    clock: "clock | KLOK | /klɑk/ | “ck” says /k/.",
    sheep: "sheep | SHEEP | /ʃip/ | “ee” says /ee/. One sheep or many sheep: the word does not change.",
    cloud: "cloud | KLOWD | /klaʊd/ | “ou” says /ow/.",
    stone: "stone | STOHN | /stoʊn/ | The final e is silent and makes the o say its name.",
    grass: "grass | GRASS | /ɡræs/",
    pizza: "piz-za | PEET-suh | /ˈpit.sə/ | “zz” says /ts/ in this Italian word.",

  // ---------- wave 2: easy ----------
    they: "they | THAY | /ðeɪ/ | “ey” says /ay/ here.",
    said: "said | SED | /sɛd/ | “ai” says a short /e/, not /ay/.",
    were: "were | WUR | /wɝ/ | “ere” says /ur/, not like “here”.",
    would: "would | WUD | /wʊd/ | The l is silent: it sounds like “wood”.",
    could: "could | KUD | /kʊd/ | The l is silent: it sounds like “kood”.",
    should: "should | SHUD | /ʃʊd/ | The l is silent: it sounds like “shood”.",
    enough: "e-nough | ih-NUF | /ɪˈnʌf/ | “ough” says /uf/ here.",
    laugh: "laugh | LAF | /læf/ | “gh” says /f/ here.",
    write: "write | RYTE | /raɪt/ | The w is silent.",
    wrong: "wrong | RAWNG | /rɔŋ/ | The w is silent.",
    knee: "knee | NEE | /ni/ | The k is silent.",
    knife: "knife | NYFE | /naɪf/ | The k is silent and the final e makes the i say its name.",
    knock: "knock | NOK | /nɑk/ | The k is silent.",
    climb: "climb | KLYME | /klaɪm/ | The final b is silent.",
    listen: "lis-ten | LIS-un | /ˈlɪs.ən/ | The t is silent.",
    answer: "an-swer | AN-sur | /ˈæn.sɚ/ | The w is silent.",
    whistle: "whis-tle | WIS-ul | /ˈwɪs.əl/ | The t is silent and “wh” says /w/.",
    honest: "hon-est | ON-ist | /ˈɑn.ɪst/ | The h is silent.",
    hour: "hour | OWR | /aʊr/ | The h is silent: it sounds like “our”.",
    ghost: "ghost | GOHST | /ɡoʊst/ | The h is silent.",
    castle: "cas-tle | KAS-ul | /ˈkæs.əl/ | The t is silent.",
    walk: "walk | WAWK | /wɔk/ | The l is silent.",
    again: "a-gain | uh-GEN | /əˈɡɛn/ | “ai” says a short /e/ here.",
    heart: "heart | HART | /hɑrt/ | “ear” says /ar/ here.",
    early: "ear-ly | UR-lee | /ˈɝ.li/ | “ear” says /ur/ here.",
    guess: "guess | GES | /ɡɛs/ | The u is silent; “gu” says /g/.",
    guide: "guide | GYDE | /ɡaɪd/ | The u is silent; “gu” says /g/.",
    busy: "bus-y | BIZ-ee | /ˈbɪz.i/ | “u” says a short /i/ here.",
    once: "once | WUNSS | /wʌns/ | It starts with a /w/ sound that the spelling does not show.",
    country: "coun-try | KUN-tree | /ˈkʌn.tri/ | “ou” says a short /u/.",
    young: "young | YUNG | /jʌŋ/ | “ou” says a short /u/.",
    group: "group | GROOP | /ɡrup/ | “ou” says /oo/.",
    minute: "min-ute | MIN-it | /ˈmɪn.ɪt/ | The ending -ute sounds like “it”.",
    sugar: "su-gar | SHOOG-ur | /ˈʃʊɡ.ɚ/ | The first “s” says /sh/.",
    orange: "or-ange | OR-inj | /ˈɔr.ɪndʒ/ | “ange” says /inj/.",
    breakfast: "break-fast | BREK-fust | /ˈbrɛk.fəst/ | “ea” says a short /e/.",
    ocean: "o-cean | OH-shun | /ˈoʊ.ʃən/ | “cea” says /sh/.",
    thunder: "thun-der | THUN-dur | /ˈθʌn.dɚ/ | “th” makes the sound in “thin”.",
    feather: "feath-er | FETH-ur | /ˈfɛð.ɚ/ | “ea” says a short /e/.",
    forest: "for-est | FOR-ist | /ˈfɔr.ɪst/ | The ending -est sounds like “ist”.",
    garden: "gar-den | GAR-dun | /ˈɡɑr.dən/ | The ending -en sounds like “un”.",
    window: "win-dow | WIN-doh | /ˈwɪn.doʊ/ | “ow” says /oh/ at the end.",
    pencil: "pen-cil | PEN-sul | /ˈpɛn.səl/ | The c says /s/ before i.",
    family: "fam-i-ly | FAM-uh-lee | /ˈfæm.ə.li/ | The middle i says a weak “uh”.",
    giant: "gi-ant | JY-unt | /ˈdʒaɪ.ənt/ | “g” says /j/ before i.",

  // ---------- wave 2: medium ----------
    address: "ad-dress | uh-DRESS | /əˈdrɛs/ | Two d’s and two s’s: ad + dress.",
    argument: "ar-gu-ment | AR-gyuh-munt | /ˈɑr.ɡjə.mənt/ | Drop the e from “argue” before adding -ment.",
    beginning: "be-gin-ning | bih-GIN-ing | /bɪˈɡɪn.ɪŋ/ | Double the n before adding -ing.",
    bargain: "bar-gain | BAR-gin | /ˈbɑr.ɡɪn/ | “ain” says a short “in”.",
    behavior: "be-hav-ior | bih-HAYV-yur | /bɪˈheɪv.jɚ/ | The ending sounds like “yur”: -ior in American spelling, -iour in British.",
    cozy: "co-zy | KOH-zee | /ˈkoʊ.zi/ | The middle sound is /z/: American spelling writes it z, British spelling writes s.",
    analyze: "an-a-lyze | AN-uh-lyze | /ˈæn.ə.laɪz/ | The ending says /eyez/: -yze in American spelling, -yse in British.",
    courage: "cour-age | KUR-ij | /ˈkɝ.ɪdʒ/ | “ou” says /ur/ and “age” says /ij/.",
    curious: "cu-ri-ous | KYUR-ee-us | /ˈkjʊr.i.əs/ | The ending -ous says “us”.",
    delicious: "de-li-cious | dih-LISH-us | /dɪˈlɪʃ.əs/ | “cious” says /shus/.",
    describe: "de-scribe | dih-SKRYBE | /dɪˈskraɪb/ | The final e is silent and makes the i say its name.",
    fierce: "fierce | FEERSS | /fɪrs/ | “ie” says /ee/ before r: remember i before e.",
    guard: "guard | GARD | /ɡɑrd/ | The u is silent; “gu” says /g/.",
    guitar: "gui-tar | gih-TAR | /ɡɪˈtɑr/ | The u is silent; “gu” says /g/.",
    interrupt: "in-ter-rupt | in-tur-RUPT | /ˌɪn.tɚˈrʌpt/ | Double r: inter + rupt.",
    lightning: "light-ning | LYTE-ning | /ˈlaɪt.nɪŋ/ | No e in the middle: lightning, not lightening.",
    muscle: "mus-cle | MUS-ul | /ˈmʌs.əl/ | The c is silent: it sounds like “mussel”.",
    ordinary: "or-di-nar-y | OR-dih-nair-ee | /ˈɔr.dɪ.nɛr.i/ | The ending -ary says “airy”.",
    peculiar: "pe-cu-liar | pih-KYOOL-yur | /pɪˈkjul.jɚ/ | The ending “liar” says /lyur/.",
    permanent: "per-ma-nent | PUR-muh-nunt | /ˈpɝ.mə.nənt/ | The ending -ent says “unt”.",
    pollution: "pol-lu-tion | puh-LOO-shun | /pəˈlu.ʃən/ | Double l: pol + lution. The ending -tion says /shun/.",
    recipe: "rec-i-pe | RES-uh-pee | /ˈrɛs.ə.pi/ | The final e says /ee/.",
    sandwich: "sand-wich | SAND-wich | /ˈsænd.wɪtʃ/ | Many people skip the d when they say it, so remember: sand + wich.",
    secretary: "sec-re-tar-y | SEK-ruh-ter-ee | /ˈsɛk.rə.tɛr.i/ | The ending -ary says “airy”. Only one c.",
    stomach: "stom-ach | STUM-uk | /ˈstʌm.ək/ | “ch” says /k/ and “o” says a short /u/.",
    strength: "strength | STRENGKTH | /strɛŋkθ/ | One syllable with eight letters; it ends in -gth.",
    success: "suc-cess | suk-SESS | /səkˈsɛs/ | Two c’s and two s’s: suc + cess.",
    suddenly: "sud-den-ly | SUD-un-lee | /ˈsʌd.ən.li/ | Keep the double d from sudden, then add -ly.",
    tongue: "tongue | TUNG | /tʌŋ/ | “ue” is silent and “o” says a short /u/.",
    usually: "u-su-al-ly | YOO-zhoo-uh-lee | /ˈju.ʒu.ə.li/ | “s” says /zh/; it is usual + ly, so two l’s.",
    weight: "weight | WAYT | /weɪt/ | “eigh” says /ay/; the gh is silent.",
    interesting: "in-ter-est-ing | IN-tur-es-ting | /ˈɪn.tɚ.ɛs.tɪŋ/ | Written in four syllables (in-ter-est-ing), though people often say three.",
    comfortable: "com-fort-a-ble | KUM-fur-tuh-bul | /ˈkʌm.fɚ.tə.bəl/ | Written in four syllables (com-fort-a-ble), though people often say three.",
    excellent: "ex-cel-lent | EK-suh-lunt | /ˈɛk.sə.lənt/ | Double l: excel + lent.",
    accident: "ac-ci-dent | AK-suh-dunt | /ˈæk.sə.dənt/ | Two c’s: the first says /k/, the second says /s/.",
    accept: "ac-cept | ak-SEPT | /ækˈsɛpt/ | Two c’s: ac + cept. Do not mix it up with “except”.",
    celebrate: "cel-e-brate | SEL-uh-brayt | /ˈsɛl.ə.breɪt/ | The first c says /s/ before e.",
    climate: "cli-mate | KLY-mit | /ˈklaɪ.mɪt/ | The ending -ate sounds like “it”.",
    conversation: "con-ver-sa-tion | kon-vur-SAY-shun | /ˌkɑn.vɚˈseɪ.ʃən/ | “tion” says /shun/, and there is an a before it: -sa-tion.",
    enormous: "e-nor-mous | ih-NOR-mus | /ɪˈnɔr.məs/ | The ending -ous says “us”.",
    exciting: "ex-cit-ing | ik-SY-ting | /ɪkˈsaɪ.tɪŋ/ | Drop the e from “excite” before adding -ing.",
    forehead: "fore-head | FOR-hed | /ˈfɔr.hɛd/ | It is fore + head, so “ea” says a short /e/.",
    frighten: "fright-en | FRY-tun | /ˈfraɪ.tən/ | The gh is silent.",
    gorgeous: "gor-geous | GOR-jus | /ˈɡɔr.dʒəs/ | “geous” says /jus/.",
    grammar: "gram-mar | GRAM-ur | /ˈɡræm.ɚ/ | It ends in -ar, not -er: gramm-ar.",
    mystery: "mys-ter-y | MIS-tur-ee | /ˈmɪs.tɚ.i/ | The first y says a short /i/.",
    quiet: "qui-et | KWY-ut | /ˈkwaɪ.ət/ | “ie” makes two sounds: /eye/ then /uh/.",
    receipt: "re-ceipt | rih-SEET | /rɪˈsit/ | The p is silent; “ei” follows the c.",
    scissors: "scis-sors | SIZ-urz | /ˈsɪz.ɚz/ | “sc” says /s/ and the “ss” says /z/.",
    straight: "straight | STRAYT | /streɪt/ | “eigh” says /ay/; the gh is silent.",

  // ---------- wave 2: hard ----------
    accessible: "ac-ces-si-ble | ak-SES-uh-bul | /ækˈsɛs.ə.bəl/ | It ends in -ible, not -able, and has double c and double s.",
    accidentally: "ac-ci-den-tal-ly | ak-suh-DEN-tuh-lee | /ˌæk.səˈdɛn.təl.i/ | It is accidental + ly, so the ending is -ally, with two l’s.",
    acknowledge: "ac-knowl-edge | ak-NOL-ij | /ækˈnɑl.ɪdʒ/ | It starts with ac + know: the c and the k both appear.",
    ambiguous: "am-big-u-ous | am-BIG-yoo-us | /æmˈbɪɡ.ju.əs/ | The ending is -uous: u, o, u, s.",
    apparently: "ap-par-ent-ly | uh-PAIR-unt-lee | /əˈpɛr.ənt.li/ | Double p, then -ent: apparent + ly.",
    atmosphere: "at-mos-phere | AT-muh-sfeer | /ˈæt.mə.sfɪr/ | “ph” says /f/, as in “sphere”.",
    auxiliary: "aux-il-ia-ry | awg-ZIL-yuh-ree | /ɔɡˈzɪl.jə.ri/ | Four syllables, and the x says /gz/.",
    beneficial: "ben-e-fi-cial | ben-uh-FISH-ul | /ˌbɛn.əˈfɪʃ.əl/ | “cial” says /shul/.",
    bizarre: "bi-zarre | bih-ZAR | /bɪˈzɑr/ | Double r and a final e, but you only hear one /r/.",
    boundary: "bound-a-ry | BOWN-duh-ree | /ˈbaʊn.də.ri/ | The middle is -a-, not -e-: bound + a + ry.",
    bruise: "bruise | BROOZ | /bruz/ | “ui” says /oo/ and the final e is silent.",
    catastrophe: "ca-tas-tro-phe | kuh-TAS-truh-fee | /kəˈtæs.trə.fi/ | “phe” says /fee/.",
    chauffeur: "chauf-feur | SHOH-fur | /ˈʃoʊ.fɚ/ | A French word: “ch” says /sh/ and “au” says /oh/.",
    circumstance: "cir-cum-stance | SUR-kum-stans | /ˈsɝ.kəm.stæns/ | It ends in -stance, not -stence.",
    compliment: "com-pli-ment | KOM-pluh-munt | /ˈkɑm.plə.mənt/ | A compliment with an i is kind words; complement with an e completes something.",
    consensus: "con-sen-sus | kun-SEN-sus | /kənˈsɛn.səs/ | There is no “census” hiding in the middle of it: con + sen + sus.",
    criticize: "crit-i-cize | KRIT-uh-size | /ˈkrɪt.ə.saɪz/ | The ending says /eyez/: -ize in American spelling, -ise in British.",
    curriculum: "cur-ric-u-lum | kuh-RIK-yuh-lum | /kəˈrɪk.jə.ləm/ | Double r; it ends in -ulum.",
    desperate: "des-per-ate | DES-pur-it | /ˈdɛs.pɚ.ɪt/ | The ending -ate sounds like “it”; the middle is -per-.",
    discipline: "dis-ci-pline | DIS-uh-plin | /ˈdɪs.ə.plɪn/ | “sc” hides a single /s/ sound: the c is silent.",
    dilemma: "di-lem-ma | dih-LEM-uh | /dɪˈlɛm.ə/ | Double m: dilem + ma.",
    eccentric: "ec-cen-tric | ek-SEN-trik | /ɪkˈsɛn.trɪk/ | Two c’s: the first says /k/, the second says /s/.",
    efficient: "ef-fi-cient | ih-FISH-unt | /ɪˈfɪʃ.ənt/ | Double f; the “ie” follows i before e.",
    emphasize: "em-pha-size | EM-fuh-size | /ˈɛm.fə.saɪz/ | “ph” says /f/; the ending says /eyez/: -ize in American spelling, -ise in British.",
    enthusiasm: "en-thu-si-asm | en-THOO-zee-azm | /ɪnˈθu.zi.æz.əm/ | It ends in -asm: en-thu-si-asm.",
    equipment: "e-quip-ment | ih-KWIP-munt | /ɪˈkwɪp.mənt/ | Keep the p from equip, then add -ment.",
    especially: "es-pe-cial-ly | ih-SPESH-uh-lee | /ɪˈspɛʃ.ə.li/ | It is especial + ly, so it ends with two l’s.",
    familiar: "fa-mil-iar | fuh-MIL-yur | /fəˈmɪl.jɚ/ | The ending -iar says /yur/, not -er.",
    fluorescent: "fluo-res-cent | floo-RES-unt | /flʊˈrɛs.ənt/ | It starts fluo-; and “sc” says a single /s/.",
    fundamental: "fun-da-men-tal | fun-duh-MEN-tul | /ˌfʌn.dəˈmɛn.təl/ | It ends in -al; the middle is -da-men-.",
    harassment: "har-ass-ment | huh-RASS-munt | /həˈræs.mənt/ | One r and two s’s: har + ass + ment.",
    hypocrite: "hyp-o-crite | HIP-uh-krit | /ˈhɪp.ə.krɪt/ | The ending -ite sounds like “it”.",
    incidentally: "in-ci-den-tal-ly | in-suh-DEN-tuh-lee | /ˌɪn.səˈdɛn.təl.i/ | It is incidental + ly, so the ending is -ally.",
    irrelevant: "ir-rel-e-vant | ih-REL-uh-vunt | /ɪˈrɛl.ə.vənt/ | Double r: ir + relevant.",
    jealous: "jeal-ous | JEL-us | /ˈdʒɛl.əs/ | “ea” says a short /e/ and the ending -ous says “us”.",
    judgment: "judg-ment | JUJ-munt | /ˈdʒʌdʒ.mənt/ | American spelling drops the e after g; British spelling keeps it.",
    leisure: "lei-sure | LEE-zhur | /ˈli.ʒɚ/ | “ei” says /ee/ here, not /ay/, and “s” says /zh/.",
    lieutenant: "lieu-ten-ant | loo-TEN-unt | /luˈtɛn.ənt/ | In American English “lieu” says /loo/.",
    maneuver: "ma-neu-ver | muh-NOO-vur | /məˈnu.vɚ/ | The “eu” (British: “oeu”) says /oo/.",
    mathematics: "math-e-mat-ics | math-uh-MAT-iks | /ˌmæθ.əˈmæt.ɪks/ | Four syllables: math-e-mat-ics.",
    miniature: "min-i-a-ture | MIN-ee-uh-chur | /ˈmɪn.i.ə.tʃɚ/ | Four syllables: min-i-a-ture, and “ture” says /chur/.",
    noticeable: "no-tice-a-ble | NOH-tis-uh-bul | /ˈnoʊ.tɪs.ə.bəl/ | Keep the e from “notice” so the c still says /s/.",
    occasionally: "oc-ca-sion-al-ly | uh-KAY-zhun-uh-lee | /əˈkeɪ.ʒə.nə.li/ | Double c, and occasional + ly gives two l’s.",
    pastime: "pas-time | PAS-tyme | /ˈpæs.taɪm/ | Only one t in the middle: pas + time.",
    pursue: "pur-sue | pur-SOO | /pɚˈsu/ | “ue” at the end says /oo/.",
    sergeant: "ser-geant | SAR-junt | /ˈsɑr.dʒənt/ | “er” says /ar/ and “geant” says /junt/.",
    skeptical: "skep-ti-cal | SKEP-tuh-kul | /ˈskɛp.tɪ.kəl/ | The first sound is /sk/: spelled sk in American English, sc in British.",
    solemn: "sol-emn | SOL-um | /ˈsɑl.əm/ | The final n is silent.",
    subtle: "sub-tle | SUT-ul | /ˈsʌt.əl/ | The b is silent.",
    thorough: "thor-ough | THUR-oh | /ˈθɝ.oʊ/ | “ough” says /oh/ here.",

  // ---------- wave 2: expert ----------
    aficionado: "a-fi-cio-na-do | uh-fish-yuh-NAH-doh | /əˌfɪʃ.jəˈnɑ.doʊ/ | A Spanish word: “ci” says /sh/ and the ending is -ado.",
    ambidextrous: "am-bi-dex-trous | am-bih-DEKS-trus | /ˌæm.bɪˈdɛk.strəs/ | The ending -ous says “us”; “dex” comes from the Latin word for right hand.",
    anachronism: "a-nach-ro-nism | uh-NAK-ruh-nizm | /əˈnæk.rə.nɪz.əm/ | “ch” says /k/.",
    anesthesia: "an-es-the-sia | an-ihs-THEE-zhuh | /ˌæn.ɪsˈθi.ʒə/ | “th” says /th/ and “sia” says /zhuh/.",
    antediluvian: "an-te-di-lu-vi-an | an-tee-dih-LOO-vee-un | /ˌæn.ti.dɪˈlu.vi.ən/ | From Latin: ante (before) + diluvium (flood).",
    apocryphal: "a-poc-ry-phal | uh-POK-ruh-ful | /əˈpɑk.rə.fəl/ | “ph” says /f/.",
    archipelago: "ar-chi-pel-a-go | ar-kuh-PEL-uh-goh | /ˌɑr.kəˈpɛl.ə.ɡoʊ/ | “ch” says /k/.",
    bourgeois: "bour-geois | boorzh-WAH | /bʊrʒˈwɑ/ | A French word: “geois” says /zhwah/.",
    cacophony: "ca-coph-o-ny | kuh-KOF-uh-nee | /kəˈkɑf.ə.ni/ | “ph” says /f/.",
    chiaroscuro: "chi-a-ro-scu-ro | kee-ar-uh-SKYUR-oh | /kiˌɑr.əˈskjʊr.oʊ/ | Italian for light-dark: “chi” says /kee/ and “sc” says /sk/.",
    clandestine: "clan-des-tine | klan-DES-tin | /klænˈdɛs.tɪn/ | The ending -ine sounds like “in” here.",
    curmudgeon: "cur-mudg-eon | kur-MUJ-un | /kɚˈmʌdʒ.ən/ | “geon” says /jun/.",
    demagogue: "dem-a-gogue | DEM-uh-gog | /ˈdɛm.ə.ɡɑɡ/ | The ending -gogue says /gog/; the ue is silent.",
    dilettante: "dil-et-tan-te | dil-uh-TAHN-tee | /ˌdɪl.əˈtɑn.ti/ | Double l and double t; the final -te says /tee/.",
    ebullient: "e-bul-lient | ih-BUL-yunt | /ɪˈbʊl.jənt/ | Double l; “lient” says /lyunt/.",
    eclectic: "ec-lec-tic | ih-KLEK-tik | /ɪˈklɛk.tɪk/ | Both c’s say /k/.",
    ephemeral: "e-phem-er-al | ih-FEM-uh-rul | /ɪˈfɛm.ɚ.əl/ | “ph” says /f/.",
    epitome: "e-pit-o-me | ih-PIT-uh-mee | /ɪˈpɪt.ə.mi/ | The final e says /ee/, so it is not “epitom”.",
    esoteric: "es-o-ter-ic | es-uh-TAIR-ik | /ˌɛs.əˈtɛr.ɪk/ | The final c says /k/.",
    euphemism: "eu-phem-ism | YOO-fuh-mizm | /ˈju.fə.mɪz.əm/ | “eu” says /yoo/ and “ph” says /f/.",
    facetious: "fa-ce-tious | fuh-SEE-shus | /fəˈsi.ʃəs/ | It contains every vowel in order: a, e, i, o, u.",
    fastidious: "fas-tid-i-ous | fas-TID-ee-us | /fæˈstɪd.i.əs/ | The ending -ious says “ee-us”.",
    flamboyant: "flam-boy-ant | flam-BOY-unt | /flæmˈbɔɪ.ənt/ | “oy” says /oy/ and the ending -ant says “unt”.",
    gregarious: "gre-gar-i-ous | grih-GAIR-ee-us | /ɡrɪˈɡɛr.i.əs/ | The ending -ious says “ee-us”.",
    haphazard: "hap-haz-ard | hap-HAZ-urd | /hæpˈhæz.ɚd/ | It is hap + hazard, so both parts are spelled out.",
    hegemony: "he-gem-o-ny | hih-JEM-uh-nee | /hɪˈdʒɛm.ə.ni/ | The g says /j/ before e.",
    idyllic: "i-dyl-lic | eye-DIL-ik | /aɪˈdɪl.ɪk/ | Double l: idyl + lic.",
    ineffable: "in-ef-fa-ble | in-EF-uh-bul | /ɪnˈɛf.ə.bəl/ | Double f: in + eff + able.",
    insouciant: "in-sou-ci-ant | in-SOO-see-unt | /ɪnˈsu.si.ənt/ | A French word meaning “not worrying”: “ou” says /oo/.",
    irascible: "i-ras-ci-ble | ih-RAS-uh-bul | /ɪˈræs.ə.bəl/ | “sc” hides a single /s/ sound; the ending is -ible.",
    lackadaisical: "lack-a-dai-si-cal | lak-uh-DAY-zih-kul | /ˌlæk.əˈdeɪ.zɪ.kəl/ | “ai” says /ay/ and the s says /z/.",
    malfeasance: "mal-fea-sance | mal-FEE-zuns | /mælˈfi.zəns/ | mal (bad) + feasance (doing); the ending is -ance.",
    meticulous: "me-tic-u-lous | muh-TIK-yuh-lus | /məˈtɪk.jə.ləs/ | The ending -ous says “us”.",
    nonchalant: "non-cha-lant | non-shuh-LAHNT | /ˌnɑn.ʃəˈlɑnt/ | “ch” says /sh/ in this French word.",
    obsequious: "ob-se-qui-ous | ub-SEE-kwee-us | /əbˈsi.kwi.əs/ | “qui” says /kwee/.",
    ostentatious: "os-ten-ta-tious | os-ten-TAY-shus | /ˌɑs.tɛnˈteɪ.ʃəs/ | “tious” says /shus/.",
    perfunctory: "per-func-to-ry | pur-FUNK-tuh-ree | /pɚˈfʌŋk.tɚ.i/ | It ends in -ory.",
    pusillanimous: "pu-sil-lan-i-mous | pyoo-suh-LAN-uh-mus | /ˌpju.səˈlæn.ə.məs/ | Double l; it means small-spirited.",
    quintessential: "quin-tes-sen-tial | kwin-tuh-SEN-shul | /ˌkwɪn.təˈsɛn.ʃəl/ | “tial” says /shul/, and the middle has a double s.",
    rendezvous: "ren-dez-vous | RON-day-voo | /ˈrɑn.deɪ.vu/ | A French word: the final -vous says /voo/ and the s and z are silent.",
    schism: "schism | SIZM | /ˈsɪz.əm/ | “sch” says /s/ here, and the “s” says /z/.",
    serendipity: "ser-en-dip-i-ty | sair-un-DIP-uh-tee | /ˌsɛr.ənˈdɪp.ə.ti/ | The ending -ity says “uh-tee”.",
    soliloquy: "so-lil-o-quy | suh-LIL-uh-kwee | /səˈlɪl.ə.kwi/ | The ending -quy says /kwee/.",
    sycophant: "syc-o-phant | SIK-uh-funt | /ˈsɪk.ə.fənt/ | “ph” says /f/ and the first y says a short /i/.",
    ubiquitous: "u-biq-ui-tous | yoo-BIK-wuh-tus | /juˈbɪk.wə.təs/ | “qui” says /kwuh/ and the ending -ous says “us”.",
  };

  function parse(word, row) {
    const [syl, say, ipa, note] = row.split("|").map((p) => p.trim());
    const syllables = syl.split("-");
    const parts = say.split("-");
    // The stressed part is the uppercase one; single-syllable words have no stress to show.
    const stress = parts.length > 1 ? parts.findIndex((p) => p === p.toUpperCase()) : -1;
    return { word, syllables, say: parts, stress, ipa, note: note || "" };
  }

  // Rows that did not come from this file (AI-generated words) are untrusted, so every property the
  // guide relies on is checked, and a row that fails any check is rejected whole.
  function fromRow(word, row) {
    if (typeof row !== "string" || row.length > 500) return null;
    const parts = row.split("|").map((p) => p.trim());
    if (parts.length < 3 || parts.length > 4) return null;
    const [syl, say, ipaRaw, note = ""] = parts;
    const syllables = syl.toLowerCase().split("-");
    if (syllables.join("") !== String(word).toLowerCase() || syllables.some((s) => !/^[a-z]+$/.test(s))) return null;
    let spoken = say.split("-");
    if (spoken.length !== syllables.length || spoken.some((p) => !/^[A-Za-z]+$/.test(p))) return null;
    if (spoken.length === 1) spoken = [spoken[0].toUpperCase()];
    else if (spoken.filter((p) => p === p.toUpperCase()).length !== 1) return null; // exactly one stressed part
    const ipa = /^\/[^/]{1,60}\/$/.test(ipaRaw) ? ipaRaw : /^[^/]{1,60}$/.test(ipaRaw) ? `/${ipaRaw}/` : "";
    if (!ipa || note.length > 160) return null;
    return {
      word: String(word).toLowerCase(), syllables, say: spoken,
      stress: spoken.length > 1 ? spoken.findIndex((p) => p === p.toUpperCase()) : -1,
      ipa, note, source: "ai",
    };
  }

  const cache = new Map();

  // Look up by the spelling on screen, which may be the British variant of the base word.
  function get(spelled) {
    if (!spelled) return null;
    const key = String(spelled).toLowerCase();
    if (cache.has(key)) return cache.get(key);
    const list = typeof WORD_LIST !== "undefined" ? WORD_LIST : [];
    const base = list.find((w) => w.word === key || (w.variants && Object.values(w.variants).includes(key)));
    const row = ROWS[base ? base.word : key];
    const guide = row ? parse(key, row) : null;
    cache.set(key, guide);
    return guide;
  }

  // The built-in, hand-checked guide wins; a word's own AI-written row is the fallback.
  function forEntry(entry) {
    if (!entry) return null;
    const guide = get(entry.word) || fromRow(entry.word, entry.sounds);
    return guide && guide.source === "ai" && entry.pack ? { ...guide, source: "pack" } : guide;
  }

  window.SpellSounds = { get, fromRow, forEntry, rows: ROWS };
})();
