// Word list: from absolute-beginner sight words up to ultra-advanced vocabulary.
// Each entry: word (lowercase, letters a-z only, American spelling by default),
// hint, difficulty (beginner|easy|medium|hard|expert), category, an optional
// `rule` tag (key into RULE_TIPS), and an optional `variants` map (e.g.
// { uk: "colour" }) used when the learner's Spelling Style is set to British.
const WORD_LIST = [
  // ---------- beginner: first words, 3-5 letters, no tricky patterns ----------
  { word: "cat", hint: "A small pet that meows.", difficulty: "beginner", category: "nature" },
  { word: "dog", hint: "A pet that barks and wags its tail.", difficulty: "beginner", category: "nature" },
  { word: "sun", hint: "It shines in the sky in the daytime.", difficulty: "beginner", category: "nature" },
  { word: "run", hint: "To move fast on your feet.", difficulty: "beginner", category: "everyday" },
  { word: "jump", hint: "To push off the ground into the air.", difficulty: "beginner", category: "everyday" },
  { word: "frog", hint: "A small green animal that hops and swims.", difficulty: "beginner", category: "nature" },
  { word: "milk", hint: "A white drink that comes from cows.", difficulty: "beginner", category: "food" },
  { word: "book", hint: "You read this to learn a story.", difficulty: "beginner", category: "school" },
  { word: "happy", hint: "Feeling good and cheerful.", difficulty: "beginner", category: "people" },
  { word: "apple", hint: "A round fruit that can be red or green.", difficulty: "beginner", category: "food" },
  { word: "house", hint: "A building where people live.", difficulty: "beginner", category: "home" },
  { word: "water", hint: "You drink this when you're thirsty.", difficulty: "beginner", category: "everyday" },
  { word: "green", hint: "The color of grass.", difficulty: "beginner", category: "everyday" },
  { word: "smile", hint: "What your face does when you're happy.", difficulty: "beginner", category: "people" },
  { word: "chair", hint: "Furniture you sit on.", difficulty: "beginner", category: "home" },

  { word: "because", hint: "For the reason that.", difficulty: "easy", category: "everyday" },
  { word: "friend", hint: "Someone you like and trust.", difficulty: "easy", category: "people", rule: "ie_ei" },
  { word: "believe", hint: "To think something is true.", difficulty: "medium", category: "everyday", rule: "ie_ei" },
  { word: "separate", hint: "To divide or keep apart.", difficulty: "medium", category: "everyday", rule: "vowel_confusion" },
  { word: "definitely", hint: "Without any doubt.", difficulty: "hard", category: "everyday", rule: "tricky_ending" },
  { word: "necessary", hint: "Needed; required.", difficulty: "hard", category: "everyday", rule: "double_consonant" },
  { word: "receive", hint: "To get or be given something.", difficulty: "medium", category: "everyday", rule: "ie_ei" },
  { word: "though", hint: "Despite the fact that.", difficulty: "easy", category: "everyday", rule: "silent_letter" },
  { word: "beautiful", hint: "Very pleasing to look at.", difficulty: "medium", category: "everyday" },
  { word: "science", hint: "The study of the natural world.", difficulty: "medium", category: "school" },
  { word: "people", hint: "Human beings in general.", difficulty: "easy", category: "people" },
  { word: "different", hint: "Not the same as another.", difficulty: "medium", category: "everyday" },
  { word: "favorite", hint: "The one you like best.", difficulty: "medium", category: "everyday", variants: { uk: "favourite" } },
  { word: "weird", hint: "Strange or unusual.", difficulty: "easy", category: "everyday", rule: "ie_ei" },
  { word: "environment", hint: "The natural world around us.", difficulty: "hard", category: "nature" },
  { word: "government", hint: "The group that runs a country.", difficulty: "hard", category: "school" },
  { word: "restaurant", hint: "A place where you pay to eat a meal.", difficulty: "hard", category: "food", rule: "tricky_ending" },
  { word: "calendar", hint: "A chart showing days and months.", difficulty: "medium", category: "everyday", rule: "vowel_confusion" },
  { word: "vacuum", hint: "A machine that sucks up dust.", difficulty: "medium", category: "home", rule: "vowel_confusion" },
  { word: "rhythm", hint: "A regular repeated pattern of sound.", difficulty: "hard", category: "school", rule: "silent_letter" },
  { word: "language", hint: "The words a group of people use to talk.", difficulty: "medium", category: "school" },
  { word: "surprise", hint: "An unexpected event.", difficulty: "medium", category: "everyday", rule: "silent_letter" },
  { word: "immediately", hint: "Right away, with no delay.", difficulty: "hard", category: "everyday", rule: "double_consonant" },
  { word: "occasion", hint: "A special event or time.", difficulty: "medium", category: "everyday", rule: "double_consonant" },
  { word: "embarrass", hint: "To make someone feel shy or ashamed.", difficulty: "hard", category: "people", rule: "double_consonant" },
  { word: "knowledge", hint: "Facts and information you know.", difficulty: "medium", category: "school", rule: "silent_letter" },
  { word: "guarantee", hint: "A promise that something will happen.", difficulty: "hard", category: "everyday", rule: "tricky_ending" },
  { word: "mischievous", hint: "Playfully causing trouble.", difficulty: "hard", category: "people", rule: "ie_ei" },
  { word: "neighbor", hint: "Someone who lives next door.", difficulty: "medium", category: "people", rule: "silent_letter", variants: { uk: "neighbour" } },
  { word: "achieve", hint: "To successfully reach a goal.", difficulty: "medium", category: "school", rule: "ie_ei" },
  { word: "although", hint: "Even though.", difficulty: "easy", category: "everyday", rule: "silent_letter" },
  { word: "business", hint: "Work done to earn money.", difficulty: "medium", category: "everyday", rule: "silent_letter" },
  { word: "column", hint: "A vertical line of text or a pillar.", difficulty: "easy", category: "school", rule: "silent_letter" },
  { word: "foreign", hint: "From another country.", difficulty: "medium", category: "everyday", rule: "ie_ei" },
  { word: "grateful", hint: "Feeling thankful.", difficulty: "medium", category: "people" },
  { word: "height", hint: "How tall something is.", difficulty: "easy", category: "everyday", rule: "silent_letter" },
  { word: "island", hint: "Land surrounded by water.", difficulty: "easy", category: "nature", rule: "silent_letter" },
  { word: "jewelry", hint: "Rings, necklaces, and bracelets.", difficulty: "medium", category: "home", rule: "tricky_ending", variants: { uk: "jewellery" } },
  { word: "library", hint: "A place full of books to borrow.", difficulty: "medium", category: "school" },
  { word: "medicine", hint: "Something you take when you are sick.", difficulty: "medium", category: "home" },
  { word: "opposite", hint: "Completely different, the other side.", difficulty: "medium", category: "everyday", rule: "tricky_ending" },
  { word: "possible", hint: "Able to happen or be done.", difficulty: "medium", category: "everyday" },
  { word: "question", hint: "Something you ask to get an answer.", difficulty: "easy", category: "school" },
  { word: "rhyme", hint: "Words that end with the same sound.", difficulty: "easy", category: "school", rule: "silent_letter" },
  { word: "schedule", hint: "A plan of times for events.", difficulty: "hard", category: "school", rule: "tricky_ending" },
  { word: "tomorrow", hint: "The day after today.", difficulty: "easy", category: "everyday", rule: "double_consonant" },
  { word: "umbrella", hint: "You open it to stay dry in the rain.", difficulty: "easy", category: "home", rule: "double_consonant" },
  { word: "vegetable", hint: "A plant food like carrots or peas.", difficulty: "hard", category: "food", rule: "silent_letter" },
  { word: "weather", hint: "Sun, rain, wind, or snow outside.", difficulty: "easy", category: "nature" },

  // ---------- expert: ultra-advanced vocabulary ----------
  { word: "conscientious", hint: "Careful to do things thoroughly and correctly.", difficulty: "expert", category: "people", rule: "tricky_ending" },
  { word: "onomatopoeia", hint: "A word that imitates the sound it describes, like 'buzz'.", difficulty: "expert", category: "school", rule: "vowel_confusion" },
  { word: "bureaucracy", hint: "A system of government with many officials and strict rules.", difficulty: "expert", category: "school", rule: "tricky_ending" },
  { word: "questionnaire", hint: "A set of written questions used to gather information.", difficulty: "expert", category: "school", rule: "double_consonant" },
  { word: "entrepreneur", hint: "Someone who starts and runs their own business.", difficulty: "expert", category: "everyday", rule: "tricky_ending" },
  { word: "chrysanthemum", hint: "A flower with colorful, feathery petals.", difficulty: "expert", category: "nature", rule: "silent_letter" },
  { word: "idiosyncrasy", hint: "A quirky habit unique to one person.", difficulty: "expert", category: "people", rule: "vowel_confusion" },
  { word: "connoisseur", hint: "Someone with expert taste in food, art, or wine.", difficulty: "expert", category: "food", rule: "double_consonant" },
  { word: "camouflage", hint: "A pattern that helps something blend into its surroundings.", difficulty: "expert", category: "nature", rule: "tricky_ending" },
  { word: "silhouette", hint: "A dark outline seen against a bright background.", difficulty: "expert", category: "everyday", rule: "silent_letter" },
  { word: "rhinoceros", hint: "A large animal with one or two horns on its nose.", difficulty: "expert", category: "nature", rule: "silent_letter" },
  { word: "acquaintance", hint: "Someone you know but who isn't a close friend.", difficulty: "expert", category: "people", rule: "tricky_ending" },
  { word: "millennium", hint: "A period of one thousand years.", difficulty: "expert", category: "school", rule: "double_consonant" },
  { word: "hierarchy", hint: "A system that ranks people or things by importance.", difficulty: "expert", category: "school", rule: "ie_ei" },
  { word: "phenomenon", hint: "A remarkable or unusual fact or event.", difficulty: "expert", category: "school", rule: "vowel_confusion" },
  { word: "pneumonia", hint: "A serious illness that affects the lungs.", difficulty: "expert", category: "home", rule: "silent_letter" },
  { word: "cappuccino", hint: "A coffee drink topped with frothy milk.", difficulty: "expert", category: "food", rule: "double_consonant" },
  { word: "kaleidoscope", hint: "A tube toy that makes colorful, shifting patterns.", difficulty: "expert", category: "everyday", rule: "ie_ei" },

  // ---------- more beginner words ----------
  { word: "bird", hint: "An animal that flies and has feathers.", difficulty: "beginner", category: "nature" },
  { word: "fish", hint: "An animal that swims and breathes underwater.", difficulty: "beginner", category: "nature" },
  { word: "tree", hint: "A tall plant with a trunk, branches, and leaves.", difficulty: "beginner", category: "nature" },
  { word: "star", hint: "A bright point of light in the night sky.", difficulty: "beginner", category: "nature" },
  { word: "moon", hint: "It circles the earth and glows at night.", difficulty: "beginner", category: "nature" },
  { word: "ball", hint: "A round toy you throw, kick, or bounce.", difficulty: "beginner", category: "everyday" },
  { word: "cake", hint: "A sweet treat you eat on a birthday.", difficulty: "beginner", category: "food" },
  { word: "bike", hint: "You pedal it to ride around.", difficulty: "beginner", category: "everyday" },
  { word: "rain", hint: "Water that falls from clouds.", difficulty: "beginner", category: "nature" },
  { word: "snow", hint: "Soft white flakes that fall when it's cold.", difficulty: "beginner", category: "nature" },
  { word: "shoe", hint: "You wear this on your foot.", difficulty: "beginner", category: "home" },
  { word: "hand", hint: "The part of your body at the end of your arm.", difficulty: "beginner", category: "people" },
  { word: "door", hint: "You open this to walk into a room.", difficulty: "beginner", category: "home" },
  { word: "desk", hint: "A table you sit at to write or study.", difficulty: "beginner", category: "school" },
  { word: "lamp", hint: "It gives you light in a dark room.", difficulty: "beginner", category: "home" },

  // ---------- more easy words ----------
  { word: "picture", hint: "An image, drawing, or photo.", difficulty: "easy", category: "everyday" },
  { word: "another", hint: "One more, or a different one.", difficulty: "easy", category: "everyday" },
  { word: "thought", hint: "An idea in your mind.", difficulty: "easy", category: "everyday", rule: "silent_letter" },
  { word: "through", hint: "Moving in one side and out the other.", difficulty: "easy", category: "everyday", rule: "silent_letter" },
  { word: "careful", hint: "Paying close attention to avoid mistakes.", difficulty: "easy", category: "people" },
  { word: "kitchen", hint: "The room where meals are cooked.", difficulty: "easy", category: "home" },
  { word: "morning", hint: "The early part of the day.", difficulty: "easy", category: "everyday" },
  { word: "evening", hint: "The part of the day before night.", difficulty: "easy", category: "everyday" },
  { word: "holiday", hint: "A special day off from school or work.", difficulty: "easy", category: "everyday" },
  { word: "cousin", hint: "The child of your aunt or uncle.", difficulty: "easy", category: "people", rule: "vowel_confusion" },
  { word: "sister", hint: "A girl who shares your parents.", difficulty: "easy", category: "people" },
  { word: "brother", hint: "A boy who shares your parents.", difficulty: "easy", category: "people" },
  { word: "teacher", hint: "Someone who helps you learn at school.", difficulty: "easy", category: "school" },
  { word: "student", hint: "Someone who is learning at school.", difficulty: "easy", category: "school" },
  { word: "journey", hint: "A trip from one place to another.", difficulty: "easy", category: "everyday", rule: "vowel_confusion" },
  { word: "hungry", hint: "Feeling like you need to eat.", difficulty: "easy", category: "everyday" },
  { word: "thirsty", hint: "Feeling like you need a drink.", difficulty: "easy", category: "everyday" },
  { word: "thankful", hint: "Feeling grateful for something.", difficulty: "easy", category: "people" },
  { word: "birthday", hint: "The day each year that celebrates when you were born.", difficulty: "easy", category: "everyday" },

  // ---------- more medium words ----------
  { word: "remember", hint: "To keep something in your memory.", difficulty: "medium", category: "school" },
  { word: "alphabet", hint: "The set of letters used to write a language.", difficulty: "medium", category: "school" },
  { word: "computer", hint: "A machine used to write, browse, and play games.", difficulty: "medium", category: "school" },
  { word: "continue", hint: "To keep doing something without stopping.", difficulty: "medium", category: "everyday" },
  { word: "decision", hint: "A choice you make after thinking it over.", difficulty: "medium", category: "everyday", rule: "tricky_ending" },
  { word: "exercise", hint: "Physical activity to stay healthy.", difficulty: "medium", category: "home", rule: "silent_letter" },
  { word: "furniture", hint: "Chairs, tables, and beds inside a home.", difficulty: "medium", category: "home", rule: "tricky_ending" },
  { word: "direction", hint: "The way you need to go to get somewhere.", difficulty: "medium", category: "everyday", rule: "tricky_ending" },
  { word: "character", hint: "A person in a story, or someone's personality.", difficulty: "medium", category: "school", rule: "silent_letter" },
  { word: "adventure", hint: "An exciting or unusual experience.", difficulty: "medium", category: "everyday" },
  { word: "chocolate", hint: "A sweet brown treat made from cacao.", difficulty: "medium", category: "food", rule: "silent_letter" },
  { word: "dangerous", hint: "Able to cause harm or injury.", difficulty: "medium", category: "everyday", rule: "tricky_ending" },
  { word: "difficult", hint: "Not easy to do or understand.", difficulty: "medium", category: "school" },
  { word: "vacation", hint: "A trip or break from school or work.", difficulty: "medium", category: "everyday" },
  { word: "mountain", hint: "A very tall, rocky landform.", difficulty: "medium", category: "nature", rule: "vowel_confusion" },
  { word: "thousand", hint: "The number 1,000.", difficulty: "medium", category: "everyday" },
  { word: "hospital", hint: "A place where sick or injured people are treated.", difficulty: "medium", category: "home" },

  // ---------- more hard words ----------
  { word: "dictionary", hint: "A book that lists words and their meanings.", difficulty: "hard", category: "school", rule: "tricky_ending" },
  { word: "temperature", hint: "How hot or cold something is.", difficulty: "hard", category: "nature", rule: "vowel_confusion" },
  { word: "disappear", hint: "To go out of sight suddenly.", difficulty: "hard", category: "everyday", rule: "double_consonant" },
  { word: "disappoint", hint: "To fail to meet someone's hopes.", difficulty: "hard", category: "people", rule: "double_consonant" },
  { word: "appreciate", hint: "To be grateful for something.", difficulty: "hard", category: "people", rule: "double_consonant" },
  { word: "communicate", hint: "To share information with someone.", difficulty: "hard", category: "everyday", rule: "double_consonant" },
  { word: "experience", hint: "Something you have lived through or done.", difficulty: "hard", category: "everyday", rule: "vowel_confusion" },
  { word: "imagination", hint: "The ability to picture things in your mind.", difficulty: "hard", category: "school" },
  { word: "information", hint: "Facts or details about something.", difficulty: "hard", category: "school", rule: "tricky_ending" },
  { word: "personality", hint: "The set of traits that make someone who they are.", difficulty: "hard", category: "people" },
  { word: "professional", hint: "Relating to a paid, skilled job.", difficulty: "hard", category: "school", rule: "double_consonant" },
  { word: "unfortunately", hint: "Used to say something unlucky happened.", difficulty: "hard", category: "everyday" },
  { word: "responsibility", hint: "A duty you are expected to handle.", difficulty: "hard", category: "everyday", rule: "tricky_ending" },
  { word: "extraordinary", hint: "Very unusual or remarkable.", difficulty: "hard", category: "everyday", rule: "vowel_confusion" },
  { word: "conscience", hint: "The inner sense of right and wrong.", difficulty: "hard", category: "people", rule: "silent_letter" },

  // ---------- more expert words ----------
  { word: "pronunciation", hint: "The way a word is spoken aloud.", difficulty: "expert", category: "school", rule: "tricky_ending" },
  { word: "miscellaneous", hint: "Made up of many different, unrelated things.", difficulty: "expert", category: "everyday", rule: "vowel_confusion" },
  { word: "unprecedented", hint: "Never having happened before.", difficulty: "expert", category: "school" },
  { word: "indispensable", hint: "So important that you cannot do without it.", difficulty: "expert", category: "everyday", rule: "tricky_ending" },
  { word: "subconscious", hint: "Part of the mind you're not actively aware of.", difficulty: "expert", category: "people", rule: "silent_letter" },
  { word: "exaggerate", hint: "To describe something as bigger than it really is.", difficulty: "expert", category: "everyday", rule: "double_consonant" },
  { word: "maintenance", hint: "The work of keeping something in good condition.", difficulty: "expert", category: "everyday", rule: "tricky_ending" },
  { word: "questionable", hint: "Doubtful or open to suspicion.", difficulty: "expert", category: "everyday" },
  { word: "perseverance", hint: "Continued effort despite difficulty.", difficulty: "expert", category: "people" },
  { word: "vulnerable", hint: "Easily hurt or exposed to harm.", difficulty: "expert", category: "people", rule: "vowel_confusion" },

  // ---------- US/UK spelling-variant pairs (spelled American by default) ----------
  { word: "color", hint: "Red, blue, green, or any shade like them.", difficulty: "easy", category: "everyday", variants: { uk: "colour" } },
  { word: "honor", hint: "Great respect, or to keep a promise.", difficulty: "easy", category: "people", variants: { uk: "honour" } },
  { word: "flavor", hint: "The taste of a food or drink.", difficulty: "easy", category: "food", variants: { uk: "flavour" } },
  { word: "humor", hint: "The quality of being funny.", difficulty: "easy", category: "people", variants: { uk: "humour" } },
  { word: "labor", hint: "Hard work.", difficulty: "easy", category: "everyday", variants: { uk: "labour" } },
  { word: "rumor", hint: "A piece of unconfirmed gossip.", difficulty: "medium", category: "people", variants: { uk: "rumour" } },
  { word: "harbor", hint: "A sheltered place where ships dock.", difficulty: "medium", category: "nature", variants: { uk: "harbour" } },
  { word: "vapor", hint: "A cloud-like gas, like steam.", difficulty: "medium", category: "nature", variants: { uk: "vapour" } },
  { word: "center", hint: "The middle point of something.", difficulty: "easy", category: "everyday", variants: { uk: "centre" } },
  { word: "theater", hint: "A place where you watch plays or movies.", difficulty: "medium", category: "everyday", variants: { uk: "theatre" } },
  { word: "meter", hint: "A unit used to measure length.", difficulty: "easy", category: "school", variants: { uk: "metre" } },
  { word: "liter", hint: "A unit used to measure liquid.", difficulty: "easy", category: "everyday", variants: { uk: "litre" } },
  { word: "fiber", hint: "A thin thread, or part of food that aids digestion.", difficulty: "medium", category: "food", variants: { uk: "fibre" } },
  { word: "organize", hint: "To arrange things in a neat, orderly way.", difficulty: "medium", category: "school", variants: { uk: "organise" } },
  { word: "realize", hint: "To suddenly understand something.", difficulty: "medium", category: "everyday", variants: { uk: "realise" } },
  { word: "recognize", hint: "To know someone or something you've seen before.", difficulty: "hard", category: "school", variants: { uk: "recognise" } },
  { word: "apologize", hint: "To say sorry for a mistake.", difficulty: "medium", category: "people", variants: { uk: "apologise" } },
  { word: "memorize", hint: "To learn something so well you know it by heart.", difficulty: "medium", category: "school", variants: { uk: "memorise" } },
  { word: "catalog", hint: "A list of items you can look through or order from.", difficulty: "medium", category: "school", variants: { uk: "catalogue" } },
  { word: "dialog", hint: "A conversation between two or more people.", difficulty: "medium", category: "school", variants: { uk: "dialogue" } },
  { word: "defense", hint: "Protection against attack or harm.", difficulty: "medium", category: "everyday", variants: { uk: "defence" } },
  { word: "license", hint: "Official permission to do something, like drive.", difficulty: "medium", category: "everyday", variants: { uk: "licence" } },
  { word: "traveling", hint: "Going from one place to another.", difficulty: "medium", category: "everyday", rule: "double_consonant", variants: { uk: "travelling" } },
  { word: "canceled", hint: "Called off; not going to happen anymore.", difficulty: "medium", category: "everyday", rule: "double_consonant", variants: { uk: "cancelled" } },
  { word: "gray", hint: "A color between black and white.", difficulty: "beginner", category: "everyday", variants: { uk: "grey" } },
  { word: "pajamas", hint: "Comfortable clothes you wear to sleep.", difficulty: "easy", category: "home", variants: { uk: "pyjamas" } },
  { word: "mustache", hint: "Hair grown above the upper lip.", difficulty: "medium", category: "people", variants: { uk: "moustache" } },
  { word: "fulfill", hint: "To carry out a promise or duty.", difficulty: "medium", category: "everyday", rule: "double_consonant", variants: { uk: "fulfil" } },

  // ---------- expansion: more Hard-level vocabulary ----------
  { word: "achievement", hint: "Something done successfully after effort.", difficulty: "hard", category: "school", rule: "ie_ei" },
  { word: "committee", hint: "A group chosen to decide something together.", difficulty: "hard", category: "school", rule: "double_consonant" },
  { word: "conscious", hint: "Awake and aware of what is happening.", difficulty: "hard", category: "people", rule: "silent_letter" },
  { word: "existence", hint: "The state of being real or alive.", difficulty: "hard", category: "everyday", rule: "tricky_ending" },
  { word: "independent", hint: "Not needing help from anyone else.", difficulty: "hard", category: "people" },
  { word: "occurrence", hint: "Something that happens or takes place.", difficulty: "hard", category: "everyday", rule: "double_consonant" },
  { word: "parallel", hint: "Two lines that stay the same distance apart.", difficulty: "hard", category: "school", rule: "double_consonant" },
  { word: "possession", hint: "Something you own.", difficulty: "hard", category: "everyday", rule: "double_consonant" },
  { word: "privilege", hint: "A special right given to some but not all.", difficulty: "hard", category: "people", rule: "vowel_confusion" },
  { word: "recommend", hint: "To suggest that someone try something you liked.", difficulty: "hard", category: "everyday", rule: "double_consonant" },
  { word: "sincerely", hint: "In a way you truly mean it.", difficulty: "hard", category: "people", rule: "tricky_ending" },
  { word: "cemetery", hint: "A place where people are buried.", difficulty: "hard", category: "everyday", rule: "vowel_confusion" },
  { word: "handkerchief", hint: "A small square of cloth for wiping the nose.", difficulty: "hard", category: "home", rule: "silent_letter" },
  { word: "sacrilege", hint: "An insult to something people hold sacred.", difficulty: "hard", category: "school", rule: "vowel_confusion" },
  { word: "yacht", hint: "A sleek boat used for pleasure sailing.", difficulty: "hard", category: "everyday", rule: "silent_letter" },
  { word: "colonel", hint: "A senior officer in the army, said like 'kernel'.", difficulty: "hard", category: "people", rule: "silent_letter" },

  // ---------- expansion: more Expert-level vocabulary ----------
  { word: "accommodate", hint: "To make room for or fit in with someone.", difficulty: "expert", category: "everyday", rule: "double_consonant" },
  { word: "acquiesce", hint: "To quietly agree without protest.", difficulty: "expert", category: "people", rule: "silent_letter" },
  { word: "liaison", hint: "A person who connects two groups.", difficulty: "expert", category: "people", rule: "vowel_confusion" },
  { word: "reminiscence", hint: "A memory brought back to mind.", difficulty: "expert", category: "people", rule: "tricky_ending" },
  { word: "renaissance", hint: "A fresh burst of interest in art and learning.", difficulty: "expert", category: "school", rule: "double_consonant" },
  { word: "sovereignty", hint: "The power of a country to rule itself.", difficulty: "expert", category: "school", rule: "silent_letter" },
  { word: "surreptitious", hint: "Done quietly so no one notices.", difficulty: "expert", category: "people", rule: "tricky_ending" },
  { word: "unanimous", hint: "Agreed on by every single person.", difficulty: "expert", category: "people", rule: "vowel_confusion" },
  { word: "vengeance", hint: "Getting back at someone for a wrong done.", difficulty: "expert", category: "people", rule: "tricky_ending" },
  { word: "whimsical", hint: "Playful and a little unpredictable.", difficulty: "expert", category: "people", rule: "silent_letter" },
  { word: "camaraderie", hint: "The warm bond among people who share time together.", difficulty: "expert", category: "people", rule: "vowel_confusion" },
  { word: "gauge", hint: "A tool that measures pressure or level.", difficulty: "expert", category: "school", rule: "vowel_confusion" },
  { word: "inoculate", hint: "To give a vaccine that protects from a disease.", difficulty: "expert", category: "school", rule: "vowel_confusion" },
  { word: "juxtapose", hint: "To place two things side by side to compare them.", difficulty: "expert", category: "school", rule: "tricky_ending" },
  { word: "labyrinth", hint: "A confusing maze of paths.", difficulty: "expert", category: "school", rule: "silent_letter" },
  { word: "mnemonic", hint: "A trick that helps you remember something.", difficulty: "expert", category: "school", rule: "silent_letter" },
  { word: "paraphernalia", hint: "The collection of small items used for an activity.", difficulty: "expert", category: "everyday", rule: "silent_letter" },
  { word: "pharaoh", hint: "An ancient Egyptian ruler.", difficulty: "expert", category: "school", rule: "silent_letter" },
  { word: "supersede", hint: "To take the place of something older.", difficulty: "expert", category: "school", rule: "tricky_ending" },
  { word: "cinnamon", hint: "A warm brown spice made from tree bark.", difficulty: "hard", category: "food", rule: "double_consonant" },
  { word: "physician", hint: "A doctor trained to treat illness.", difficulty: "hard", category: "people", rule: "silent_letter" },
  { word: "resemblance", hint: "The way one thing looks like another.", difficulty: "hard", category: "people", rule: "tricky_ending" },
  { word: "trustworthy", hint: "Deserving trust and confidence.", difficulty: "hard", category: "people" },
  { word: "prestigious", hint: "Widely respected and held in high regard.", difficulty: "expert", category: "people", rule: "tricky_ending" }
];

const WORD_CATEGORIES = [
  { value: "all", label: "All" },
  { value: "everyday", label: "Everyday" },
  { value: "people", label: "People" },
  { value: "school", label: "School" },
  { value: "nature", label: "Nature" },
  { value: "food", label: "Food" },
  { value: "home", label: "Home" },
];

// Short, proactive tips shown before a word that fits a known tricky spelling pattern.
const RULE_TIPS = {
  ie_ei: "Tricky i/e pattern — “i before e, except after c”... though this word might be an exception.",
  double_consonant: "This word doubles a letter in the middle — say it slowly and picture both of them.",
  silent_letter: "Watch out — this word has a silent letter that isn't pronounced at all.",
  tricky_ending: "The ending isn't spelled the way it sounds — it's worth memorizing as one chunk.",
  vowel_confusion: "Easy to mix up the vowels here — look closely at each one before you start.",
};

// Human-readable labels for each rule, used on the "weak patterns" history view.
const RULE_LABELS = {
  ie_ei: "I/E confusion",
  double_consonant: "Double letters",
  silent_letter: "Silent letters",
  tricky_ending: "Tricky endings",
  vowel_confusion: "Vowel mix-ups",
};

// Three short example sentences per built-in word, shown on the study card so the
// learner can read each word in context. Kept apart from WORD_LIST on purpose:
// saved entries are checked against a fixed list of keys when a backup is imported.
// "{word}" is replaced with the word as spelled for the learner's style (US/UK), so
// sentences must not contain any other US-only spelling (color, neighbor, center...).
const WORD_EXAMPLES = {
  // ---------- beginner ----------
  cat: ["The {word} curled up on the warm sofa.", "My {word} likes to chase a ball of yarn.", "A black {word} crossed the garden wall."],
  dog: ["The {word} wagged its tail when I came home.", "We take our {word} for a walk every evening.", "A friendly {word} ran up to say hello."],
  sun: ["The {word} rises in the east every morning.", "Put on a hat when the {word} is strong.", "We watched the {word} set behind the hills."],
  run: ["I {word} to the bus stop every morning.", "Dogs love to {word} across an open field.", "Can you {word} as fast as your brother?"],
  jump: ["The kids {word} over the puddle.", "Frogs can {word} much farther than they can walk.", "Take a deep breath before you {word} into the pool."],
  frog: ["A green {word} sat on the lily pad.", "The {word} hopped into the pond with a splash.", "At night we heard a {word} croaking by the stream."],
  milk: ["I pour {word} on my cereal each morning.", "The farmer gets {word} from the cows at dawn.", "She drank a warm glass of {word} before bed."],
  book: ["I borrowed a funny {word} from the library.", "Please open your {word} to page ten.", "My mother reads me a {word} at bedtime."],
  happy: ["The children were {word} to see the snow.", "A warm hug made her feel {word}.", "He was so {word} that he started to sing."],
  apple: ["She packed a red {word} in her lunch box.", "An {word} a day is a healthy snack.", "We picked an {word} straight from the tree."],
  house: ["Their {word} has a blue door and a small garden.", "We painted the {word} white last summer.", "Come to my {word} after school."],
  water: ["Drink plenty of {word} on a hot day.", "The {word} in the lake was cold and clear.", "Please {word} the plants before you leave."],
  green: ["Grass turns {word} in the spring.", "She wore a {word} scarf to school.", "Wait until the light turns {word} before you cross."],
  smile: ["Her {word} made everyone feel welcome.", "I couldn't help but {word} at the joke.", "Give the camera a big {word}."],
  chair: ["Please pull up a {word} and sit with us.", "The cat sleeps on the old wooden {word}.", "He pushed his {word} back from the desk."],

  // ---------- everyday words ----------
  because: ["I took an umbrella {word} it was raining.", "She smiled {word} she had passed her test.", "We stayed inside {word} the storm was loud."],
  friend: ["My best {word} lives next door.", "A good {word} listens when you are sad.", "I made a new {word} on my first day at school."],
  believe: ["I {word} that you can do it.", "Do you {word} in ghosts?", "It was hard to {word} how fast the year had gone."],
  separate: ["Please {word} the red socks from the white ones.", "The twins sleep in {word} rooms.", "After the show, we went our {word} ways."],
  definitely: ["I will {word} come to your party.", "That was {word} the best pizza I've ever had.", "She is {word} going to win the race."],
  necessary: ["It is {word} to wear a helmet when you ride a bike.", "Bring only what is {word} for the trip.", "Is it {word} to finish this tonight?"],
  receive: ["I hope to {word} a letter from my pen pal.", "You will {word} a certificate when you finish the course.", "We {word} the newspaper every morning."],
  though: ["I went outside, even {word} it was cold.", "It looked easy, {word} it was actually hard.", "He kept running, {word} he was tired."],
  beautiful: ["The sunset over the sea was {word}.", "She sang a {word} song at the concert.", "What a {word} garden you have!"],
  science: ["We did a fun experiment in {word} class today.", "She wants to study {word} when she grows up.", "{word} helps us understand how the world works."],
  people: ["Many {word} came to watch the parade.", "Kind {word} help each other.", "How many {word} are coming to dinner?"],
  different: ["My sister and I like {word} kinds of music.", "This road leads to a {word} town.", "Every snowflake looks {word}."],
  favorite: ["Blue is my {word} shade of paint.", "What is your {word} food?", "This song is her {word}."],
  weird: ["I had a {word} dream about flying fish.", "It felt {word} to be back in my old school.", "That is the {word}est hat I have ever seen."],
  environment: ["We should all help protect the {word}.", "Planting trees is good for the {word}.", "Pollution harms the {word} and the animals in it."],
  government: ["The {word} makes the laws of a country.", "Our class visited the {word} building in the capital.", "Leaders of the {word} met to talk about new schools."],
  restaurant: ["We ate dinner at a small Italian {word}.", "The {word} was full, so we had to wait for a table.", "She works as a chef in a busy {word}."],
  calendar: ["I marked my birthday on the {word}.", "Check the {word} to see when the game is.", "The {word} on the wall shows a different animal each month."],
  vacuum: ["Dad used the {word} to clean the carpet.", "Space is almost a perfect {word}, with no air at all.", "Please {word} the living room before our guests arrive."],
  rhythm: ["The drummer kept a steady {word}.", "We clapped along to the {word} of the song.", "She tapped her foot to the {word}."],
  language: ["Spanish is the {word} they speak at home.", "She is learning a new {word} at school.", "Body {word} can say a lot without any words."],
  surprise: ["The party was a big {word} for her.", "He couldn't hide his {word} when he saw the gift.", "We planned to {word} Grandma with a visit."],
  immediately: ["Please come here {word}.", "When the bell rang, we lined up {word}.", "She answered the phone {word}."],
  occasion: ["A birthday is a special {word}.", "I wore my best dress for the {word}.", "On one {word}, we saw a whale from the shore."],
  embarrass: ["Please don't {word} me in front of my friends.", "Tripping on stage could {word} anyone.", "He didn't mean to {word} her with that question."],
  knowledge: ["Reading gives you a lot of {word}.", "Her {word} of birds is amazing.", "To my {word}, the shop is closed on Sundays."],
  guarantee: ["The store will {word} that you are happy with it.", "I can't {word} it won't rain, but I hope not.", "This watch comes with a two-year {word}."],
  mischievous: ["The {word} puppy chewed my slipper.", "He had a {word} grin on his face.", "My {word} little brother hid my shoes."],
  neighbor: ["Our {word} waters our plants when we are away.", "I said hello to my {word} over the fence.", "A kind {word} helped carry the shopping."],
  achieve: ["With hard work, you can {word} your goals.", "She wants to {word} a perfect score on the test.", "What do you hope to {word} this year?"],
  although: ["{word} it was raining, we went to the park.", "I enjoyed the movie, {word} it was a bit long.", "She kept smiling {word} she was tired."],
  business: ["His family runs a small {word} that sells bread.", "She wants to start her own {word} one day.", "The shop does good {word} on weekends."],
  column: ["Write the answers in the first {word} of the table.", "A tall stone {word} held up the roof.", "He reads the sports {word} in the newspaper."],
  foreign: ["She loves learning a {word} language.", "We flew to a {word} country for the holidays.", "The shop sells {word} stamps and coins."],
  grateful: ["I am {word} for all your help.", "She felt {word} when the stranger returned her bag.", "We are {word} for the warm meal."],
  height: ["The {word} of the tree surprised us.", "They measured her {word} against the door frame.", "The plane flew at a great {word}."],
  island: ["We sailed to a tiny {word} in the middle of the sea.", "Palm trees grew all over the {word}.", "You can only reach the {word} by boat."],
  jewelry: ["She keeps her {word} in a small wooden box.", "The shop sells silver {word}.", "Grandma wore her best {word} to the wedding."],
  library: ["I returned my books to the {word} today.", "It is very quiet in the {word}.", "The {word} has a corner just for comics."],
  medicine: ["The doctor gave me {word} for my cough.", "Take your {word} after you eat.", "She studies {word} because she wants to be a nurse."],
  opposite: ["Hot is the {word} of cold.", "The bank is {word} the post office.", "They sat on {word} sides of the table."],
  possible: ["Is it {word} to finish before dinner?", "Please call me as soon as {word}.", "Anything is {word} if you keep trying."],
  question: ["May I ask a {word} about the homework?", "She raised her hand to answer the {word}.", "That is a very good {word}."],
  rhyme: ["Cat and hat {word} with each other.", "We learned a funny {word} about a spider.", "Can you think of a word that will {word} with moon?"],
  schedule: ["Our class {word} has art on Tuesdays.", "The train is running on {word}.", "Let's {word} a time to meet next week."],
  tomorrow: ["We are going to the zoo {word}.", "I will finish my project {word}.", "{word} is a brand-new day."],
  umbrella: ["Take your {word}, because it looks like rain.", "She held a bright yellow {word} over her head.", "The wind turned my {word} inside out."],
  vegetable: ["Carrot is my best-loved {word}.", "Try to eat a {word} with every dinner.", "Grandma grows a different {word} in each row of the garden."],
  weather: ["The {word} was sunny all week.", "What is the {word} like today?", "Check the {word} before you pack."],

  // ---------- expert ----------
  conscientious: ["She is a {word} student who always checks her work.", "A {word} nurse double-checks every dose.", "He was so {word} that he never missed a deadline."],
  onomatopoeia: ["\"Buzz\" and \"splash\" are examples of {word}.", "Comic books use {word} like \"boom\" and \"pow\".", "Our teacher asked us to find the {word} in the poem."],
  bureaucracy: ["Getting a permit meant dealing with a lot of {word}.", "The {word} slowed down the new project.", "Too much {word} can make simple tasks take weeks."],
  questionnaire: ["Please fill in the {word} before you leave.", "The {word} had ten short questions about school lunch.", "She mailed back the {word} the next day."],
  entrepreneur: ["The young {word} started a company in her garage.", "An {word} takes risks to build something new.", "He dreams of becoming a successful {word}."],
  chrysanthemum: ["A yellow {word} bloomed by the gate.", "She put a {word} in a vase on the table.", "In autumn, the {word} garden is full of bright petals."],
  idiosyncrasy: ["Humming while he works is just his latest {word}.", "Everyone has some small {word} that makes them unique.", "Her odd {word} of eating cake before dinner made us laugh."],
  connoisseur: ["He is a {word} of fine chocolate.", "The {word} tasted the wine and described its taste.", "My uncle is a coffee {word} who can name every bean."],
  camouflage: ["The chameleon uses {word} to hide from birds.", "Soldiers wore {word} to blend into the forest.", "The moth's wings are perfect {word} against the tree bark."],
  silhouette: ["We saw the {word} of a tree against the evening sky.", "Her {word} appeared on the curtain.", "The artist cut a paper {word} of my face."],
  rhinoceros: ["A {word} has thick skin and a horn on its nose.", "We saw a huge {word} at the wildlife park.", "The baby {word} stayed close to its mother."],
  acquaintance: ["He is just an {word}, not a close friend.", "I met an old {word} on the train.", "She introduced me to an {word} from her book club."],
  millennium: ["A {word} is a period of one thousand years.", "The year 2000 marked the start of a new {word}.", "People celebrated the new {word} with fireworks."],
  hierarchy: ["In the army, there is a strict {word} of ranks.", "A king sat at the top of the {word}.", "The {word} of the company has five levels."],
  phenomenon: ["A rainbow is a beautiful natural {word}.", "The northern lights are a rare {word}.", "Scientists tried to explain the strange {word}."],
  pneumonia: ["He stayed in the hospital because he had {word}.", "{word} is an illness that affects the lungs.", "Doctors treat {word} with rest and medicine."],
  cappuccino: ["She ordered a {word} with extra foam.", "Dad drinks a {word} every morning.", "The cafe is famous for its creamy {word}."],
  kaleidoscope: ["I turned the {word} and the patterns danced.", "Looking through a {word} is like seeing a tiny fireworks show.", "The garden was a {word} of flowers in every shade."],

  // ---------- more beginner ----------
  bird: ["A small {word} sang on the branch.", "The {word} built a nest in our tree.", "We put out seeds for every hungry {word}."],
  fish: ["The {word} swam around the bowl.", "We caught a big {word} in the lake.", "Dad cooked {word} and rice for dinner."],
  tree: ["A tall {word} grows in our yard.", "The squirrel ran up the {word}.", "We sat in the shade of the old {word}."],
  star: ["I made a wish on the first {word} of the night.", "The {word} twinkled in the dark sky.", "She drew a gold {word} on my paper."],
  moon: ["The {word} was big and bright last night.", "Astronauts have walked on the {word}.", "We watched the {word} rise over the trees."],
  ball: ["He kicked the {word} across the field.", "The dog brought the {word} back to me.", "She bounced the {word} three times."],
  cake: ["We baked a chocolate {word} for her birthday.", "Please cut me a slice of {word}.", "The {word} had candles on top."],
  bike: ["I ride my {word} to school.", "He pumped air into the soft wheel of his {word}.", "She learned to ride a {word} last summer."],
  rain: ["We stayed inside because of the heavy {word}.", "The {word} tapped on the window all night.", "Please bring a coat in case of {word}."],
  snow: ["The kids built a man out of {word}.", "{word} covered the roof and the road.", "I love to watch the {word} fall."],
  shoe: ["I can't find my other {word}.", "She tied the lace on her {word}.", "A small stone got stuck in my {word}."],
  hand: ["Raise your {word} if you know the answer.", "She held her little brother's {word}.", "Please wash your {word} before you eat."],
  door: ["Please close the {word} behind you.", "Someone knocked on the front {word}.", "The {word} creaked as it opened."],
  desk: ["She keeps her pencils in a drawer of her {word}.", "My {word} is next to the window.", "He left his bag under the {word}."],
  lamp: ["Turn on the {word} so you can read.", "A small {word} sat on the table by my bed.", "The {word} lit up the whole room."],
  picture: ["She drew a {word} of her family.", "That {word} on the wall is very old.", "Let's take a {word} together."],
  another: ["May I have {word} slice of pizza?", "She read {word} chapter before bed.", "Let's try {word} way to solve it."],
  thought: ["I {word} about you on my birthday.", "A good {word} popped into her head.", "He {word} the test would be harder."],
  through: ["We walked {word} the forest.", "The train went {word} a long tunnel.", "She looked {word} the window."],
  careful: ["Be {word} when you cross the road.", "The {word} boy carried the glass slowly.", "She was {word} not to spill the milk."],
  kitchen: ["Dad is cooking dinner in the {word}.", "The {word} smells like fresh bread.", "We eat breakfast at the {word} table."],
  morning: ["I brush my teeth every {word}.", "The birds sing early in the {word}.", "Good {word}, everyone!"],
  evening: ["We take a walk every {word}.", "The sky turns orange in the {word}.", "She reads a story in the {word}."],
  holiday: ["We went to the beach for our {word}.", "The {word} lasts for two weeks.", "Schools are closed on a public {word}."],
  cousin: ["My {word} lives in another city.", "I played games with my {word} at the party.", "Her {word} is the same age as me."],
  sister: ["My little {word} loves to draw.", "She shares a room with her {word}.", "I help my {word} with her homework."],
  brother: ["My big {word} taught me to swim.", "He plays soccer with his {word}.", "I gave my {word} half of my sandwich."],
  teacher: ["Our {word} reads us a story after lunch.", "She wants to become a {word}.", "I gave my {word} a card on her birthday."],
  student: ["Every {word} got a new notebook.", "The new {word} sat next to me.", "A good {word} asks questions."],
  journey: ["The {word} to the mountains took all day.", "We packed snacks for the long {word}.", "Their {word} began at sunrise."],
  hungry: ["I am so {word} that I could eat a whole pizza.", "The {word} puppy ate everything in its bowl.", "Don't go to the shop when you are {word}."],
  thirsty: ["I felt {word} after the long run.", "The {word} horse drank from the stream.", "Bring water if you get {word}."],
  thankful: ["I am {word} for my family.", "She was {word} for the warm coat.", "We feel {word} when people are kind."],
  birthday: ["Today is my {word}.", "We sang a song at her {word} party.", "He got a new bike for his {word}."],
  remember: ["Please {word} to lock the door.", "Do you {word} the name of that song?", "I always {word} my first day of school."],
  alphabet: ["The {word} has twenty-six letters.", "We sang the {word} song in class.", "She can say the {word} backwards."],
  computer: ["I wrote my story on the {word}.", "Dad uses a {word} at work.", "The {word} switched on with a soft hum."],
  continue: ["Please {word} reading from page five.", "The rain will {word} all afternoon.", "Let's {word} the game after lunch."],
  decision: ["It was a hard {word} to make.", "We made the {word} together.", "She is happy with her {word}."],
  exercise: ["Daily {word} keeps your body strong.", "We do an {word} before class begins.", "Please {word} for twenty minutes."],
  furniture: ["We bought new {word} for the living room.", "The {word} was moved to make space.", "Dad polished the wooden {word}."],
  direction: ["Which {word} should we walk in?", "The wind changed {word} during the night.", "She asked for {word} to the station."],
  character: ["My best-loved {word} in the book is a brave mouse.", "He has a kind and honest {word}.", "The play has one funny {word}."],
  adventure: ["Our camping trip was a big {word}.", "She loves books about {word} on the sea.", "Let's go on an {word} through the woods."],
  chocolate: ["She ate a piece of dark {word}.", "We made hot {word} on a cold day.", "The cake was covered in melted {word}."],
  dangerous: ["The path by the cliff is {word}.", "It is {word} to swim in the storm.", "A lion can be a {word} animal."],
  difficult: ["The puzzle was very {word}.", "It is {word} to learn a new language.", "She stayed calm in a {word} situation."],
  vacation: ["We are going on {word} in July.", "Our family spent the {word} at the lake.", "The best part of the {word} was the beach."],
  mountain: ["We climbed to the top of the {word}.", "Snow covers the {word} all year.", "A river runs down the {word}."],
  thousand: ["A {word} people came to the festival.", "The mountain is one {word} feet tall.", "She saved a {word} coins in a jar."],
  hospital: ["The nurse works at the {word}.", "He went to the {word} to visit his grandfather.", "A new {word} opened in our town."],
  dictionary: ["Look up the word in the {word}.", "She keeps a {word} on her desk.", "The {word} tells you what each word means."],
  temperature: ["The {word} dropped overnight.", "The doctor checked my {word}.", "What is the {word} outside today?"],
  disappear: ["The sun can {word} behind a cloud.", "Magicians make things {word}.", "The stain will {word} when you wash it."],
  disappoint: ["I didn't want to {word} my team.", "The bad weather might {word} the fans.", "She tried not to {word} her parents."],
  appreciate: ["I really {word} your help.", "We {word} a beautiful sunset.", "She will {word} a thank-you note."],
  communicate: ["Bees {word} by dancing.", "We {word} with friends by phone.", "Good friends {word} clearly with each other."],
  experience: ["Riding a horse was a new {word} for me.", "She has a lot of {word} as a pilot.", "It was a fun {word} we will not forget."],
  imagination: ["She has a wild {word}.", "Use your {word} to invent a new game.", "The story came from his {word}."],
  information: ["The sign gives {word} about the train.", "I need more {word} before I decide.", "She found useful {word} in the library."],
  personality: ["He has a warm and funny {word}.", "Each of my friends has a different {word}.", "Her cheerful {word} lit up the room."],
  professional: ["He is a {word} soccer player.", "She did a {word} job painting the house.", "We hired a {word} photographer."],
  unfortunately: ["{word}, we missed the bus.", "I wanted to come, but {word} I was sick.", "{word}, the shop was closed."],
  responsibility: ["Feeding the dog is my {word}.", "She takes her {word} seriously.", "With age comes more {word}."],
  extraordinary: ["She has an {word} talent for music.", "It was an {word} view from the top.", "He did something {word} to save the day."],
  conscience: ["His {word} told him to tell the truth.", "She had a clear {word}.", "Listen to your {word} when you have a hard choice."],
  pronunciation: ["Her French {word} is very good.", "Check the {word} of a word in the dictionary.", "Work on your {word} by saying the word slowly."],
  miscellaneous: ["The box held {word} items like pens and tape.", "Put the {word} things in the drawer.", "She listed some {word} costs at the end."],
  unprecedented: ["The storm caused {word} damage.", "It was an {word} event in our town's history.", "The company saw {word} growth this year."],
  indispensable: ["A map is {word} on a long hike.", "She is an {word} member of the team.", "Water is {word} for all living things."],
  subconscious: ["Dreams can come from the {word} mind.", "He had a {word} fear of dogs.", "Your {word} notices things before you do."],
  exaggerate: ["Don't {word} when you tell the story.", "He likes to {word} how big the fish was.", "It's hard not to {word} when you are excited."],
  maintenance: ["The car needs regular {word}.", "The {word} crew fixed the broken light.", "Good {word} keeps the bike running smoothly."],
  questionable: ["That is a {word} idea.", "His reason sounded {word}.", "The shop had {word} prices."],
  perseverance: ["Her {word} helped her finish the race.", "It takes {word} to learn the piano.", "He showed great {word} after many tries."],
  vulnerable: ["A baby bird is {word} to cats.", "The old bridge is {word} to floods.", "She felt {word} on her first day."],

  // ---------- US / UK spelling pairs ----------
  color: ["Red is the {word} of a ripe tomato.", "What {word} is your bike?", "The artist chose a bold {word} for the wall."],
  honor: ["It is an {word} to meet you.", "She received an award in {word} of her work.", "We stood up to {word} the old soldier."],
  flavor: ["Vanilla is a popular ice cream {word}.", "The soup needs more {word}.", "Which {word} of juice do you want?"],
  humor: ["She has a great sense of {word}.", "His {word} made everyone laugh.", "The movie was full of {word}."],
  labor: ["Building the wall took a lot of hard {word}.", "{word} Day is a holiday in September.", "The workers earned a fair wage for their {word}."],
  rumor: ["There is a {word} that school will close early.", "Don't spread a {word} you aren't sure about.", "I heard a {word} about a new park."],
  harbor: ["Boats are tied up in the {word}.", "The ship sailed into the {word} at dawn.", "We watched the fishermen in the {word}."],
  vapor: ["Steam is water in the form of {word}.", "A cloud of {word} rose from the kettle.", "The mirror fogged up from the {word}."],
  center: ["The {word} of the town has a clock tower.", "Put the vase in the {word} of the table.", "We went to the sports {word} after school."],
  theater: ["We watched a play at the {word}.", "The {word} was full on opening night.", "She wants to act in the {word} one day."],
  meter: ["The race track is one {word} long.", "He ran every {word} of the race.", "A {word} is a little more than three feet."],
  liter: ["Please buy a {word} of milk.", "The bottle holds one {word} of water.", "A {word} is bigger than a cup."],
  fiber: ["Beans are a good source of {word}.", "A {word} of cotton is soft and thin.", "The rope is made from natural {word}."],
  organize: ["Please {word} your books on the shelf.", "We will {word} a surprise party for Dad.", "She likes to {word} her pencils by size."],
  realize: ["I didn't {word} it was so late.", "You will {word} how easy it is.", "He started to {word} he had left his bag."],
  recognize: ["I did not {word} you with short hair.", "Can you {word} this song?", "Dogs can {word} their owners by smell."],
  apologize: ["I need to {word} for being late.", "She wanted to {word} to her friend.", "It is polite to {word} when you make a mistake."],
  memorize: ["We need to {word} the poem for tomorrow.", "She can {word} a whole page in an hour.", "It helps to {word} a phone number."],
  catalog: ["We looked through the toy {word}.", "The library has an online {word}.", "The museum will {word} every old painting."],
  dialog: ["The {word} between the two characters was funny.", "A box popped up and started a {word} on the screen.", "Read the {word} out loud with a partner."],
  defense: ["The team has a strong {word}.", "She spoke in {word} of her friend.", "A thick wall is a good {word} against the wind."],
  license: ["You need a {word} to drive a car.", "Dad showed his driver's {word}.", "The shop has a {word} to sell fish."],
  traveling: ["We are {word} to Spain next week.", "She loves {word} by train.", "He has been {word} for a month."],
  canceled: ["The game was {word} because of rain.", "She {word} her trip when she got sick.", "The concert was {word} at the last minute."],
  gray: ["The sky was {word} before the storm.", "He wore a {word} sweater.", "My grandmother has soft {word} hair."],
  pajamas: ["I put on my {word} and went to bed.", "She wore her warm {word} all morning.", "His {word} have stars on them."],
  mustache: ["Grandpa has a thick white {word}.", "He drew a {word} on the poster.", "The magician wore a curly {word}."],
  fulfill: ["She worked hard to {word} her dream.", "I will {word} my promise to you.", "The new library will {word} the town's needs."],

  // ---------- hard ----------
  achievement: ["Finishing the marathon was a great {word}.", "She was proud of her {word} in math.", "The prize celebrates a lifetime {word}."],
  committee: ["A {word} will plan the school fair.", "She joined the {word} to help the park.", "The {word} met on Tuesday to vote."],
  conscious: ["He stayed {word} during the whole trip.", "She was {word} of the noise behind her.", "We try to be {word} about saving water."],
  existence: ["Scientists proved the {word} of a new planet.", "She didn't know about its {word}.", "A small pond is the whole {word} for those fish."],
  independent: ["She is {word} and does her own homework.", "The country became {word} in 1947.", "He wants to be {word} and live on his own."],
  occurrence: ["Rain is a rare {word} in the desert.", "A snowstorm is a common {word} here in winter.", "The strange {word} surprised everyone."],
  parallel: ["The two roads run {word} to each other.", "Draw two {word} lines on your paper.", "Their stories follow a {word} path."],
  possession: ["The old watch is her most prized {word}.", "He was caught in {word} of the lost keys.", "Please keep every {word} with you at all times."],
  privilege: ["It is a {word} to speak to you today.", "Staying up late is a {word} for older kids.", "She felt it was a {word} to help."],
  recommend: ["I {word} this book to everyone.", "Can you {word} a good restaurant?", "The doctor will {word} rest and fluids."],
  sincerely: ["She thanked him {word}.", "I {word} hope you feel better soon.", "Yours {word}, Sam."],
  cemetery: ["The old {word} is quiet and peaceful.", "Flowers were placed at the {word} gate.", "The {word} sits on a hill outside the town."],
  handkerchief: ["He wiped his face with a clean {word}.", "Grandpa kept a {word} in his pocket.", "She waved a white {word} at the train."],
  sacrilege: ["Burning the old book felt like {word}.", "Some call it {word} to change the recipe.", "He thought it was {word} to laugh in the temple."],
  yacht: ["The {word} sailed past the lighthouse.", "They spent the summer on a white {word}.", "A luxury {word} floated near the shore."],
  colonel: ["The {word} gave orders to his soldiers.", "A {word} is a high-ranking officer.", "She saluted the {word} as he walked by."],
  accommodate: ["The hotel can {word} two hundred guests.", "We will try to {word} your request.", "Can you {word} another suitcase in the car?"],
  acquiesce: ["He chose to {word} rather than argue.", "She did not {word} to their demands.", "The board will {word} if the offer is fair."],
  liaison: ["She acts as a {word} between the two teams.", "The {word} officer explained the plan to us.", "A good {word} keeps both sides informed."],
  reminiscence: ["Grandpa shared a fond {word} of his youth.", "The old photo sparked a {word} about summer camp.", "Her {word} of school days made us laugh."],
  renaissance: ["The {word} was a time of great art and ideas in Europe.", "Italy was at the heart of the {word}.", "The town is enjoying a cultural {word}."],
  sovereignty: ["The country fought to protect its {word}.", "{word} means having full power to rule yourself.", "They declared their {word} in a speech."],
  surreptitious: ["She took a {word} glance at her watch.", "He gave a {word} wink across the room.", "The {word} look told us something was up."],
  unanimous: ["The vote was {word}.", "They reached a {word} decision.", "The class was {word} in choosing a pizza party."],
  vengeance: ["He swore {word} on those who hurt him.", "The villain sought {word} for his past.", "She refused to take {word}."],
  whimsical: ["The {word} garden had a tiny door.", "She had a {word} sense of fun.", "He drew a {word} cartoon of a flying pig."],

  // ---------- more expert ----------
  camaraderie: ["The {word} among the team made every game fun.", "There was great {word} on the camping trip.", "Soldiers often share a strong {word}."],
  gauge: ["Check the fuel {word} before you drive.", "A {word} shows how much pressure is in the pipe.", "We use a {word} to measure the rain."],
  inoculate: ["Doctors {word} children against measles.", "The nurse will {word} us at school.", "It is wise to {word} against the flu."],
  juxtapose: ["The artist likes to {word} light and dark.", "The film will {word} the old city with the new.", "Try to {word} the two poems to see how they differ."],
  labyrinth: ["The garden hedge formed a {word}.", "He got lost in the {word} of tunnels.", "The legend tells of a monster in a {word}."],
  mnemonic: ["A {word} can help you remember the planets.", "Use a {word} to learn the spelling.", "Our teacher taught us a funny {word}."],
  paraphernalia: ["The camping {word} filled the whole car.", "She packed her painting {word} into a box.", "The {word} for the party was piled by the door."],
  pharaoh: ["The {word} ruled ancient Egypt.", "A golden mask was found in the {word}'s tomb.", "The {word} built a great pyramid."],
  supersede: ["The new rules {word} the old ones.", "Newer phones {word} older models.", "This plan will {word} the earlier one."],
  cinnamon: ["Sprinkle {word} on your toast.", "The kitchen smelled of apples and {word}.", "She added a pinch of {word} to the oatmeal."],
  physician: ["The {word} checked my heart.", "She trained to be a {word}.", "Ask your {word} about the medicine."],
  resemblance: ["There is a strong {word} between the twins.", "The {word} between the two paintings is clear.", "She noticed the {word} to her grandmother."],
  trustworthy: ["A {word} friend keeps secrets.", "She is honest and {word}.", "We need a {word} person to guard the money."],
  prestigious: ["She won a {word} award for her work.", "He attends a {word} university.", "It is a {word} prize in science."]
};
