// Word list: from absolute-beginner sight words up to ultra-advanced vocabulary.
// Each entry: word (lowercase, letters a-z only, American spelling by default),
// hint, difficulty (beginner|easy|medium|hard|expert), category, an optional
// `rule` tag (key into RULE_TIPS), and an optional `variants` map (e.g.
// { uk: "colour" }) used when the learner's Spelling Style is set to British.
const WORD_LIST = [
  // ---------- beginner: first words, 3-5 letters, no tricky patterns ----------
  { word: "cat", hint: "A small pet that meows.", difficulty: "beginner", category: "nature" },
  { word: "dog", hint: "A pet that barks and wags its tail.", difficulty: "beginner", category: "nature" },
  { word: "sun", hint: "It shines in the sky in the daytime.", difficulty: "beginner", category: "nature" },
  { word: "run", hint: "To move fast on your feet.", difficulty: "beginner", category: "everyday" },
  { word: "jump", hint: "To push off the ground into the air.", difficulty: "beginner", category: "everyday" },
  { word: "frog", hint: "A small green animal that hops and swims.", difficulty: "beginner", category: "nature" },
  { word: "milk", hint: "A white drink that comes from cows.", difficulty: "beginner", category: "food" },
  { word: "book", hint: "You read this to learn a story.", difficulty: "beginner", category: "school" },
  { word: "happy", hint: "Feeling good and cheerful.", difficulty: "beginner", category: "people" },
  { word: "apple", hint: "A round fruit that can be red or green.", difficulty: "beginner", category: "food" },
  { word: "house", hint: "A building where people live.", difficulty: "beginner", category: "home" },
  { word: "water", hint: "You drink this when you're thirsty.", difficulty: "beginner", category: "everyday" },
  { word: "green", hint: "The color of grass.", difficulty: "beginner", category: "everyday" },
  { word: "smile", hint: "What your face does when you're happy.", difficulty: "beginner", category: "people" },
  { word: "chair", hint: "Furniture you sit on.", difficulty: "beginner", category: "home" },

  { word: "because", hint: "For the reason that.", difficulty: "easy", category: "everyday" },
  { word: "friend", hint: "Someone you like and trust.", difficulty: "easy", category: "people", rule: "ie_ei" },
  { word: "believe", hint: "To think something is true.", difficulty: "medium", category: "everyday", rule: "ie_ei" },
  { word: "separate", hint: "To divide or keep apart.", difficulty: "medium", category: "everyday", rule: "vowel_confusion" },
  { word: "definitely", hint: "Without any doubt.", difficulty: "hard", category: "everyday", rule: "tricky_ending" },
  { word: "necessary", hint: "Needed; required.", difficulty: "hard", category: "everyday", rule: "double_consonant" },
  { word: "receive", hint: "To get or be given something.", difficulty: "medium", category: "everyday", rule: "ie_ei" },
  { word: "though", hint: "Despite the fact that.", difficulty: "easy", category: "everyday", rule: "silent_letter" },
  { word: "beautiful", hint: "Very pleasing to look at.", difficulty: "medium", category: "everyday" },
  { word: "science", hint: "The study of the natural world.", difficulty: "medium", category: "school" },
  { word: "people", hint: "Human beings in general.", difficulty: "easy", category: "people" },
  { word: "different", hint: "Not the same as another.", difficulty: "medium", category: "everyday" },
  { word: "favorite", hint: "The one you like best.", difficulty: "medium", category: "everyday", variants: { uk: "favourite" } },
  { word: "weird", hint: "Strange or unusual.", difficulty: "easy", category: "everyday", rule: "ie_ei" },
  { word: "environment", hint: "The natural world around us.", difficulty: "hard", category: "nature" },
  { word: "government", hint: "The group that runs a country.", difficulty: "hard", category: "school" },
  { word: "restaurant", hint: "A place where you pay to eat a meal.", difficulty: "hard", category: "food", rule: "tricky_ending" },
  { word: "calendar", hint: "A chart showing days and months.", difficulty: "medium", category: "everyday", rule: "vowel_confusion" },
  { word: "vacuum", hint: "A machine that sucks up dust.", difficulty: "medium", category: "home", rule: "vowel_confusion" },
  { word: "rhythm", hint: "A regular repeated pattern of sound.", difficulty: "hard", category: "school", rule: "silent_letter" },
  { word: "language", hint: "The words a group of people use to talk.", difficulty: "medium", category: "school" },
  { word: "surprise", hint: "An unexpected event.", difficulty: "medium", category: "everyday", rule: "silent_letter" },
  { word: "immediately", hint: "Right away, with no delay.", difficulty: "hard", category: "everyday", rule: "double_consonant" },
  { word: "occasion", hint: "A special event or time.", difficulty: "medium", category: "everyday", rule: "double_consonant" },
  { word: "embarrass", hint: "To make someone feel shy or ashamed.", difficulty: "hard", category: "people", rule: "double_consonant" },
  { word: "knowledge", hint: "Facts and information you know.", difficulty: "medium", category: "school", rule: "silent_letter" },
  { word: "guarantee", hint: "A promise that something will happen.", difficulty: "hard", category: "everyday", rule: "tricky_ending" },
  { word: "mischievous", hint: "Playfully causing trouble.", difficulty: "hard", category: "people", rule: "ie_ei" },
  { word: "neighbor", hint: "Someone who lives next door.", difficulty: "medium", category: "people", rule: "silent_letter", variants: { uk: "neighbour" } },
  { word: "achieve", hint: "To successfully reach a goal.", difficulty: "medium", category: "school", rule: "ie_ei" },
  { word: "although", hint: "Even though.", difficulty: "easy", category: "everyday", rule: "silent_letter" },
  { word: "business", hint: "Work done to earn money.", difficulty: "medium", category: "everyday", rule: "silent_letter" },
  { word: "column", hint: "A vertical line of text or a pillar.", difficulty: "easy", category: "school", rule: "silent_letter" },
  { word: "foreign", hint: "From another country.", difficulty: "medium", category: "everyday", rule: "ie_ei" },
  { word: "grateful", hint: "Feeling thankful.", difficulty: "medium", category: "people" },
  { word: "height", hint: "How tall something is.", difficulty: "easy", category: "everyday", rule: "silent_letter" },
  { word: "island", hint: "Land surrounded by water.", difficulty: "easy", category: "nature", rule: "silent_letter" },
  { word: "jewelry", hint: "Rings, necklaces, and bracelets.", difficulty: "medium", category: "home", rule: "tricky_ending", variants: { uk: "jewellery" } },
  { word: "library", hint: "A place full of books to borrow.", difficulty: "medium", category: "school" },
  { word: "medicine", hint: "Something you take when you are sick.", difficulty: "medium", category: "home" },
  { word: "opposite", hint: "Completely different, the other side.", difficulty: "medium", category: "everyday", rule: "tricky_ending" },
  { word: "possible", hint: "Able to happen or be done.", difficulty: "medium", category: "everyday" },
  { word: "question", hint: "Something you ask to get an answer.", difficulty: "easy", category: "school" },
  { word: "rhyme", hint: "Words that end with the same sound.", difficulty: "easy", category: "school", rule: "silent_letter" },
  { word: "schedule", hint: "A plan of times for events.", difficulty: "hard", category: "school", rule: "tricky_ending" },
  { word: "tomorrow", hint: "The day after today.", difficulty: "easy", category: "everyday", rule: "double_consonant" },
  { word: "umbrella", hint: "You open it to stay dry in the rain.", difficulty: "easy", category: "home", rule: "double_consonant" },
  { word: "vegetable", hint: "A plant food like carrots or peas.", difficulty: "hard", category: "food", rule: "silent_letter" },
  { word: "weather", hint: "Sun, rain, wind, or snow outside.", difficulty: "easy", category: "nature" },

  // ---------- expert: ultra-advanced vocabulary ----------
  { word: "conscientious", hint: "Careful to do things thoroughly and correctly.", difficulty: "expert", category: "people", rule: "tricky_ending" },
  { word: "onomatopoeia", hint: "A word that imitates the sound it describes, like 'buzz'.", difficulty: "expert", category: "school", rule: "vowel_confusion" },
  { word: "bureaucracy", hint: "A system of government with many officials and strict rules.", difficulty: "expert", category: "school", rule: "tricky_ending" },
  { word: "questionnaire", hint: "A set of written questions used to gather information.", difficulty: "expert", category: "school", rule: "double_consonant" },
  { word: "entrepreneur", hint: "Someone who starts and runs their own business.", difficulty: "expert", category: "everyday", rule: "tricky_ending" },
  { word: "chrysanthemum", hint: "A flower with colorful, feathery petals.", difficulty: "expert", category: "nature", rule: "silent_letter" },
  { word: "idiosyncrasy", hint: "A quirky habit unique to one person.", difficulty: "expert", category: "people", rule: "vowel_confusion" },
  { word: "connoisseur", hint: "Someone with expert taste in food, art, or wine.", difficulty: "expert", category: "food", rule: "double_consonant" },
  { word: "camouflage", hint: "A pattern that helps something blend into its surroundings.", difficulty: "expert", category: "nature", rule: "tricky_ending" },
  { word: "silhouette", hint: "A dark outline seen against a bright background.", difficulty: "expert", category: "everyday", rule: "silent_letter" },
  { word: "rhinoceros", hint: "A large animal with one or two horns on its nose.", difficulty: "expert", category: "nature", rule: "silent_letter" },
  { word: "acquaintance", hint: "Someone you know but who isn't a close friend.", difficulty: "expert", category: "people", rule: "tricky_ending" },
  { word: "millennium", hint: "A period of one thousand years.", difficulty: "expert", category: "school", rule: "double_consonant" },
  { word: "hierarchy", hint: "A system that ranks people or things by importance.", difficulty: "expert", category: "school", rule: "ie_ei" },
  { word: "phenomenon", hint: "A remarkable or unusual fact or event.", difficulty: "expert", category: "school", rule: "vowel_confusion" },
  { word: "pneumonia", hint: "A serious illness that affects the lungs.", difficulty: "expert", category: "home", rule: "silent_letter" },
  { word: "cappuccino", hint: "A coffee drink topped with frothy milk.", difficulty: "expert", category: "food", rule: "double_consonant" },
  { word: "kaleidoscope", hint: "A tube toy that makes colorful, shifting patterns.", difficulty: "expert", category: "everyday", rule: "ie_ei" },

  // ---------- more beginner words ----------
  { word: "bird", hint: "An animal that flies and has feathers.", difficulty: "beginner", category: "nature" },
  { word: "fish", hint: "An animal that swims and breathes underwater.", difficulty: "beginner", category: "nature" },
  { word: "tree", hint: "A tall plant with a trunk, branches, and leaves.", difficulty: "beginner", category: "nature" },
  { word: "star", hint: "A bright point of light in the night sky.", difficulty: "beginner", category: "nature" },
  { word: "moon", hint: "It circles the earth and glows at night.", difficulty: "beginner", category: "nature" },
  { word: "ball", hint: "A round toy you throw, kick, or bounce.", difficulty: "beginner", category: "everyday" },
  { word: "cake", hint: "A sweet treat you eat on a birthday.", difficulty: "beginner", category: "food" },
  { word: "bike", hint: "You pedal it to ride around.", difficulty: "beginner", category: "everyday" },
  { word: "rain", hint: "Water that falls from clouds.", difficulty: "beginner", category: "nature" },
  { word: "snow", hint: "Soft white flakes that fall when it's cold.", difficulty: "beginner", category: "nature" },
  { word: "shoe", hint: "You wear this on your foot.", difficulty: "beginner", category: "home" },
  { word: "hand", hint: "The part of your body at the end of your arm.", difficulty: "beginner", category: "people" },
  { word: "door", hint: "You open this to walk into a room.", difficulty: "beginner", category: "home" },
  { word: "desk", hint: "A table you sit at to write or study.", difficulty: "beginner", category: "school" },
  { word: "lamp", hint: "It gives you light in a dark room.", difficulty: "beginner", category: "home" },

  // ---------- more easy words ----------
  { word: "picture", hint: "An image, drawing, or photo.", difficulty: "easy", category: "everyday" },
  { word: "another", hint: "One more, or a different one.", difficulty: "easy", category: "everyday" },
  { word: "thought", hint: "An idea in your mind.", difficulty: "easy", category: "everyday", rule: "silent_letter" },
  { word: "through", hint: "Moving in one side and out the other.", difficulty: "easy", category: "everyday", rule: "silent_letter" },
  { word: "careful", hint: "Paying close attention to avoid mistakes.", difficulty: "easy", category: "people" },
  { word: "kitchen", hint: "The room where meals are cooked.", difficulty: "easy", category: "home" },
  { word: "morning", hint: "The early part of the day.", difficulty: "easy", category: "everyday" },
  { word: "evening", hint: "The part of the day before night.", difficulty: "easy", category: "everyday" },
  { word: "holiday", hint: "A special day off from school or work.", difficulty: "easy", category: "everyday" },
  { word: "cousin", hint: "The child of your aunt or uncle.", difficulty: "easy", category: "people", rule: "vowel_confusion" },
  { word: "sister", hint: "A girl who shares your parents.", difficulty: "easy", category: "people" },
  { word: "brother", hint: "A boy who shares your parents.", difficulty: "easy", category: "people" },
  { word: "teacher", hint: "Someone who helps you learn at school.", difficulty: "easy", category: "school" },
  { word: "student", hint: "Someone who is learning at school.", difficulty: "easy", category: "school" },
  { word: "journey", hint: "A trip from one place to another.", difficulty: "easy", category: "everyday", rule: "vowel_confusion" },
  { word: "hungry", hint: "Feeling like you need to eat.", difficulty: "easy", category: "everyday" },
  { word: "thirsty", hint: "Feeling like you need a drink.", difficulty: "easy", category: "everyday" },
  { word: "thankful", hint: "Feeling grateful for something.", difficulty: "easy", category: "people" },
  { word: "birthday", hint: "The day each year that celebrates when you were born.", difficulty: "easy", category: "everyday" },

  // ---------- more medium words ----------
  { word: "remember", hint: "To keep something in your memory.", difficulty: "medium", category: "school" },
  { word: "alphabet", hint: "The set of letters used to write a language.", difficulty: "medium", category: "school" },
  { word: "computer", hint: "A machine used to write, browse, and play games.", difficulty: "medium", category: "school" },
  { word: "continue", hint: "To keep doing something without stopping.", difficulty: "medium", category: "everyday" },
  { word: "decision", hint: "A choice you make after thinking it over.", difficulty: "medium", category: "everyday", rule: "tricky_ending" },
  { word: "exercise", hint: "Physical activity to stay healthy.", difficulty: "medium", category: "home", rule: "silent_letter" },
  { word: "furniture", hint: "Chairs, tables, and beds inside a home.", difficulty: "medium", category: "home", rule: "tricky_ending" },
  { word: "direction", hint: "The way you need to go to get somewhere.", difficulty: "medium", category: "everyday", rule: "tricky_ending" },
  { word: "character", hint: "A person in a story, or someone's personality.", difficulty: "medium", category: "school", rule: "silent_letter" },
  { word: "adventure", hint: "An exciting or unusual experience.", difficulty: "medium", category: "everyday" },
  { word: "chocolate", hint: "A sweet brown treat made from cacao.", difficulty: "medium", category: "food", rule: "silent_letter" },
  { word: "dangerous", hint: "Able to cause harm or injury.", difficulty: "medium", category: "everyday", rule: "tricky_ending" },
  { word: "difficult", hint: "Not easy to do or understand.", difficulty: "medium", category: "school" },
  { word: "vacation", hint: "A trip or break from school or work.", difficulty: "medium", category: "everyday" },
  { word: "mountain", hint: "A very tall, rocky landform.", difficulty: "medium", category: "nature", rule: "vowel_confusion" },
  { word: "thousand", hint: "The number 1,000.", difficulty: "medium", category: "everyday" },
  { word: "hospital", hint: "A place where sick or injured people are treated.", difficulty: "medium", category: "home" },

  // ---------- more hard words ----------
  { word: "dictionary", hint: "A book that lists words and their meanings.", difficulty: "hard", category: "school", rule: "tricky_ending" },
  { word: "temperature", hint: "How hot or cold something is.", difficulty: "hard", category: "nature", rule: "vowel_confusion" },
  { word: "disappear", hint: "To go out of sight suddenly.", difficulty: "hard", category: "everyday", rule: "double_consonant" },
  { word: "disappoint", hint: "To fail to meet someone's hopes.", difficulty: "hard", category: "people", rule: "double_consonant" },
  { word: "appreciate", hint: "To be grateful for something.", difficulty: "hard", category: "people", rule: "double_consonant" },
  { word: "communicate", hint: "To share information with someone.", difficulty: "hard", category: "everyday", rule: "double_consonant" },
  { word: "experience", hint: "Something you have lived through or done.", difficulty: "hard", category: "everyday", rule: "vowel_confusion" },
  { word: "imagination", hint: "The ability to picture things in your mind.", difficulty: "hard", category: "school" },
  { word: "information", hint: "Facts or details about something.", difficulty: "hard", category: "school", rule: "tricky_ending" },
  { word: "personality", hint: "The set of traits that make someone who they are.", difficulty: "hard", category: "people" },
  { word: "professional", hint: "Relating to a paid, skilled job.", difficulty: "hard", category: "school", rule: "double_consonant" },
  { word: "unfortunately", hint: "Used to say something unlucky happened.", difficulty: "hard", category: "everyday" },
  { word: "responsibility", hint: "A duty you are expected to handle.", difficulty: "hard", category: "everyday", rule: "tricky_ending" },
  { word: "extraordinary", hint: "Very unusual or remarkable.", difficulty: "hard", category: "everyday", rule: "vowel_confusion" },
  { word: "conscience", hint: "The inner sense of right and wrong.", difficulty: "hard", category: "people", rule: "silent_letter" },

  // ---------- more expert words ----------
  { word: "pronunciation", hint: "The way a word is spoken aloud.", difficulty: "expert", category: "school", rule: "tricky_ending" },
  { word: "miscellaneous", hint: "Made up of many different, unrelated things.", difficulty: "expert", category: "everyday", rule: "vowel_confusion" },
  { word: "unprecedented", hint: "Never having happened before.", difficulty: "expert", category: "school" },
  { word: "indispensable", hint: "So important that you cannot do without it.", difficulty: "expert", category: "everyday", rule: "tricky_ending" },
  { word: "subconscious", hint: "Part of the mind you're not actively aware of.", difficulty: "expert", category: "people", rule: "silent_letter" },
  { word: "exaggerate", hint: "To describe something as bigger than it really is.", difficulty: "expert", category: "everyday", rule: "double_consonant" },
  { word: "maintenance", hint: "The work of keeping something in good condition.", difficulty: "expert", category: "everyday", rule: "tricky_ending" },
  { word: "questionable", hint: "Doubtful or open to suspicion.", difficulty: "expert", category: "everyday" },
  { word: "perseverance", hint: "Continued effort despite difficulty.", difficulty: "expert", category: "people" },
  { word: "vulnerable", hint: "Easily hurt or exposed to harm.", difficulty: "expert", category: "people", rule: "vowel_confusion" },

  // ---------- US/UK spelling-variant pairs (spelled American by default) ----------
  { word: "color", hint: "Red, blue, green, or any shade like them.", difficulty: "easy", category: "everyday", variants: { uk: "colour" } },
  { word: "honor", hint: "Great respect, or to keep a promise.", difficulty: "easy", category: "people", variants: { uk: "honour" } },
  { word: "flavor", hint: "The taste of a food or drink.", difficulty: "easy", category: "food", variants: { uk: "flavour" } },
  { word: "humor", hint: "The quality of being funny.", difficulty: "easy", category: "people", variants: { uk: "humour" } },
  { word: "labor", hint: "Hard work.", difficulty: "easy", category: "everyday", variants: { uk: "labour" } },
  { word: "rumor", hint: "A piece of unconfirmed gossip.", difficulty: "medium", category: "people", variants: { uk: "rumour" } },
  { word: "harbor", hint: "A sheltered place where ships dock.", difficulty: "medium", category: "nature", variants: { uk: "harbour" } },
  { word: "vapor", hint: "A cloud-like gas, like steam.", difficulty: "medium", category: "nature", variants: { uk: "vapour" } },
  { word: "center", hint: "The middle point of something.", difficulty: "easy", category: "everyday", variants: { uk: "centre" } },
  { word: "theater", hint: "A place where you watch plays or movies.", difficulty: "medium", category: "everyday", variants: { uk: "theatre" } },
  { word: "meter", hint: "A unit used to measure length.", difficulty: "easy", category: "school", variants: { uk: "metre" } },
  { word: "liter", hint: "A unit used to measure liquid.", difficulty: "easy", category: "everyday", variants: { uk: "litre" } },
  { word: "fiber", hint: "A thin thread, or part of food that aids digestion.", difficulty: "medium", category: "food", variants: { uk: "fibre" } },
  { word: "organize", hint: "To arrange things in a neat, orderly way.", difficulty: "medium", category: "school", variants: { uk: "organise" } },
  { word: "realize", hint: "To suddenly understand something.", difficulty: "medium", category: "everyday", variants: { uk: "realise" } },
  { word: "recognize", hint: "To know someone or something you've seen before.", difficulty: "hard", category: "school", variants: { uk: "recognise" } },
  { word: "apologize", hint: "To say sorry for a mistake.", difficulty: "medium", category: "people", variants: { uk: "apologise" } },
  { word: "memorize", hint: "To learn something so well you know it by heart.", difficulty: "medium", category: "school", variants: { uk: "memorise" } },
  { word: "catalog", hint: "A list of items you can look through or order from.", difficulty: "medium", category: "school", variants: { uk: "catalogue" } },
  { word: "dialog", hint: "A conversation between two or more people.", difficulty: "medium", category: "school", variants: { uk: "dialogue" } },
  { word: "defense", hint: "Protection against attack or harm.", difficulty: "medium", category: "everyday", variants: { uk: "defence" } },
  { word: "license", hint: "Official permission to do something, like drive.", difficulty: "medium", category: "everyday", variants: { uk: "licence" } },
  { word: "traveling", hint: "Going from one place to another.", difficulty: "medium", category: "everyday", rule: "double_consonant", variants: { uk: "travelling" } },
  { word: "canceled", hint: "Called off; not going to happen anymore.", difficulty: "medium", category: "everyday", rule: "double_consonant", variants: { uk: "cancelled" } },
  { word: "gray", hint: "A color between black and white.", difficulty: "beginner", category: "everyday", variants: { uk: "grey" } },
  { word: "pajamas", hint: "Comfortable clothes you wear to sleep.", difficulty: "easy", category: "home", variants: { uk: "pyjamas" } },
  { word: "mustache", hint: "Hair grown above the upper lip.", difficulty: "medium", category: "people", variants: { uk: "moustache" } },
  { word: "fulfill", hint: "To carry out a promise or duty.", difficulty: "medium", category: "everyday", rule: "double_consonant", variants: { uk: "fulfil" } }
];

const WORD_CATEGORIES = [
  { value: "all", label: "All" },
  { value: "everyday", label: "Everyday" },
  { value: "people", label: "People" },
  { value: "school", label: "School" },
  { value: "nature", label: "Nature" },
  { value: "food", label: "Food" },
  { value: "home", label: "Home" },
];

// Short, proactive tips shown before a word that fits a known tricky spelling pattern.
const RULE_TIPS = {
  ie_ei: "Tricky i/e pattern — “i before e, except after c”... though this word might be an exception.",
  double_consonant: "This word doubles a letter in the middle — say it slowly and picture both of them.",
  silent_letter: "Watch out — this word has a silent letter that isn't pronounced at all.",
  tricky_ending: "The ending isn't spelled the way it sounds — it's worth memorizing as one chunk.",
  vowel_confusion: "Easy to mix up the vowels here — look closely at each one before you start.",
};

// Human-readable labels for each rule, used on the "weak patterns" history view.
const RULE_LABELS = {
  ie_ei: "I/E confusion",
  double_consonant: "Double letters",
  silent_letter: "Silent letters",
  tricky_ending: "Tricky endings",
  vowel_confusion: "Vowel mix-ups",
};
